### ISSUE TITLE
Build fails on Fedora 35 due to bad -L setting

### ISSUE THREAD

**Issue by flyn-org** [libvmi/libvmi#1002]
Building libvmi-0.14.0 on Fedora 35 with the following commands results in the indicated error:
```
$ mkdir build
$ cd build
$ cmake ..
$ make VERBOSE=1
[...]
/usr/bin/cc  -Wall -Wextra -g -g3 -O0  -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -rdynamic CMakeFiles/map-addr.dir/map-addr.c.o -o map-addr  -Wl,-rpath,/home/mike/Download/libvmi-0.14.0/build/libvmi ../libvmi/libvmi.so.0.0.14 -L/usr/lib64glib-2.0 
/usr/bin/ld: ../libvmi/libvmi.so.0.0.14: undefined reference to `g_direct_hash'
/usr/bin/ld: ../libvmi/libvmi.so.0.0.14: undefined reference to `g_tree_new_full'
/usr/bin/ld: ../libvmi/libvmi.so.0.0.14: undefined reference to `g_slist_free_full'
[...]
collect2: error: ld returned 1 exit status
```
Notice the use of `-L/usr/lib64glib-2.0`. A `/` is missing from the path, and the directory contains headers, not libraries.

**Comment by flyn-org** [comment]
I am not sure if this is a Fedora bug. See also https://bugzilla.redhat.com/show_bug.cgi?id=2031182.

**Comment by Wenzel** [comment]
hi @flyn-org,
I had a similar issue while trying to fix a bug on the Python bindings:
https://github.com/libvmi/python/pull/76#issuecomment-983403966

Could you try to compile with autotools to check if it's not a CMake issue ? (I'm thinking some weird string replacement that 's gone wrong)

**Comment by besser82** [comment]
See https://src.fedoraproject.org/rpms/libvmi/c/3d132c9990c0377fcf1b7c7faea159d4d5e9722a for a fix.

**Comment by Wenzel** [comment]
Thanks @besser82 
So these are the problematic lines:
https://github.com/libvmi/libvmi/blob/master/CMakeLists.txt#L32
https://github.com/libvmi/libvmi/blob/master/libvmi/CMakeLists.txt#L40

This has been added to cleanup the get a "clean" `glib_ldflags`, in order for to be used when generating the libtool file:
The libtool libraries dependencies are appended in this variable, by prefixing with `-l` each time
https://github.com/libvmi/libvmi/blob/master/libvmi/CMakeLists.txt#L221

If you remove this cleanup, it will result in having a libtool `dependency_libs` expanded such as this:
~~~
# Libraries that this one depends upon
dependency_libs=' -l-lglib-2.0 -ljson-c -ldl'
~~~
which is not correct

There are multiple questions here:
- why `pkg_search_module(GLIB REQUIRED glib-2.0)` results in `GLIB_LDFLAGS` prefixed by `-l`, whereas `find_package(JSON-C)` results  `JSON-C_LIBRARIES` var being just `json-c`
- What's the output of `GLIB_LDFLAGS` on Fedora 35 (before the cleanup) ? And why the string replace fails ?

**Comment by besser82** [comment]
@Wenzel I assume, the commit message of my PR answers your question?

**Comment by Wenzel** [comment]
yes ! thank you for looking into it :)
I missed this variable in https://cmake.org/cmake/help/latest/module/FindPkgConfig.html

**Comment by flyn-org** [comment]
https://github.com/libvmi/libvmi/pull/1003 works here. Thank you, @besser82! I will close this once a solution is merged.

**Comment by besser82** [comment]
@flyn-org You're welcome!  Merging my PR should close this issue automatically, btw.
