### ISSUE TITLE
`vmi_get_va_pages()` takes several minutes to complete on Windows

### ISSUE THREAD

**Issue by rageagainsthepc** [libvmi/libvmi#1052]
Hi!

I've noticed that `vmi_get_va_pages()` takes several minutes on Windows (Win10_21H2 specifically) in contrast to Linux where it is almost instant. If you count the entries in the result list it is close to one billion. If you count how many times a single physical page is mapped by the process it will yield a result similar to this output:
```
[    4] System (struct addr:ffffe1013b8a4040)
page addr 82837504 count 809529504
page addr 1052672 count 1572838
page addr 83886080 count 140567
page addr 84934656 count 8192
page addr 82845696 count 3070
page addr 85983232 count 270
page addr 983040 count 191
page addr 4227899392 count 129
page addr 4043309056 count 4
page addr 82849792 count 4
page addr 745472 count 3
page addr 671744 count 3
page addr 749568 count 3
page addr 753664 count 3
page addr 757760 count 3
page addr 761856 count 3
page addr 765952 count 3
page addr 770048 count 3
page addr 774144 count 3
page addr 778240 count 3
page addr 782336 count 3
page addr 663552 count 3
page addr 659456 count 3
page addr 667648 count 3
page addr 655360 count 3
page addr 737280 count 3
page addr 675840 count 3
page addr 679936 count 3
page addr 684032 count 3
page addr 741376 count 3
page addr 688128 count 3
page addr 692224 count 3
[...]
```
Note that while I've only provided the output for the system process other processes show similar behavior.
Peeking into the memory content of those pages that are on the top of this list reveals that they seem to consist of either null bytes or periodic patterns.

So, my question is: Does anybody know what feature of Windows causes this behavior? What would be the best way to reduce the performance cost?

**Comment by tklengyel** [comment]
That doesn't sound right. Can you double-check what Volatility thinks are the available pages using https://github.com/volatilityfoundation/volatility/wiki/Address-Spaces#get_available_pages?

**Comment by tklengyel** [comment]
That's your clue then. LibVMI's get_va_pages was originally modeled on Volatility's approach, they might have changed some things which makes their parser more accurate. Diff the two, find where things get off the rails in LibVMI and patch. ;)

**Comment by rageagainsthepc** [comment]
Will do, as time permits.

**Comment by rageagainsthepc** [comment]
A small update: I've stumbled onto [this](https://github.com/volatilityfoundation/volatility3/pull/475) PR in volatility. TLDR: It looks like in the case of transition pages some of the higher bits that belong to the PFN are used for flags on newer versions of Windows. Since Windows currently only supports up to [24TB of RAM](https://learn.microsoft.com/en-us/windows/win32/memory/memory-limits-for-windows-releases), bits 45-48 can be used for other purposes as long as they don't mess with the MMU. Will provide a fix soon...

**Comment by rageagainsthepc** [comment]
Ok, the problem with the high bits for transition pages is apparently unrelated to this issue. But it looks like volatility has got some code to handle deduplication of pages. https://github.com/volatilityfoundation/volatility/blob/a438e768194a9e05eb4d9ee9338b881c0fa25937/volatility/plugins/addrspaces/amd64.py#L304
