### ISSUE TITLE
Using libvmi with a memory dump file from ARM64 Xen VM

### ISSUE THREAD

**Issue by thehoustonian** [libvmi/libvmi#1057]
I have been trying to use libvmi to interact with a memory dump file of an ARM64 Xen guest, and I've been running into some issues getting it working.

I'm running Xen 4.16 on a Xilinx ZCU102 development board (ARM64 PetaLinux) with a single ARM64 DomU guest, and I've tried generating a memory dump with the `dump-memory.c` example program included with libvmi as well as using Xen's `xl dump-core` feature. When using `libvmi` in this setup with the live VM everything works as expected, but when I try to run the same program against the dump file, I get errors. I'm currently using the `process-list.c` example program. Here's the debug output: 
```
--found file
Running Bareflank CPUID signature: 0 0 0 0
LibVMI Version 0.15.0
LibVMI Driver Mode 2
--completed driver init.
**set image_type = paravirtual-core-dump
**set allocated_ram_size = 7d3ace57, max_physical_address = 0x7d3ace57
--looking for config file at /home/dese/github/libvmi/build/examples/libvmi.conf
--looking for config file at /home/dese/etc/libvmi.conf
**set os_type to Linux.
--got vaddr for swapper_pg_dir (0xffff80000918d000).
--trying boundary 0x00000000c0000000.
--V2P cache miss (no address space) 0xffff7fff4918d000 0x0000000000000000
--PTLookup: lookup vaddr = 0xffff80000918d000, pt = 0xffff7fff4918d000
--Reading pfn 0x0
--MEMORY cache set 0x0
--PTLookup: pgd_entry = 0x00000090
--PTLookup: pgd_entry = 0x00000000
--PTLookup: pgd = 0x00000000
--PTLookup: paddr = 0x0000000000000000
--V2P cache miss (no address space) 0xffff7fff4918d000 0x0000000000000000
--PTLookup: lookup vaddr = 0xffff80000918d000 dtb = 0xffff7fff4918d000
--Reading pfn 0xffff7fff4918d
--MEMORY cache set 0xffff7fff4918d000
--requested PA [0xffff7fff4918d000-0xffff7fff4918e000] is outside valid physical memory
create_new_entry failed
```

I believe these are happening in https://github.com/libvmi/libvmi/blob/9dee43cdd87d0795f3aa9252a77107ca30518abb/libvmi/os/linux/core.c#L122 . 

I was able to get a little further by hardcoding some values that would normally be determined dynamically, like manually setting `vmi->kpgd` [here](https://github.com/libvmi/libvmi/blob/9dee43cdd87d0795f3aa9252a77107ca30518abb/libvmi/os/linux/core.c#L562) and setting the `vmi->arm64.t0sz`, `vmi->arm64.tg0`, etc values to what was given by the live VM. However, I then run into the following error: "Invalid or not supported paging mode during get_va_pages", and finally get an error about failing to determine the KASLR offset. 

I could probably continue cross-referencing between the behavior with a live VM and the memory dump file to hard code more values, but I wanted to post an issue and get some feedback in case I'm making this more difficult than it's expected to be.

Also, if this is not expected to work, which hypervisors and architectures are supported when interacting with memory dump files? 

Thanks!

**Comment by tklengyel** [comment]
Using memory dumps is not really well supported by LibVMI. I don't think using ARM dumps was ever tested so what you run into is somewhat expected. I would suggest instead of creating a dump you just save the VM and restore it (`xl restore -p`) potentially with a changed config so it has a different name then the original so you can inspect it with LibVMI.

**Comment by thehoustonian** [comment]
Ah, I see. I'll close this issue in that case then. Thanks!
