### ISSUE TITLE
Consistent use of `vmi->init_task` in Windows driver

### ISSUE THREAD

**Issue by awsaba** [libvmi/libvmi#218]
The functions `find_pname_offset` and `find_process_by_name` set and use `init_task` as a physical address, but the various `find_kpgd` methods set it to a virtual address.

Once this is fixed and correct, the `find_eprocess...` methods can be changed to use `init_task` instead of looking up `PsInitialSystemProcess`.

**Comment by tklengyel** [comment]
find_pname_offset still searches for the Idle process, switch it to System?
