### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by darix** [libvmi/libvmi#232]
with all the attention that this project might get from the 31c3 talk it might be nice to have a new release tagged.

I don't think packaging a release from 2013 would be something you want.

**Comment by tklengyel** [comment]
Thanks, this has been something we privately discussed with the other core developers too. The main issue is that at the moment it is somewhat arbitrary when we cut a release from git. So the discussion was whether we just want a rolling release from the master git branch vs. formal releases.

Community input on the topic is of course more then welcome =)

**Comment by darix** [comment]
I watched the presentation and would be happy to package libvmi for openSUSE. i can go with snapshots if that is wanted. but regular releases wouldnt harm either.

**Comment by bdpayne** [comment]
I'm open to cutting a new release.  Let's get the test infra up and running and then just move ahead with the cut.

**Comment by bdpayne** [comment]
@darix With regard to packaging for openSUSE, that would be wonderful.  Let's wait and use the upcoming release for that.  Should be a 0.12 coming out in the next week or so.

**Comment by Wenzel** [comment]
Hello,
what's the status of this issue ?

maybe we could release a new version of libvmi, like 0.2 ?

**Comment by tklengyel** [comment]
Yes, I think once we have some of the open PRs merged (vmi init fix) we should be good to cut a new release.
