### ISSUE TITLE
Allow `vmi_pagetable_lookup_extended` to return 0 as a valid physical address

### ISSUE THREAD

**Issue by awsaba** [libvmi/libvmi#248]
`vmi_pagetable_lookup_extended` should return VMI_SUCCESS and `info->paddr = 0` if the virtual address really does resolve to physical address 0.  This is very unlikely, but possible.

This change will probably involve modifications to the arch `v2p` functions, since whether or not this condition is an error can be detected there and by the driver if 0 is not a valid physical address.

**Comment by awsaba** [comment]
This is mostly addressed by #247 and #251; however, `vmi_pagetable_extended()` has not yet been changed to return status_t.

**Comment by tklengyel** [comment]
We also would want to switch vmi_translate_kv2p, vmi_translate_uv2p, vmi_translate_ksym2v, vmi_translate_sym2v to return status_t.
