### ISSUE TITLE
Assess current state of shm-snapshot feature

### ISSUE THREAD

**Issue by smaresca** [libvmi/libvmi#250]
The shm-snapshot capabilities introduced at the tail end of 2013 has suffered some bitrot.

Should we maintain or excise?

**Comment by smaresca** [comment]
I started to take a look at its state and will have a better sense of our options soon.

regarding release: We can always carry the current code forward through the release, deferring the decision but marking it as experimental/not supported.

**Comment by tklengyel** [comment]
As already discussed internally, this is a non-blocker for the release IMHO as it is not enabled/compiled by default.
