### ISSUE TITLE
Error mapping PE Export Table

### ISSUE THREAD

**Issue by tklengyel** [libvmi/libvmi#260]
On certain Win7 SP1 x64 images mapping the export table of DLLs fails with the following log:

--PEParse: magic is 0x20b
--PEParse: DLL base [VA] 0x0000000076c10000. Export header [RVA] 0x000000000009fffc. Size 44279.
--PID cache hit 2132 -- 0x0000000047f33000
--PTLookup: lookup vaddr = 0x0000000076cafffc
--PTLookup: dtb = 0x0000000047f33000
--PTLookup: pml4e_address = 0x0000000047f33000
--MEMORY cache hit 0x47f33000
--PTLookup: pml4e = 0x00c0000047f37867
--PTLookup: pdpte_address = 0x0000000047f37008
--MEMORY cache hit 0x47f37000
--PTLookup: pdpte = 0x01500000485be867
--PTLookup: pde_address = 0x00000000485bedb0
--MEMORY cache hit 0x485be000
--PTLookup: pde = 0x07100000492ec867
--PTLookup: pte_address = 0x00000000492ec578
--MEMORY cache hit 0x492ec000
--PTLookup: pte = 0x0000000000000000
--PTLookup: paddr = 0x0000000000000000
--PEParse: failed to map export header
--PEParse: failed to get export table

The VA where the export table should be doesn't seem to be mapped into the process, verified via Volatility as well: 

In [1]: cc(pid=2132)
Current context: taskmgr.exe @ 0xfffffa8001ed3330, pid=2132, ppid=1052 DTB=0x47f33000
In [2]: dd(0x0000000076cafffc)
Memory unreadable at 76cafffc

However, when dumping the DLL via Volatility, the carved DLL does contain the correct export table. Root cause of the issue is TBD.

**Comment by kirschju** [comment]
.rdata:0000000076CAFFFC ; Export directory for KERNEL32.dll
.rdata:0000000076CAFFFC ;
.rdata:0000000076CAFFFC                 dd 0                    ; Characteristics
.rdata:0000000076CB0000                 dd 53158EADh            ; TimeDateStamp: Tue Mar 04 08:28:29 2014
.rdata:0000000076CB0004                 dw 0                    ; MajorVersion
.rdata:0000000076CB0006                 dw 0                    ; MinorVersion
.rdata:0000000076CB0008                 dd rva aKernel32_dll    ; Name
.rdata:0000000076CB000C                 dd 1                    ; Base
.rdata:0000000076CB0010                 dd 570h                 ; NumberOfFunctions
.rdata:0000000076CB0014                 dd 570h                 ; NumberOfNames
.rdata:0000000076CB0018                 dd rva off_76CB0024     ; AddressOfFunctions
.rdata:0000000076CB001C                 dd rva off_76CB15E4     ; AddressOfNames
.rdata:0000000076CB0020                 dd rva word_76CB2BA4    ; AddressOfNameOrdinals

For some reason the table is mapped to next page. The actual offset you're looking for is orig_offset + 1.
