### ISSUE TITLE
Memory events with npages>1 will crash

### ISSUE THREAD

**Issue by felixwilhelm** [libvmi/libvmi#262]
Triggering a memory event that was registered with npages>1 crashes with an error message like this:
```VMI_ERROR: Caught a memory event that had no handler registered in LibVMI @ GFN 41624 (0xa2989af), access: 4```

The reason seems to be that the hashtable lookup in process_mem fails for all pages except for the primary one. (https://github.com/libvmi/libvmi/blob/master/libvmi/driver/xen/xen_events.c#L464)

I'm not sure if adding a hashtable entry for each page is the right solution or if the npages attribute should just be dropped.

**Comment by tklengyel** [comment]
npages>1 is currently not supported by LibVMI.

Cheers,
Tamas

**Comment by smaresca** [comment]
We'll likely revisit this one in the future, but closing for now.

**Comment by smaresca** [comment]
To guard against a crash, I'll add a warning+return failure if npages>1. In the future, it'll be remedied using a range check of some form.
