### ISSUE TITLE
Investigate replacing peparse with LibPE

### ISSUE THREAD

**Issue by tklengyel** [libvmi/libvmi#265]
TODO. Instead of rolling our own pe parser, we could integrate with LibPE (LGPL) library.. Less maintenance and more eyes on the code.

https://github.com/merces/libpe

**Comment by tklengyel** [comment]
LibPE unfortunately has many hard-coded parts for working with filestreams so this would be more tricky then it seems.

**Comment by jweyrich** [comment]
Sorry for bringing this up. What interface did you looked for when you considered libpe? Depending on what you need, I might devote some time to add support.

**Comment by tklengyel** [comment]
@jweyrich we have an internal PE parser at the moment in LibVMI (https://github.com/libvmi/libvmi/blob/master/libvmi/os/windows/peparse.c) and I would have wanted to replace that with libpe. The main blocker that I saw in libpe is that it is written with the assumption that you will be dealing with a memory-mapped file, which in the case of VMI is not the case. We can't pass in a `FILE*` to libpe nor can we simply `mmap` the whole PE binary right from the start, because we don't yet know where exactly all the pieces of the binary are located in the VM's memory. The binary might be mapped across page-boundaries for example, with the underlying physical memory for those pages being far away from each other. So the whole structure has to be processed piece by piece until we have everything.

So for example lets consider that we have a DOS header already copied into a local buffer, the `offset_to_pe` needs to be added to the virtual address of the DOS header, then translated to physical memory, then read into a buffer where it can be interpreted as the PE header. This means that there is a chance there is a large hole between the DOS header and the PE header when looked at it on the physical memory level. 

So effectively everywhere libpe uses `LIBPE_PTR_ADD` to access various parts of the binary would have to be configurable to assume either a memory-mapped file, or a libvmi virtual memory read. And that looks like quite a refactor.
