### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [libvmi/libvmi#272]
Would you like to add more error handling for return values from functions like the following?
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator in a stream.") ⇒ [memRead_4](https://github.com/libvmi/libvmi/blob/5050568269b11bc8baa247a1e6748df604e6da08/tools/windows-offset-finder/getGUID.cpp#L89)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [main](https://github.com/libvmi/libvmi/blob/5050568269b11bc8baa247a1e6748df604e6da08/tools/performance/read_mem.c#L36)

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
I would appreciate more constructive feedback for this issue.

**Comment by tklengyel** [comment]
Certainly. The files having these minor issues are not core components of libvmi and after discussing it internally we decided that the risk is mininal in keeping them as they are. You are of course welcome to submit a PR that fixes them.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?
