### ISSUE TITLE
Cache invalidation needed

### ISSUE THREAD

**Issue by smaresca** [libvmi/libvmi#274]
Report from IRC channel:

<Sin__> there's a problem with the caching in libvmi.. i'm not sure exactly what causes it, if i have more time and figure it out i'll let you guys know
<Sin__> but it's definitely there, if i set a trap on sys_execve and read the string from the register corresponding to the pathname in a loop sooner or later a new process will have the same dtb as on older one and will read from somewhere elese
<hungrigerhugo> yes i had similiar problems
<hungrigerhugo> reseting the cache works in some situations

**Comment by smaresca** [comment]
may not be a bug per se..but would be ideal if detectable

**Comment by tklengyel** [comment]
yeap, for live systems it may be advisable to disable the address cache altogether (--disable-address-cache) as there is no automatic invalidation

**Comment by awsaba** [comment]
For live VMs, we usually call `v2p_cache_clear()` on every cr3 event.  Depending on the physical page cache usage, when the page tables are still mapped, building the v2p cache back up is usually not that bad.

**Comment by tklengyel** [comment]
The above two comments address the question at hand so I'm closing this ticket.
