### ISSUE TITLE
can not find system.map

### ISSUE THREAD

**Issue by chen0031** [libvmi/libvmi#276]
ERROR: could not find System.map file after checking:
	/boot/System.map-3.16.0-30-generic
To fix this problem, add the correct sysmap entry to /etc/libvmi.conf
VMI_ERROR: Could not get init_task from System.map
[]Failed to init LibVMI library.

**Comment by tklengyel** [comment]
Well, is your system map there, or is it not?

**Comment by tklengyel** [comment]
Closing this ticket for now because of lack of response.
