### ISSUE TITLE
Problem with "map-symbol.c" in examples

### ISSUE THREAD

**Issue by zjcxhschenxu** [libvmi/libvmi#277]
For example, I run with "map-symbol vm_01 sys_call_table"

Then I got the error:
could not obtain handle on privileged command interface(2= No such file or directory)...

result of "uname -a"
Linux vm-01-desktop 2.6.32-24-generic #39 -Ubuntu SMP Wed Jul 28 05:14:15 UTC 2010 x86_64 GNU/Linux

Need for help, thanks!

**Comment by chen0031** [comment]
Are you run your code in the root role?

**Comment by chen0031** [comment]
Did you run your code in the root role?

**Comment by tklengyel** [comment]
Closing this ticket, please run the tool as root or with sudo as recommended above.
