### ISSUE TITLE
How to get open file offset?

### ISSUE THREAD

**Issue by chen0031** [libvmi/libvmi#296]
Guys:
     There are examples for obtaining the offset addresses of task_struct, pid_struct, .... But how to obtain the open file struct (i.e.,  files_struct *files) offset?  Because I want to know the opened files for each process. I need your help, thank you very much!

**Comment by tklengyel** [comment]
You would have to go through the debug information for your kernel with pahole to find the correct offset. LibVMI doesn't have any capability to do this for you.
