### ISSUE TITLE
Use xc_domain_getinfolist in xen_get_domainid_from_name()

### ISSUE THREAD

**Issue by bentau** [libvmi/libvmi#304]
Iterating over the domains in the xenstore seems not be an good idea as a VM might not have the permissions in xenstore to do so. It seems to be better to use xc_domain_getinfolist to get the the list of running domains.

**Comment by tklengyel** [comment]
If the xenstore permissions don't allow you to query information, you can compile LibVMI with --without-xenstore flag to forgo all xenstore related operations.
