### ISSUE TITLE
LINK  x86_64-softmmu/qemu-system-x86_64

### ISSUE THREAD

**Issue by TahirAhmed916** [libvmi/libvmi#322]
i am trying to patch. when i run the ./configure command  following error occur.
Error: libpci header check failed
Disable KVM Device Assignment capability
when i use make command then after making some files following error occurs.
LINK  x86_64-softmmu/qemu-system-x86_64
/usr/bin/ld: ../qemu-timer.o: undefined reference to symbol 'timer_settime@@GLIBC_2.3.3'
/lib/x86_64-linux-gnu/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:378: recipe for target 'qemu-system-x86_64' failed
make[1]: *** [qemu-system-x86_64] Error 1
Makefile:84: recipe for target 'subdir-x86_64-softmmu' failed
make: *** [subdir-x86_64-softmmu] Error 2

when i use make install command then
LINK  x86_64-softmmu/qemu-system-x86_64
/usr/bin/ld: ../qemu-timer.o: undefined reference to symbol 'timer_settime@@GLIBC_2.3.3'
/lib/x86_64-linux-gnu/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:378: recipe for target 'qemu-system-x86_64' failed
make[1]: *** [qemu-system-x86_64] Error 1
Makefile:84: recipe for target 'subdir-x86_64-softmmu' failed
make: *** [subdir-x86_64-softmmu] Error 2

**Comment by tklengyel** [comment]
This seems to be a duplicate issue.
