### ISSUE TITLE
Broad platform support Issue

### ISSUE THREAD

**Issue by Absatasy** [libvmi/libvmi#325]
Hello,
I want to use LibVMI on Hikey Board. Can I run it on a 64-bit ARM Cortex-A53 architecture(Kirin620 does not support hardware virtualization so I have to emulate it totally by software)? And does it support an aarch64 Guest OS?
If so, are there some examples about how to use it? Most examples on your repository are based on x86, I don't know how to write a silimar example on a arm platform.
Thanks.

**Comment by tklengyel** [comment]
Aarch64 guest are not supported right now. The examples process-list and module-list work for aarch32 guests for sure on Xen.

**Comment by tklengyel** [comment]
PR #343 added support for ARM64 guests.
