### ISSUE TITLE
Is there more programs other than in libvmi/exapmles

### ISSUE THREAD

**Issue by TahirAhmed916** [libvmi/libvmi#327]
Hi i am searching more programs other than in libvmi/examples for introspection. Such as to check network connections on machine running on kvm and malware anaylsis of ubuntu machine running on kvm.

**Comment by tklengyel** [comment]
The point of LibVMI is that code using it would not have to be hypervisor specific. I'm not aware of other open source projects publicly available using LibVMi beside DRAKVUF.
