### ISSUE TITLE
Could not obtain handle on privileged command interface

### ISSUE THREAD

**Issue by TahirAhmed916** [libvmi/libvmi#328]
Hi facing the following error while i am trying to execute
test@ubuntu:~/libvmi-0.10.1/examples$ sudo ./process-list test-ubuntu
xc: error: Could not obtain handle on privileged command interface (2 = No such file or directory): Internal error
Process listing for VM test-ubuntu (id=3)
Failed to read next pointer at 0x338 before entering loop

i am using ubuntu machine in KVM.

**Comment by tklengyel** [comment]
You seem to have compiled LibVMI for Xen. When you run configure you need to make sure it detects KVM and not Xen. You probably have Xen headers on your system that you will need to remove.
