### ISSUE TITLE
Building libvmi fails when using "make -j 3"

### ISSUE THREAD

**Issue by MikePetullo** [libvmi/libvmi#350]
Building libvmi with "make -j 3" fails. Perhaps the Makefile is missing an explicit build dependency on grammar.h which causes parallel make to violate the proper build order.

libvmi-0.10.1]$ make clean all -j 3
[...]
make[1]: Leaving directory '/home/mike/Source/rpms/BUILD/libvmi-0.10.1'
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I../.. -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -c lexicon.c  -fPIC -DPIC -o .libs/lexicon.o
lexicon.l:30:21: fatal error: grammar.h: No such file or directory
 #include "grammar.h"
                     ^
compilation terminated.
Makefile:416: recipe for target 'lexicon.lo' failed
make[3]: *** [lexicon.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
updating grammar.h
make[3]: Leaving directory '/home/mike/Source/rpms/BUILD/libvmi-0.10.1/libvmi/config'
Makefile:828: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/mike/Source/rpms/BUILD/libvmi-0.10.1/libvmi'
Makefile:476: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/mike/Source/rpms/BUILD/libvmi-0.10.1'
Makefile:385: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tklengyel** [comment]
This is probably inherent to how automake works and the fact that you are sending the command to clean and to build all at the same time. Try just making one target at a time: `make -j3 clean; make -j3 all`

**Comment by tklengyel** [comment]
I'm closing this issue for now.

**Comment by pbraun9** [comment]
Ok with latest LibVMI from git and Drakvuf recompiled against it,
```
DRAKVUF v0.6-3868a26
Starting DRAKVUF initialization
drakvuf_event_fd_add fd=14
size of list=1
regenerating event_fds and fd_info_lookup...
new event_fd i=0 for fd=14
new fd_info_lookup i=0 for fd=14
drakvuf_init: adding event_fd done
Init VMI on domID 6 -> devuanhvm
init_vmi: initializing vmi done
Max GPFN: 0xff001
Max mem set? 0
Physmap populated? 0
Altp2m enabled? 0
Altp2m view X created? 0 with ID 1
Altp2m view R created? 0 with ID 2
Switched Altp2m view to X? 0
VMI_ERROR: xc_hvm_set_mem_access failed with code: -1
*** FAILED TO SET MEMORY TRAP @ PAGE 1044482 ***
Failed to create guard trap for the empty page!
starting close_vmi_drakvuf
close_vmi_drakvuf finished
libdrakvuf initialization failed
Failed to initialize DRAKVUF
```
