### ISSUE TITLE
libvmi does not always initialize correctly with Windows 10 using Rekall profiles

### ISSUE THREAD

**Issue by CMF-Marodeur** [libvmi/libvmi#354]
I added the required information for Windows 10 (analogue to tklengyels pull request #314), which generally works.
The problem is that libvmi does not always initialize (a problem i already faced when attaching to a Windows 7 image, but I did not investigate any further).

The problem seems to missing page table entries:

Working:
LibVMI Version 0.11.0
--found Xen
LibVMI Mode 2
--completed driver init.
--got id from name (domU-4 --> 33)
**set image_type = domU-4
**set hvm to true (HVM).
--xen: setup live mode
**set allocated_ram_size = 7fdde000, max_physical_address = 0xff000000
**set pae = 1
**set pse = 1
**set lme = 1
**IA-32e paging
**sanity checking cr3 = 0x000000002b75f000
--succesfully completed architecture init.
--looking for config file at (null)/etc/libvmi.conf
--looking for config file at /etc/libvmi.conf
**Using config file at /etc/libvmi.conf
**set os_type to unknown.
**Trying to init from Rekall profile
--PTLookup: lookup vaddr = 0xfffff801c4886000
--PTLookup: dtb = 0x0000000071162000
--MEMORY cache set 0x71162000
--xen_get_memory_pfn success on pfn=0x71162
--PTLookup: pml4e_address = 0x0000000071162f80
--MEMORY cache set 0x584000
--xen_get_memory_pfn success on pfn=0x584
--PTLookup: pdpte_address = 0x0000000000584038, pdpte_value = 0x0000000000585063
--MEMORY cache set 0x585000
--xen_get_memory_pfn success on pfn=0x585
--PTLookup: pde_address = 0x0000000000585120, pde_value= 0x0000000000593063
--MEMORY cache set 0x593000
--xen_get_memory_pfn success on pfn=0x593
--PTLookup: pte_address = 0x0000000000593430, pte_value = 0x8000000002c86963
--PTLookup: paddr = 0x0000000002c86000
--V2P cache set 0xfffff801c4886000 -- 0x0000000002c86000 (0x0000000071162000/0xfffff801c4886000)
**KernBase PA=0x2c86000
**KernBase VA=0xfffff801c4886000
--MEMORY cache set 0x2ed3000
--xen_get_memory_pfn success on pfn=0x2ed3
**init from Rekall profile success

Not working:
LibVMI Version 0.11.0
--found Xen
LibVMI Mode 2
--completed driver init.
--got id from name (domU-0 --> 21)
**set image_type = domU-0
**set hvm to true (HVM).
--xen: setup live mode
**set allocated_ram_size = 7fdde000, max_physical_address = 0xff000000
**set pae = 1
**set pse = 1
**set lme = 1
**IA-32e paging
**sanity checking cr3 = 0x000000002b75f000
--succesfully completed architecture init.
--looking for config file at (null)/etc/libvmi.conf
--looking for config file at /etc/libvmi.conf
**Using config file at /etc/libvmi.conf
**set os_type to unknown.
**Trying to init from Rekall profile
--PTLookup: lookup vaddr = 0x000000e493ef1000
--PTLookup: dtb = 0x0000000070bcb000
--MEMORY cache set 0x70bcb000
--xen_get_memory_pfn success on pfn=0x70bcb
--PTLookup: pml4e_address = 0x0000000070bcb008
--MEMORY cache set 0x6f3ec000
--xen_get_memory_pfn success on pfn=0x6f3ec
--PTLookup: pdpte_address = 0x000000006f3ecc90, pdpte_value = 0x013000006fc2d867
--MEMORY cache set 0x6fc2d000
--xen_get_memory_pfn success on pfn=0x6fc2d
--PTLookup: pde_address = 0x000000006fc2d4f8, pde_value= 0x0000000000000000
--PTLookup: paddr = 0x0000000000000000
**KernBase PA=0x0
**set os.windows_instance.pname_offset (0x450)
--searching for process by name: System

When trying to init libvmi a second time on the same VM the initialization succeeds.

**Comment by tklengyel** [comment]
Yea looks like the cr3 value is different between the two runs: ```--PTLookup: dtb = 0x0000000071162000``` and ```--PTLookup: dtb = 0x0000000070bcb000``` so it might just happen that the process doesn't have the required pages mapped (new process launching or it is exiting or for some other reason).

**Comment by CMF-Marodeur** [comment]
After the init fails libvmi seems to try to analyse the whole memory looking for a PE-file but never succeeds until the search eventually crashes with

> (process:10061): GLib-CRITICAL **: g_hash_table_destroy: assertion 'hash_table != NULL' failed

It sometimes seems to find files but the following steps seem to fail:

> --PEParse: magic is 0x20b
> --PEParse: Image data directory RVA is 0
> --MEMORY cache hit 0x2c158000
> --PEPARSE: DOS header signature not found
> --PEPARSE: failed to validate a continuous PE header
> --PEPARSE: You might want to use peparse_get_image_virt here! 

Or

> --PEParse: magic is 0x10b
> --MEMORY cache set 0x31848000
> --xen_get_memory_pfn success on pfn=0x31848
> --PEPARSE: DOS header signature not found
> --PEPARSE: failed to validate a continuous PE header
> --PEPARSE: You might want to use peparse_get_image_virt here!

Assuming the process simply lacks the required pages, do you have any idea how to fix this problem?

One idea to circumvent it ( at least in our use case ) would be to simply use a fixed KernBase PA since our VMs are restored from a state file and therefore should all have the same KernBase PA.
While I imagine that this could work, it cannot be called a solution to this problem.

**Comment by awsaba** [comment]
libvmi accepts combinations of `win_sysproc`, `win_kdvb`, `win_kdbg` and `win_ntoskrnl` in order to avoid this time consuming (at best) and sometimes error prone search when connecting to a known VM.  I'd have to look into it to make sure that those shortcuts are used when initializing from a rekall profile, I haven't looked at that code in a while.  If they aren't, that is an enhancement that should be made.

I understand not feeling that this is an elegant solution, but sophisticated, full featured applications most likely need those values and more that can't be found by easily automated methods, so moving some of that logic to the application is viable for a lot of environments.  In fact, not leaving enough of that up to the application has been a criticism of libvmi's current architecture.

**Comment by tklengyel** [comment]
> has been a criticism of libvmi's current architecture

[citation needed] ;)

**Comment by awsaba** [comment]
@tklengyel that's how I interpreted the first bullet points in con/pro lists (towards the end of the post): https://blog.xenproject.org/2015/08/04/the-bitdefender-virtual-machine-introspection-library-is-now-on-github/

**Comment by tklengyel** [comment]
@awsaba  Which points exactly? I mean currently the user is free to do partial init + paging init on the domain without needing to define any of these values.

**Comment by awsaba** [comment]
> in order to work properly, LibVMI requires that you install a configuration file into either $HOME/etc  /libvmi.conf or /etc/libvmi.conf, with a set of entries for each virtual machine or memory image that LibVMI will access (while it is possible to use it without extracting this detailed information, doing so severely limits available guest information, and it does reflect a core design concern);

vs. 

> it (libbdvmi) only connects an introspection logic component to the guest, leaving on-the-fly OS detection and decision-making to it;

I agree that it is possible to do this with libvmi as you suggest (and so that point by the author is flawed), but it's not really well documented or has a good example.

Applied to this issue, I think it's a reasonable solution for an application, but one that might seem to go against the design or intent of libvmi's responsibilities.

**Comment by tklengyel** [comment]
Yea, it's not documented too well unfortunately but overall I think libvmi was designed with fairly flexible API to blend to many different use-cases. So for this case for example I agree, it would be fine to manually define the config values if they are known beforehand rather then relying on the automatic methods.

**Comment by CMF-Marodeur** [comment]
After taking another look at this issue the problem seems to be a bad kpcr in the init_from_rekall_profile.
In case of VMI_PM_IA32E the kpcr is taken from the GS_BASE register. As far as I know this approach only works if the process from which the register is taken actually is a 64bit process. A WOW64 process will fail at this point since the computation
`windows->ntoskrnl_va = kpcr - kpcr_rva;`
will be wrong.
Sometimes resulting in an underflow, sometimes simply in wrong values.

`kpcr=0x318000 kpcr_rva=0x31d000
--PTLookup: lookup vaddr = 0xffffffffffffb000`

`kpcr=0x85eaf3a000 kpcr_rva=0x31d000
--PTLookup: lookup vaddr = 0x00000085eac1d000`

The bogus vaddr in turn leads to a failing vmi_translate_kv2p.

I think catching the error should be easy since a valid kpcr should be in the memory region used by the windows kernel ( 0xffff800000000000+), while the GS_BASE-value of an WOW64 process most likely will not.
A way to get a valid kpcr on the other hand would be even better. ^^

**Comment by tklengyel** [comment]
Indeed, I'll add a check for that. However, without activating events and waiting for a 64-bit process to get scheduled I'm not sure how we would be able to get this working.

**Comment by CMF-Marodeur** [comment]
Waiting for a 64-bit process was also my first idea... I was hopping you had a better idea how this could be achieved. ^^

I`m thinking about a way to pass default values to the vmi_init to circumvent this problem in our use case, but I don`t want to simply hack something into libvmi. Instead I would like to code something that follows the spirit of libvmi and could end up in the main branch.
My idea would be to pass a default vmi->os_data to an overloaded vmi_init which then would call vmi_init_private with an additional "FALLBACK_VALUES" flag.
If this flag is set windows_init / linux_init don`t zero the vmi->os_data but instead try to take the default values.

As far as I can see this would require the windows_instance_t / linux_instance_t to be made public (in libvmi.h), an overloaded vmi_init and some changes in the windows_init / linux_init as well as in the corresponding init_from_rekall_profile.

Any remarks / improvements / better ideas?

**Comment by tklengyel** [comment]
So in my latest windows10 branch I made it that if the Rekall profile based init fails it will fall back to the old init modes, so you can define the kernel base address next to the Rekall profile as a safety option.

**Comment by tklengyel** [comment]
PR #358 added support for a work-around when the KPCR pointed to by vCPU0 is not KiInitialPCR.
