### ISSUE TITLE
vmi_step_event function fails to clear its single step event

### ISSUE THREAD

**Issue by ryan-johnson2** [libvmi/libvmi#377]
While using the vmi_step_event function in conjuction with an interrupt event to trace system calls, I found that the vmi_step_event function failed to clear the single_step it created and caused the guest machine to hang and the VMI instance to continuously trap on singlestep events.

```
Disabling event on interrupt: 1
CALL STEP EVENT
--Starting single step on domain 3
--Setting MTF flag on vcpu 0
Enabling single step
--RET INT3

--Finished handling event.
--Waiting for xen events...(500 ms)
--Caught single step event!
--STP
PAUSE
GET RIP VAL
RIP: ffffffff81645893
GET LSTAR
LSTAR: ffffffff81645890
WRITE BP TO MEM AT LSTAR: ffffffff81645890
--V2P cache hit 0xffffffff81645890 -- 0x0000000001645890 (0x000000003ae71000/0xffffffff81645000)
--MEMORY cache hit 0x1645000
--xen_get_memory_pfn success on pfn=0x1645
READ NEW MEM AT LSTAR
--V2P cache hit 0xffffffff81645890 -- 0x0000000001645890 (0x000000003ae71000/0xffffffff81645000)
--MEMORY cache set 0x1645000
--xen_get_memory_pfn success on pfn=0x1645
--MEMORY cache hit 0x1645000
MEM AT LSTAR --ffffffff81645890-- NOW 0xcc
RESUME
REGISTER INT3 EVENT
Enabled event on interrupt: 1
--RET SP

--Finished handling event.
Cannot clear unknown event: 0
--Waiting for xen events...(500 ms)
--Caught single step event!
--Finished handling event.
--Waiting for xen events...(500 ms)
--Caught single step event!
--Finished handling event.
--Waiting for xen events...(500 ms)
--Caught single step event!
--Finished handling event.
```

**Comment by tklengyel** [comment]
Well, the problem line seems to be `Cannot clear unknown event: 0`. I believe it's because the step_and_reg_events function calls vmi_clear_event without specifying the free function and instead just goes ahead and frees the event itsef. However, in a callback it is not safe to discard the structure right after a call to vmi_clear_event. I'll submit a PR for, please give it a try and let me know if it solved this issue.

**Comment by ryan-johnson2** [comment]
I tried it out and it did indeed solve the issue, works as it should now. Thank you.
