### ISSUE TITLE
id in virDomainLookupByID must be zero or greater

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#391]
Hi !
I'm trying to use libvmi on top of `KVM`.

I created a Windows XP VM with virt-manager and started it.
I compiled libvmi (master) with the following parameters :
`./configure --disable-xen`

I created a libvmi configuration file in `/etc/libvmi.conf` with the following content :
~~~
winxp {
    ostype      = "Windows";
    win_tasks   = 0x88;
    win_pdbase  = 0x18;
    win_pid     = 0x84;
}
~~~

And i tried to use the `process-list` script in the examples which resulted in this output :
~~~
./process-list winxp
libvirt: Domain Config error : id in virDomainLookupByID must be zero or greater
Failed to init LibVMI library.
~~~

Did i misconfigured something ?
The KVM part of libvmi is usable on master ?

Thanks !

**Comment by Wenzel** [comment]
I followed the instructions to get more debugging output.
Therefore i defined the constant `VMI_DEBUG` to `__VMI_DEBUG_ALL` in `libvmi/debug.c` and recompiled the project.

This is the output that i have now :
~~~
LibVMI Version 0.11.0
--found KVM
LibVMI Mode 4
--completed driver init.
--got id from name (winxp --> 4294967295)
**set image_type = winxp
libvirt: Domain Config error : id in virDomainLookupByID must be zero or greater
--failed to find kvm domain
Failed to init LibVMI library.
~~~

Then i followed the bug in `libvmi/driver/kvm.c:kvm_get_id_from_name` using gdb.
~~~
    conn = virConnectOpenAuth("qemu:///system", virConnectAuthPtrDefault,
                           0);
    if (NULL == conn) {
        dbprint(VMI_DEBUG_KVM, "--no connection to kvm hypervisor\n");
        return -1;
    }

    dom = virDomainLookupByName(conn, name);
    if (NULL == dom) {
        dbprint(VMI_DEBUG_KVM, "--failed to find kvm domain\n");
        return -1;
    }

--> domainid = (uint64_t) virDomainGetID(dom);

    if (dom)
        virDomainFree(dom);
    if (conn)
        virConnectClose(conn);
~~~
And i noticed that the domain is found successfully, because the function `virDomainLookupByName` returns a valid domain, but the call to `virDomainGetID` returns an invalid id : `4294967295`.

Any ideas ?

**Comment by Wenzel** [comment]
So the bug really comes from `libvirt`...
I can reproduce it every time with the following test code and i will report it to libvirt bug tracker.
~~~
#include <stdlib.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>
#include <libvirt/libvirt.h>
#include <libvirt/virterror.h>

int main(int argc, char* argv[])
{
    virConnectPtr conn = 0;
    virDomainPtr dom = 0;
    uint64_t domainid = 0;

    conn = virConnectOpenAuth("qemu:///system", virConnectAuthPtrDefault, 0);
    if (conn == NULL) {
        fprintf(stderr, "Failed to open connection to qemu:///system\n");
        return 1;
    }
    dom = virDomainLookupByName(conn, "winxp");
    if (dom == NULL) {
        fprintf(stderr, "Failed to lookup domain by name");
        return 1;
    }
    domainid = virDomainGetID(dom);
    fprintf(stderr, "domainid: %" PRId64 "\n", domainid);
    virConnectClose(conn);
    return 0;
}
~~~

Thanks.

**Comment by bdpayne** [comment]
Nice find, thanks.  Should we close this bug on this end?

**Comment by Wenzel** [comment]
Hi !
I just found that `virDomainGetID` returns `-1` if there was an error or if the domain is not running.
In my case, the domain was not running :)

We can close this bug, sorry for the report :D

**Comment by smaresca** [comment]
Even so, we can be more graceful about handling virDomainGetID by checking for that special-case value of (unsigned int)-1.

I'll submit a PR. Thanks for the follow-up @Wenzel
