### ISSUE TITLE
port pyvmi to Python3

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#398]
Hi !
This is a feature request.

I would like to use `pyvmi` in Python3.
Is there any plan to port it ?

Also, I saw this PR [Complete rewrite of python wrapper for LibVMI](https://github.com/libvmi/libvmi/pull/161) from May 2014.

So what is the status of `pyvmi` ?
Can i try to port it to Python 3, or should i wait for a big refactoring ?

Thanks !

**Comment by smaresca** [comment]
Hi there, I've recently (in the last week or two) picked up the PR you
referenced to finish the work required. Python3 will be supported as an
outcome.

If you'd like to follow along, I can push the branch to a public place?

Steve

**Comment by Wenzel** [comment]
Hi !

Please do, i would like to try it !

Here is [my attempt](https://github.com/Wenzel/libvmi/tree/pyvmi_python3) to port `pyvmi.c` to Python3.
As I'm not familiar with Python extension C code, it segfault when i try to call `pyvmi.init()`.

**Comment by Wenzel** [comment]
Hi !
Any update about the port to Python 3 ?
Did you pushed the code somewhere ?

Thanks !

**Comment by noxdafox** [comment]
Hello, any update on this track?

If you could publish the branch maybe someone could help?

**Comment by smaresca** [comment]
For those watching this issue regarding Python3 support: I am planning to rebase and update in the next day. We do not have testing of python integrated with Jenkins yet, but that is also on my list to ensure that it stays stable and regression free.

**Comment by Wenzel** [comment]
Hi @smaresca ,
did you had a chance to rebase your work on the current libvmi ?
I'm able to test some functions of pyvmi python 3 and report the bugs if that helps you.

**Comment by Wenzel** [comment]
Hi @smaresca !
Any update regarding this ?
I'm really eager to test it !

Thanks.

**Comment by Wenzel** [comment]
Hi @smaresca,

still watching this issue because it will be very useful for the `kvm-vmi` project.
do you have any updates ?

Thanks.

**Comment by Wenzel** [comment]
Hi Steve,

Any updates about this issue ?

Thanks.

**Comment by Wenzel** [comment]
Hi,

i wrote a `CFFI` wrapper for `LibVMI`, to be used with Python3.
It only wraps the functions i need for Nitro, but i could be extended to support the entire LibVMI API.

https://github.com/KVM-VMI/nitro/pull/32/files

Are you interested in getting it along with `pyvmi` ?
cc @tklengyel

**Comment by smaresca** [comment]
@Wenzel yes, please

finding time on my end has been very difficult, unfortunately, and I'm
sorry for that

**Comment by Wenzel** [comment]
Hourray, we have the Python3 bindings now !
https://github.com/libvmi/libvmi/pull/532
