### ISSUE TITLE
Do not use -Werror in the default CFLAGS

### ISSUE THREAD

**Issue by TheJJ** [libvmi/libvmi#402]
Newer compilers can suddenly emit warnings about things that are not fixed in the upstream repo yet, but the build will fail.

Please remove the flag as most distribution will patch it out anyway in order to perform a working build.

(my current warning:

```
driver/kvm/kvm.c: In function ‘kvm_put_memory’:
driver/kvm/kvm.c:1216:9: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
         write(kvm_get_instance(vmi)->socket_fd, buf, length);
         ^
driver/kvm/kvm.c:1217:9: error: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Werror=unused-result]
         read(kvm_get_instance(vmi)->socket_fd, &status, 1);
         ^
driver/kvm/kvm.c: In function ‘destroy_domain_socket’:
driver/kvm/kvm.c:318:9: error: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Werror=unused-result]
         write(kvm->socket_fd, &req, sizeof(struct request));
         ^
cc1: all warnings being treated as errors
```

)

**Comment by tklengyel** [comment]
Thanks, there is already a PR open that fixes it (PR #387).

**Comment by TheJJ** [comment]
Thanks, but this still doesn't actually fix my issue. See here:

**Comment by tklengyel** [comment]
Did you actually try out the fix in the PR?

**Comment by TheJJ** [comment]
Yes, the build will pass then, but I was trying to avoid future errors by trying to inform you that `-Werror` is bad.

**Comment by tklengyel** [comment]
We are compiling with -Werror for exactly that reason and not by accident. It enforces a stricter quality on new code being introduced and helps spotting errors in the PR gate by failing to compile right away. This error in KVM has just been on a path the PR gates were not actually testing.

**Comment by TheJJ** [comment]
Your CI or test workflow can very well use it for a good reason, but for distros it is just another patch to apply (like me, for gentoo) to ensure the package doesn't break (i. e. `new warnings on version bumps of GCC/GLIBC the developer was not aware of at the point of coding `, `random breakage depending on what distro/architecture/library version/kernel/userland the developer was testing "-Werror" on`).
Thus I recommend having a proper CI check for warnings and spot warnings when you compile it on your machine, or add an additional `-Werror`-mode. But I'll have to patch it out in the packaging script otherwise.

**Comment by tklengyel** [comment]
Fair enough. We can probably introduce an --enable-debug configure option to easily switch these flags on and off.

**Comment by TheJJ** [comment]
(`-Wall` and `-Wextra` and `-pedantic` is fine to keep, this motivates users to fix those :)

**Comment by tklengyel** [comment]
Failing the PR gate will also have that affect but right, the warning parts should be fine ;)
