### ISSUE TITLE
LibVMI overwriting VCPU data

### ISSUE THREAD

**Issue by mattshockl** [libvmi/libvmi#420]
It seems as LibVMI is overwriting step data in between calls to register_singlestep_event and clear_singlestep_event, causing errors when CHECK_VCPU_SINGLESTEP can't find the correct VCPU number.  I instrumented events.c to print the event->ss_event.vcpus value in register and clear and got the following output:

```
Syscall Reached: LSTAR=0xfffff800026d2640 RIP=0xfffff800026d28d3
register_singlestep_event vcpus: 1
clear_singlestep_event: 40708315
Syscall Reached: LSTAR=0xfffff800026d2640 RIP=0xfffff800026d28db
register_singlestep_event vcpus: 1
clear_singlestep_event: 40708322
Syscall Reached: LSTAR=0xfffff800026d2640 RIP=0xfffff800026d28e2
```

You can see that the value is getting overwritten (or something?) in between those calls.  The code I used to run this is:

```
event_response_t reset_event_callback(vmi_instance_t vmi, vmi_event_t *event) {
    event->version = VMI_EVENTS_VERSION;
    vmi_register_event(vmi, event);

    return VMI_EVENT_RESPONSE_NONE;
}

event_response_t syscall_event_callback(vmi_instance_t vmi, vmi_event_t *event) {
    fprintf(stderr, "Syscall Reached: LSTAR=0x%lx RIP=0x%lx\n", lstar, event->x86_regs->rip);

    event->mem_event.generic = 0;
    event->mem_event.physical_address = event->mem_event.gfn << 12;
    vmi_clear_event(vmi, event, NULL);
    
    vmi_step_event(vmi, event, event->vcpu_id, 1, reset_event_callback);

    return VMI_EVENT_RESPONSE_NONE;
}
```

And the code I added to instrument is:
```
status_t register_singlestep_event(vmi_instance_t vmi, vmi_event_t *event) {
    ...
    fprintf(stderr, "register_singlestep_event vcpus: %u\n", event->ss_event.vcpus);
    ...
}

status_t clear_singlestep_event(vmi_instance_t vmi, vmi_event_t *event) {
    ...
    fprintf(stderr, "clear_singlestep_event vcpus: %u\n", event->ss_event.vcpus);
    ...
}
```

**Comment by tklengyel** [comment]
The event version and the vcpu id are currently in a union, so you would have to manually set the event version again before calling vmi_step_event while saving the vcpu_id to a local variable to be passed there. As it is a bit counter-intuitive this is being reworked in PR #419.

**Comment by mattshockl** [comment]
@tklengyel Even with that, I'm still reaching the same bug as before with event->ss_event.vcpus getting overwritten with some data in between calls to register_event and clean_event, thus making CHECK_VCPU_SINGLESTEP always fail after like the second callback to the same event.  If you use 1 VCPU and comment out the CHECK_VCPU_SINGLESTEP altogether within clear_singlestep_event, it works as intended.
