### ISSUE TITLE
Wrong symbol address for PsActiveProcessHead

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#436]
Hi !

On Windows systems, `PsActiveProcessHead` should point to a doubly linked list of EProcess objects.
[As an image is better than thousand words](http://image.slidesharecdn.com/ananalysisandsolutionfortheproblemofhiddenorphanprocessesonwindowsntplatforms-12747612068296-phpapp01/95/an-analysis-and-solution-for-the-problem-of-hidden-orphan-processes-on-windows-nt-platforms-5-728.jpg?cb=1274750019)

I tried to use the API `read_addr_ksym` in `pyvmi` to get the address of `PsActiveProcessHead` on a Windows 7 VM, and the value that it returned was a pointer to the first `EPROCESS` (which is `system`).
Therefore it was the value of the Flink field of `PsActiveProcessHead`, and not the address of this list, as i expected it to be.

I tried to ask `Rekall` to display the address of this symbol from a ram dump, and it was different.

Please see the following scripts to reproduce this behaviour :
Using `Rekall` to extract the symbol  (with a ram dump as command line argument):
~~~Python
#!/usr/bin/env python2

import os
import sys
import logging
from rekall import session
from rekall import plugins

def get_symbol_addr(session, symbol):
    return session.address_resolver.get_constant_object(symbol,
            "unsigned int").obj_offset


def main(ram_dump):
    s = session.Session(
            filename=ram_dump,
            autodetect=["rsds"],
            logger=logging.getLogger(),
            cache_dir='{}/rekall_cache'.format(os.getcwd()),
            autodetect_build_local='basic',
            format='data',
            profile_path=[
                "http://profiles.rekall-forensic.com"   
            ])




    # get PsActiveProcessHead address
    pshead_addr = get_symbol_addr(s, 'nt!PsActiveProcessHead')
    print('PsActiveProcessHead: {}'.format(hex(pshead_addr)))

if __name__ == '__main__':
    main(sys.argv[1])
~~~

Using `libvmi` to extract the symbol (with a vm name as command line argument) :
~~~Python
#!/usr/bin/env python2

import os
import sys
import pyvmi

def main(vm_name):
    vmi = pyvmi.init(vm_name, 'complete')
    
    # get PsActiveProcessHead address
    pshead_addr = vmi.read_addr_ksym('PsActiveProcessHead')
    print('PsActiveProcessHead: {}'.format(hex(pshead_addr)))

if __name__ == '__main__':
    main(sys.argv[1])

~~~

Thanks !

**Comment by tklengyel** [comment]
Not sure why the discrepancy. Are you using the Rekall profile method to introspect the VM?

**Comment by smaresca** [comment]
Mathieu,

If you want the address of PsActiveProcessHead, just use vmi
translate_ksym2v().  Using read_addr_ksym will find the address and
dereference, which I believe is why you're seeing the address of the
EPROCESS.

Regards,
Steve

**Comment by Wenzel** [comment]
Hi Steve,
I missed that API !
Indeed, `read_addr_ksym` was reading the content at the address of the given symbol.
Using `translate_ksym2v` gave the right address.

Thanks !
