### ISSUE TITLE
Issues reading the data from a virtual address

### ISSUE THREAD

**Issue by harpreetsc1992** [libvmi/libvmi#451]
Hey,
I am trying to read data at a virtual address inside a process's address space. I can do so for kernel memory addresses, but I cannot do it for user space.
I have tried the following LibVMI APIs: 
vmi_read_va
vmi_translate_uv2p followed by vmi_read_pa (similar to the way I did for kernel virtual addresses)
vmi_translate_sym2v (It says Linux is unimplemented at this time - but I still gave it an optimistic shot)

All of these attempts return garbage as values while trying to read from the virtual address I specify.
The map_addr.c and map_symbol.c files don't seem to work either.

I need some advice on what would be the right way to read data from a user virtual address, just like we can do so from a kernel virtual address using a combination of vmi_translate_kv2p followed by vmi_read_pa.

Thanks

Harpreet

**Comment by tklengyel** [comment]
Well, then it's very likely that the virtual address you are trying to read isn't actually mapped into the process. You can verify by using `vmi_pagetable_lookup_extended` and then looking at the page_info_t struct to see how far is the mapping is the tables.

**Comment by harpreetsc1992** [comment]
Figured it out. Thanks.
The code that am running is forking another process. 
I made a mistake of putting the pid of the parent process, while I should have been looking at the child process. Thus my objects just weren't in the address space I was looking into.
Once I got that figured out, read_va worked perfectly.

Thanks for the prompt reply. Appreciate it.:-)
