### ISSUE TITLE
events do not clear

### ISSUE THREAD

**Issue by robert-yates** [libvmi/libvmi#458]
I've noticed that events wont clear and just to check it wasnt something weird in my messy
test code i have modified the singlestep-event-example.c file

`if (vmi_clear_event(vmi, event, NULL) != VMI_SUCCESS)
    printf("Clear error\n");`

I added the following code into the single_step_callback function above the return 0;
statement.

I do not get any clear error msg and the example continues to produce singlestep output

im running ubuntu 16.04.2 LTS 64bit and using windows7-sp1 32bit as my target.

i have tried switching the "event" to "&single_step_event" but there is no difference,
what am i doing wrong or how can i debug this further?

cheers,
Rob.

**Comment by robert-yates** [comment]
i can confirm my example clear event is working when i boot my host into windows and use my vmware setup, however the guest OS is windows7 64bit in that case

**Comment by tklengyel** [comment]
The problem was with issuing `vmi_clear_event` in an event callback. PR #459 fixes the problem.

**Comment by robert-yates** [comment]
ah i see, thanks for the quick turn around, much appreciated !

/Rob.
