### ISSUE TITLE
Possible inconsistent memory access using libvmi cache

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#464]
Hi,

I'm using `libvmi` to decode `syscall` parameters while intercepting them in `KVM`.

For example, `NtOpenKey`, on Windows :
[NtOpenKey on MSDN](https://msdn.microsoft.com/en-us/library/windows/hardware/ff567014(v=vs.85).aspx)
~~~C
NTSTATUS ZwOpenKey(
  _Out_ PHANDLE            KeyHandle,
  _In_  ACCESS_MASK        DesiredAccess,
  _In_  POBJECT_ATTRIBUTES ObjectAttributes
);
~~~

I'm decoding the `ObjectAttributes` paramters, since it contains interesting value :
[OBJECT_ATTRIBUTES on MSDN](https://msdn.microsoft.com/en-us/library/windows/hardware/ff557749(v=vs.85).aspx)
~~~C
typedef struct _OBJECT_ATTRIBUTES {
  ULONG           Length;
  HANDLE          RootDirectory;
  PUNICODE_STRING ObjectName;
  ULONG           Attributes;
  PVOID           SecurityDescriptor;
  PVOID           SecurityQualityOfService;
}  OBJECT_ATTRIBUTES, *POBJECT_ATTRIBUTES;
~~~

I'm using the `vmi_read_va` function to read each field value.

**However, i noticed that sometimes the memory content returned is inconsistent and makes no sense.**

if you take a look at `NtDef.h`, where this structure is declared, there is a macro which initializes this field :

~~~C
#define InitializeObjectAttributes(p,n,a,r,s) { \
  (p)->Length = sizeof(OBJECT_ATTRIBUTES); \
  (p)->RootDirectory = (r); \
  (p)->Attributes = (a); \
  (p)->ObjectName = (n); \
  (p)->SecurityDescriptor = (s); \
  (p)->SecurityQualityOfService = NULL; \
}
~~~

Therefore, the `Length` field here is fixed and must be `0x30`.

So, most of the times, it works well :
~~~
Building ObjectAttributes from 0x188f1e0
Field Length, I, at 0x188f1e0 + 0x0
Value: 0x30
Field Handle, P, at 0x188f1e0 + 0x8
Value: 0x0
Field PUnicodeString, P, at 0x188f1e0 + 0x10
Value: 0x188f1c0
Building UnicodeString from 0x188f1c0
Field Length, H, at 0x188f1c0 + 0x0
Value: 0x62
Field MaximumLength, H, at 0x188f1c0 + 0x2
Value: 0x64
Field Buffer, P, at 0x188f1c0 + 0x8
Value: 0x3767f50
decoded \??\Volume{862f2ea7-0601-11e7-95ed-806e6f6e6963}\
~~~

And sometimes, the content is just corrupted :
~~~
Building ObjectAttributes from 0x1a9eda0
Field Length, I, at 0x1a9eda0 + 0x0
Value: 0x298120
Field Handle, P, at 0x1a9eda0 + 0x8
Value: 0x2f21a0
Field PUnicodeString, P, at 0x1a9eda0 + 0x10
Value: 0x0
Error while processing hook
~~~

Futhermore, i tried to disable libvmi paging :
`./configure --disable-address-cache --disable-page-cache`

And now the memory access is consistent !
But it's painfully slow :)

-> Do you have any idea of what could be the cause of this issue ?
-> Do you have similar bug reports and suspicious misbehavior involving the caching of libvmi ?
-> Any directions of how should i investigate this bug ?

Thanks !

**Comment by Wenzel** [comment]
I tried to flush the `libvmi` cache before processing a syscall and reading the memory.
I flushed every cache allowed by the API
- `v2pcache`
- `symcache`
- `rvacache`
- `pidcache`

But i still get these inconsistent memory issues.

**Comment by tklengyel** [comment]
I'm closing this issue for now as the solution to this is probably going to be resolved by using some of the new KVM introspection APIs currently being developed.
