### ISSUE TITLE
error: failed to init LibVMI Library

### ISSUE THREAD

**Issue by SunitaNICK** [libvmi/libvmi#468]
how to solve this error.

![screenshot from 2017-04-05 17-01-02](https://cloud.githubusercontent.com/assets/26893102/24703620/8f896062-1a21-11e7-9d77-55e83aab7ec6.png)

**Comment by tklengyel** [comment]
Well, you don't have the config file for LibVMI setup properly. Try adding the required entry for the VM.

**Comment by Wenzel** [comment]
Try enabling the libvmi debug output:
uncomment the `#define` macro in `libvmi/debug.h`

**Comment by tklengyel** [comment]
I'm closing this issue, feel free to reopen if you still have this problem.
