### ISSUE TITLE
xen-emulate-response example freezes VM

### ISSUE THREAD

**Issue by carter-yagemann** [libvmi/libvmi#474]
If you compile the `xen-emulate-response.c` example and pass it an address like the one `lstar` points to, it'll handle the event fine the first couple of times, but within a few seconds the VM freezes and the example code stops receiving events.

I'm using Xen 4.8.

**Comment by tklengyel** [comment]
The emulator in Xen is known to be incomplete. It is not guaranteed to handle all instructions correctly (or at all). Proceed with caution.

**Comment by carter-yagemann** [comment]
That makes a lot of sense. Thanks :+1:

**Comment by carter-yagemann** [comment]
@tklengyel This is a quick orthogonal question: does `vmi_set_vcpureg` support changing `RIP`? It seems to work most of the time in one of my programs, but occasionally I get a segfault in malloc somewhere in `memory.c` or lower. I can open an issue with a stack trace if you want.

**Comment by tklengyel** [comment]
It does, but if you use that instead of `VMI_EVENT_RESPONSE_SET_REGISTERS` you should pause the whole VM before calling that function.
