### ISSUE TITLE
How to generate the excute file like vmi-process-list single

### ISSUE THREAD

**Issue by Badangel** [libvmi/libvmi#479]
I want to modify the process-list.c, but I don't know how to generate the executable file like vmi-process-list. If I have installed the libvmi already. How should I write the makefile to create the executable file. 

Should I use automake to creat configure and makefile?

**Comment by tklengyel** [comment]
For autotools related problems please post on the relevant mailinglist (ie. https://lists.gnu.org/mailman/listinfo) or some other general support forum.
