### ISSUE TITLE
make: *** [qemu.1] Error 255

### ISSUE THREAD

**Issue by vikaschoudhary83** [libvmi/libvmi#482]
after copying patch file to qemu folder when i am tryting to compile after ./configure using make it giving an error 

GEN   qemu.1
qemu.pod around line 95: Non-ASCII character seen before =encoding in 'Sch�tz.'. Assuming UTF-8
POD document had syntax errors at /usr/bin/pod2man line 71.
Makefile:304: recipe for target 'qemu.1' failed
make: *** [qemu.1] Error 255
make: *** Deleting file 'qemu.1'

help me please to remove this error

**Comment by aghamir** [comment]
Did you try it like that?
```
cd /path/to/qemu/folder
patch -p1 < /path/to/patch/file
```

**Comment by vikaschoudhary83** [comment]
yes i tried like this but still same error
