### ISSUE TITLE
after applying qemu patch make command giving an error

### ISSUE THREAD

**Issue by vikaschoudhary83** [libvmi/libvmi#485]
![screenshot from 2017-06-02 00-22-59](https://cloud.githubusercontent.com/assets/24871672/26667945/29378a2a-46c5-11e7-9b2f-d6c7db44313b.png)
 how i can resolve it ?

**Comment by tklengyel** [comment]
Please give the latest QEMU patch a shot. I'm closing this issue for now but feel free to reopen if you have problems with that patch.
