### ISSUE TITLE
If the event-example can catch all syscall in XEN ubuntu16.04

### ISSUE THREAD

**Issue by Badangel** [libvmi/libvmi#494]
I use event-example to see one process, we know most syscall num between 0 to 1500. In ubuntu16.04 all of syscall is in fast sytem call. I use strace to see the process in the VM. compare with the result of event-example processname, the strace found more syscall than using event-example.
if the event-example only can find the syscall, when the CR3 changed that mean the process in CPU change. But when one process call consecutively system calls, the event-example only can find the first one system call.
Is that right or I have something wrong?

**Comment by tklengyel** [comment]
The event example is just that, an example. It's only purpose is to demonstrate the use of the event API. It does not guarantee complete syscall tracing.
