### ISSUE TITLE
LibVMI fails to initialize via rekall profile for Windows 10 x64 guest after system update

### ISSUE THREAD

**Issue by ReallyNothing** [libvmi/libvmi#496]
Hello,

I am trying to use `libvmi` to determine, whether the specific process is running on `Windows 10 x64` guest with `QEMU` under `KVM`. I have applied the patch for `QEMU`, built `libvmi` and created the applicaton, that uses `libvmi` for my task.

Everything worked fine, until Windows guest has updated. I have updated rekall profile using new `.pdb`-file. Now `libvmi` is unable to initialize via rekall profile.

I tried to debug it and found out, that failure happens in function `init_from_rekall_profile()` from `libvmi/os/windows/core.c`.
It tries to look for `KiInitialPCR` symbol in rekall profile, but there is no such symbol after system update, so the following call:
```
rekall_profile_symbol_to_rva(windows->rekall_profile, "KiInitialPCR", NULL, &kpcr_rva)
```
returns `VMI_FAILURE` and initialization fails.

My guest OS is `Windows 10 Enterprise x64`, `Version: 1703`, `OS Build: 15063.413`. The problem does not appear with the earlier versions of guest.
I have also attached [rekall profile](https://github.com/libvmi/libvmi/files/1130758/ntkrnlmp.pdb_a0011f02ee8442749e83e5180d8b19a61.json.txt).

Thanks.

**Comment by tklengyel** [comment]
Indeed, that PDB is missing `KiInitialPCR`. This is the first PDB since Windows 7 that I see it missing from. Hopefully this is not a trend and this PDB is just an outlier. If it is not, then we can still work around it similar to how we do it for Linux ASLR.

**Comment by ReallyNothing** [comment]
Thank you for your response.

If I unerstood correctly, I need to search for `ntoskrnl` in memory using some heuristics.
I tried to search for PE header backwards, starting from virtual address, stored in `GS_BASE` register, but had no success in that way.

Competent people told me to use [Interrupt Descriptor Table](http://wiki.osdev.org/Interrupt_Descriptor_Table) to find a virtual address of some interrupt handler. Having a virtual address of interrupt service routine from `ntoskrnl.exe`, we can search backwards for PE-header, starting from this address. When PE-header is found, it will be likely a virtual address of `ntoskrnl`.

What do you think about this? Is this method reliable?

**Comment by tklengyel** [comment]
That would work, yes.

**Comment by tklengyel** [comment]
An even better use of the IDT would be if we know what handler is registered at say the first position in the table, then we can just look up the RVA in the rekall profile and get to the ntoskrnl base from there.

**Comment by tklengyel** [comment]
So a quick search reveals that for int0 Windows assigns `KiDivideErrorFault`, which is present in your Rekall profile. So in case the KPCR route is not available due to the RVA not being defined the IDT route is still perfectly viable.

**Comment by tklengyel** [comment]
@ReallyNothing Could you give that PR a shot and see if it works for you?

**Comment by ReallyNothing** [comment]
Thank you for quick response.
I will check it shortly.

**Comment by ReallyNothing** [comment]
I have checked, it worked good for me.
I have also implemented another method of `ntoskrnl_va` initialization, based on searching for PE-header in memory. It is more slowly, but does not depend on any symbol in rekall profile. It can be used as the last way, if others are failed.
I have attached the patch.
[libvmi.find.ntoskrnl.via.idt.patch.txt](https://github.com/libvmi/libvmi/files/1177585/libvmi.find.ntoskrnl.via.idt.patch.txt)

**Comment by tklengyel** [comment]
Feel free to open a PR for it!

**Comment by cuiyudaniuHT** [comment]
We tested this patch. It still circles at  `--MEMORY cache hit 0x201000`.

**Comment by tklengyel** [comment]
Please post a full debug log. I have the impression the issue you are talking about is unrelated to what is being addressed here.
