### ISSUE TITLE
Can anyone give me a clue about the version problem

### ISSUE THREAD

**Issue by PinchenCui** [libvmi/libvmi#498]
Hello,

I have tried several versions of QEMU/Libvirt/Ubuntu, but none of the combinations can work.

I'm really appreciate that if someone could tell me a feasible version combinations.

Thanks!

**Comment by tklengyel** [comment]
I think as long as you are using a version of QEMU that we have a patch for the rest shouldn't matter.

**Comment by tklengyel** [comment]
Let us know if you need more help and feel free to reopen this issue if you are stuck.
