### ISSUE TITLE
The newest master branch does not support qemu 2.9?

### ISSUE THREAD

**Issue by cuiyudaniuHT** [libvmi/libvmi#499]
I clone master of libvmi, running process-list, and found :

[root@localhost libvmi]# ./examples/.libs/vmi-process-list 
--found KVM
LibVMI Version 0.11.0
LibVMI Driver Mode 1
--completed driver init.
--got id from name (xp_sp3_1 --> 46)
**set image_type = xp_sp3_1
--libvirt version 3003000
--qmp: virsh -c qemu:///system qemu-monitor-command xp_sp3_1 '{"execute": "query-version"}'
--Checking QEMU version string...
--Fail: incompatibility between libvmi and QEMU request definition detected
Failed to init LibVMI library.

And  I found in codes :
1394     // qemu_version JSON string :                                               
1395     // {                                                                        
1396     //   "return": {                                                            
1397     //     "qemu": {                                                            
1398     //       "micro": 0,                                                        
1399     //       "minor": 8,                                                        
1400     //       "major": 2                                                                                                                                           
1401     //     },                                                                   
1402     //     "package": ""                                                        
1403     //   },                                                                     
1404     //   "id": "libvirt-42"                                                     
1405     // }

**Comment by Gakaza** [comment]
I have similar issue with qemu-system-x86_64 version 2.10 'cause I want to test the performance and other things without the qemu-kvm 2.8 patch. Did you fall back to version qemu version 2.8 to solve this or is there any other solution?

**Comment by tklengyel** [comment]
The latest QEMU we have a patch for is 2.8. If  you are running with QEMU 2.8 you should have applied the appropriate patch that adds a libvmi request header to QEMU. Looks like LibVMI couldn't find that header to me says you didn't patch/install QEMU correctly.

**Comment by Gakaza** [comment]
@tklengyel thanks man for the info. I was originally just going for a performance test between unpatch vs patched version.
