### ISSUE TITLE
kvm->socket_fd will not be released when kvm_destroy using 2.8 patch?

### ISSUE THREAD

**Issue by cuiyudaniuHT** [libvmi/libvmi#503]
kvm->socket_fd will not be released when kvm_destroy using 2.8 patch?

It may cause open files leaks and memory leaks.

I add codes below which seems working:

 39 static inline void                                                              
 40 driver_destroy(                                                                 
 41     vmi_instance_t vmi)                                                         
 42 {                                                                               
 43     if (vmi->driver.initialized && vmi->driver.destroy_ptr)                     
 44         vmi->driver.destroy_ptr(vmi);                                           
 45                                                                                 
 46     kvm_instance_t *kvm = (kvm_instance_t *) vmi->driver.driver_data;           
 47     close(kvm->socket_fd);                                                      
 48     free(kvm->ds_path);                                                         
 49     free(kvm->name);                                                            
 50     free(kvm);                                                                  
 51                                                                                 
 52     bzero(&vmi->driver, sizeof(driver_interface_t));                            
 53 }

**Comment by tklengyel** [comment]
There is indeed a `close(socket_fd);` missing, but the correct place to have that would be in `driver/kvm/kvm.c:destroy_domain_socket`. Would you mind opening a PR for that fix?

**Comment by cuiyudaniuHT** [comment]
I am a newer to this, so it is hard for me to repair it. But I will try.

**Comment by Wenzel** [comment]
I guess we can close this issue now that the PR has been merged in master ? @tklengyel
