### ISSUE TITLE
Guest VM get '**failed to determine KASLR offset' when memory is 4GB ?

### ISSUE THREAD

**Issue by cuiyudaniuHT** [libvmi/libvmi#504]
I tried 4GB memory for centos7 with qemu 2.8.1.1 patched.
It comes to be failed less then 3 seconds.
`
[root@controller-100x11 libvmi]# examples/.libs/vmi-process-list 
--found KVM
LibVMI Version 0.11.0
LibVMI Driver Mode 1

--completed driver init.
--got id from name (instance-00000097 --> 36)
**set image_type = instance-00000097
--libvirt version 3003000
--qmp: virsh -c qemu:///system qemu-monitor-command instance-00000097 '{"execute": "pmemaccess", "arguments": {"path": "/tmp/vmiij0uAP"}}'
--kvm: using custom patch for fast memory access
**set allocated_ram_size = 100000000, max_physical_address = 0x100000000
--qmp: virsh -c qemu:///system qemu-monitor-command instance-00000097 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
--qmp: virsh -c qemu:///system qemu-monitor-command instance-00000097 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
**set pae = 1
**set pse = 1
--qmp: virsh -c qemu:///system qemu-monitor-command instance-00000097 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
**set lme = 1
--qmp: virsh -c qemu:///system qemu-monitor-command instance-00000097 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
**IA-32e paging
**sanity checking cr3 = 0x0000000137759000
** Note cr3 value [0x137759000] exceeds max_physical_address [0x100000000]
**set os_type to Linux.
--qmp: virsh -c qemu:///system qemu-monitor-command instance-00000097 '{"execute": "human-monitor-command", "arguments": {"command-line": "info registers"}}'
--PTLookup: lookup vaddr = 0xffffffff81a0e500
--PTLookup: dtb = 0x0000000137759000
--MEMORY cache set 0x137759000
VMI_ERROR: --requesting PA [0x13775a000] beyond max physical address [0x100000000]
VMI_ERROR:      paddr: 137759000, length 1000, vmi->max_physical_address 100000000
VMI_ERROR: create_new_entry failed
--PTLookup: error reading pml4e_address = 0x0000000137759ff8
--PTLookup: paddr = 0x0000000000000000
--MEMORY cache set 0x137759000
VMI_ERROR: --requesting PA [0x13775a000] beyond max physical address [0x100000000]
VMI_ERROR:      paddr: 137759000, length 1000, vmi->max_physical_address 100000000
VMI_ERROR: create_new_entry failed
**failed to determine KASLR offset
Failed to init LibVMI library.
`

**Comment by tklengyel** [comment]
Well, that `cr3` value seems bogus. Not sure where it came from. Is this problem repeatable?

**Comment by cuiyudaniuHT** [comment]
For linux, it is repeatable, I will try a windows version.

**Comment by cuiyudaniuHT** [comment]
I closed the kaslr by 'echo 0 | sudo tee /proc/sys/kernel/randomize_va_space' in Guest OS, but this problem remains.
And I notice that, libvmi prints `** Note cr3 value [0x1abf9d000] exceeds max_physical_address [0x174300000]` , is this the reason?

**Comment by cuiyudaniuHT** [comment]
I run a c program in Guest to get CR3. It will be like `cr3 = 0x39a54000`, while libvmi get `**sanity checking cr3 = 0x0000000139a54000`  which seems to be that difference between these is a 4GB(0x100000000) gap. Is this a bug?

**Comment by cuiyudaniuHT** [comment]
These are sources used to get CR3 in Guest.

`/* hello.c */
#include <linux/module.h>
#include <linux/kernel.h>

int init_module(void)
{
#ifdef __x86_64__
    u64 cr0, cr2, cr3;
    __asm__ __volatile__ (
            "mov %%cr0, %%rax\n\t"
            "mov %%eax, %0\n\t"
            "mov %%cr2, %%rax\n\t"
            "mov %%eax, %1\n\t"
            "mov %%cr3, %%rax\n\t"
            "mov %%eax, %2\n\t"
            : "=m" (cr0), "=m" (cr2), "=m" (cr3)
            : /* no input */
            : "%rax"
            );
#elif defined(__i386__)
    u32 cr0, cr2, cr3;
    __asm__ __volatile__ (
            "mov %%cr0, %%eax\n\t"
            "mov %%eax, %0\n\t"
            "mov %%cr2, %%eax\n\t"
            "mov %%eax, %1\n\t"
            "mov %%cr3, %%eax\n\t"
            "mov %%eax, %2\n\t"
            : "=m" (cr0), "=m" (cr2), "=m" (cr3)
            : /* no input */
            : "%eax"
            );
#endif
    printk(KERN_INFO "cr0 = 0x%8.8X\n", cr0);
    printk(KERN_INFO "cr2 = 0x%8.8X\n", cr2);
    printk(KERN_INFO "cr3 = 0x%8.8X\n", cr3);
    return 0;
}

void cleanup_module(void)
{
}
`
`# Makefile

obj-m += hello.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

test: all
	insmod ./hello.ko
	rmmod hello
	dmesg | tail`

**Comment by tklengyel** [comment]
Getting a cr3 of 0x0000000139a54000 instead of 0x39a54000 does sound like a bug to me. Should try to find out why there is the extra bit set in LibVMI.. Is the variable not properly null-set and the upper 32bit just have a stale value? It looks to me that way but it may be something else.

**Comment by cuiyudaniuHT** [comment]
The CR3 value seems to be get from virsh command

**Comment by mark-i-m** [comment]
I think this is #493
