### ISSUE TITLE
Libvmi cannot enable debug and cannot init

### ISSUE THREAD

**Issue by PinchenCui** [libvmi/libvmi#505]
Hello,

I'm facing the problem that the libvmi cannot init library, then I'm trying to enable debug to see what is going on. 

Then it reports error during make (I have uncomment the #define symbol in libvmi/debug.h).

![image](https://user-images.githubusercontent.com/19175260/28227952-e9fe6dca-68a1-11e7-8222-f75ca4b928dc.png)

How can I solve this?

**Comment by tklengyel** [comment]
What version of LibVMI is this with? It should compile fine with the latest master and debug enabled.

**Comment by PinchenCui** [comment]
It is the latest master, however, it can report debug information now without the debug enabled. I don't know why and how.

I'm trying to introspect a Window 7 guest on a Ubuntu host. It reports something like:
--kvm: using custom patch for fast memory access
--connect() failed to /tmp/vmiVwLVge. No such a file or directory.
Failed to init LibVMI library.

I'm running the qemu-2.8.0 with patch and here is the libvirt XML file:
![image](https://user-images.githubusercontent.com/19175260/28228593-cbd9a9ec-68a4-11e7-8c6c-9d1f2df6da78.png)

**Comment by tklengyel** [comment]
Maybe #508 solves your issue

**Comment by tklengyel** [comment]
I'm closing this issue for now, feel free to reopen if you still experience problems.
