### ISSUE TITLE
How to write a win10 profile?

### ISSUE THREAD

**Issue by cuiyudaniuHT** [libvmi/libvmi#507]
First, I run :
`../../examples/vmi-dump-memory win10_x64 11.dd && ./getGUID 11.dd |./downloadPDB.py | ./dumpPDB.py -o debugSymbols.txt`
This print no kernel found.
Then I run `../../examples/vmi-win-guid name win10_x64`, it print:
`Windows Kernel found @ 0x4886000
        Version: 64-bit Windows 10
        PE GUID: 559f3c1a852000
        PDB GUID: c68ee22fdcf6477895c54a862be165671
        Kernel filename: ntkrnlmp.pdb
        Multi-processor without PAE
        Signature: 17744.
        Machine: 34404.
        # of sections: 22.
        # of symbols: 0.
        Timestamp: 1436498970.
        Characteristics: 34.
        Optional header size: 240.
        Optional header type: 0x20b
        Section 1: .text
        Section 2: INITKDBG
        Section 3: POOLCODE
        Section 4: .rdata
        Section 5: .data
        Section 6: .pdata
        Section 7: ALMOSTRO
        Section 8: CACHEALI
        Section 9: PAGELK
        Section 10: PAGE
        Section 11: PAGEKD
        Section 12: PAGEVRFY
        Section 13: PAGEHDLS
        Section 14: PAGEBGFX
        Section 15: PAGEVRFB
        Section 16: .edata
        Section 17: PAGEDATA
        Section 18: PAGEVRFD
        Section 19: INITDATA
        Section 20: INIT
        Section 21: .rsrc
        Section 22: .reloc`

SO, how do I write a win 10 profile for libvmi ?

**Comment by tklengyel** [comment]
Just in case someone is wondering about the same question in the future, you use Rekall to download the PDB and to create the profile.
