### ISSUE TITLE
process-list for win10 64bit FAIL!!!

### ISSUE THREAD

**Issue by cuiyudaniuHT** [libvmi/libvmi#509]
I tested the process-list for a win10 x64 Guest.
The config is like `{ostype = \"Windows\";win_pdbase=0x28;win_pid=0x2e8;win_tasks=0x2f0;win_pname=0x448;}` (get from win-guid)

After started, the process-list with debug opened prints a lot of `--MEMORY cache set XXX` and comes to a end with

 `--Found KdDebuggerDataBlock at PA 0000000000000000
**All KdDebuggerDataBlock search methods failed
Failed to init LibVMI library.`. 
This seems that libvmi scaned all memory and found nothing?

The attachment of 1.txt is the whole debug output.
[1.txt](https://github.com/libvmi/libvmi/files/1165002/1.txt)
And `
--MEMORY cache hit 0x300000` prints a lot, more than 10% of total lines in 1.txt (I omited it).

**Comment by tklengyel** [comment]
There is no need for multiple exclamation points.

Windows  will only work if you are using a Rekall profile.
