### ISSUE TITLE
Input validation for public API

### ISSUE THREAD

**Issue by smaresca** [libvmi/libvmi#521]
Any pointers passed to public API functions which are NULL should be rejected and an error state indicated.

Various function families do not validate inputs before operating upon them, presenting risk of NULL pointer dereference

**Comment by mdolmen** [comment]
Hi! I am willing to work on this. I will start probably this week. 

Here are the files for which I noticed changes are required : 
- `accessors.c`
- `cache.c`
- `convenience.c`
- `core.c`
- `events.c`
- `pretty_print.c`
- `read.c`
- `write.c`

Let me know if I missed something.
