### ISSUE TITLE
How to get VCPUs andTraps data from VM using libvmi?

### ISSUE THREAD

**Issue by NeerajNegi** [libvmi/libvmi#524]
I want to get VPCUs data and trapping of hardware data for learning purpose. Please suggest how to do so.

**Comment by tklengyel** [comment]
Take a look at the examples in the examples folder, you will find many useful hints in there.

**Comment by NeerajNegi** [comment]
Most of the commands are not working on my system.
only process-list, win-guid and module-list are working.
