### ISSUE TITLE
size of init_flags in vmi_init ?

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#531]
Hi,

i just noticed that we have 2 different declarations of the `init_flags`:
*vmi_init*: https://github.com/libvmi/libvmi/blob/master/libvmi/core.c#L492
~~~C
status_t vmi_init(
    vmi_instance_t *vmi,
    vmi_mode_t mode,
    void* domain,
    uint32_t init_flags,
    void *init_data,
    vmi_init_error_t *error)
~~~

*vmi_init_complete*: https://github.com/libvmi/libvmi/blob/master/libvmi/core.c#L731
~~~C
status_t
vmi_init_complete(
    vmi_instance_t *vmi,
    void *domain,
    uint64_t init_flags,
    void *init_data,
    vmi_config_t config_mode,
    void *config,
    vmi_init_error_t *error)
~~~

Is it a mistake ?

**Comment by tklengyel** [comment]
Yes, it is.

**Comment by Wenzel** [comment]
PR has been merged, thanks @tklengyel !
