### ISSUE TITLE
on-the-fly offsets detection for automatic configuration

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#536]
At the moment LibVMI needs either a configuration file, a config string or a hash table to introspect a VM.

This is tedius because it requires from the user to search for these offsets, and hardcode them in a config file, (or in a script, in the case of `VMI_CONFIG_STRING` or `VMI_CONFIG_GHASHTABLE`).

Having used `Rekall` in my project, i was able to extract a lot of information, including the offsets just by analyzing a memory dump.

A look at the Rekall python API to get the offsets : https://github.com/KVM-VMI/nitro/blob/master/nitro/backends/windows/get_symbols.py#L63

Now i know this is Windows specific, i don't know if we could do this with Linux, but what about adding an `VMI_AUTO_CONFIG` option, which would take a temporary memory dump, and extract the offsets using `Rekall` ?

By removing this per/VM configuration step, this will greatly improve how accessible LibVMI is for a new user, and it would bring more people to the project.

What do you think ?

**Comment by tklengyel** [comment]
Since as you say this would only be applicable to Windows I would suggest a different naming for it. For Linux Rekall needs very similar steps then what we have with the offset finding kernel module in LibVMI. Ultimately I think the simplest way to use LibVMI is to generate a Rekall profile manually with Rekall, then just point LibVMI to that profile.

**Comment by Wenzel** [comment]
I wrote a blog article where i explain the procedure for this auto detection.
[Dynamic configuration of LibVMI using Rekall](https://wenzel.github.io/2017/11/23/dynamic_configuration_libvmi.html)

The example has been written on top of the libvmi python wrapper.

I think a this point, it could an interesting addition as a python module, from which you can import your methods to auto detect Windows, but not worth adding it into the core of LibVMI since it doesn't work with Linux.

**Comment by Wenzel** [comment]
PR has been merged.
closing this issue.
