### ISSUE TITLE
patch: **** Only garbage was found in the patch input for KVM patch

### ISSUE THREAD

**Issue by hagohel** [libvmi/libvmi#539]
Hello I am trying to install kvm patch but it shows above error.
Libvirt version is 1.3.1, libyajl.s0.2.1.0 ,Ubuntu 16.04.1 LTS and QEMU emulator version 2.5.0

I tried following showed at https://github.com/libvmi/libvmi/tree/master/tools/qemu-kvm-patch
$ tar zxvf qemu-kvm-0.14.0.tar.gz
$ cd qemu-kvm-0.14.0
$ patch -p1 < /home/user/kvm-physmem-access_0.14.0.patch

**Comment by tklengyel** [comment]
Well, trying to apply the 0.14.0 patch to version 2.5.0 is not going to work.

**Comment by hagohel** [comment]
Which patch shall I try for 2.5.0 version? 
Or shall I update the my emulator?

**Comment by hagohel** [comment]
Well, I've tried kvm-qemu-2.4.0.1-libvmi.patch and kvm-qemu-v2.8-libvmi.patch sequencially but there is a same error.

Please help me out.

**Comment by hagohel** [comment]
Please see my query. I've mentioned my configuration. Its 
Libvirt version is 1.3.1, 
libyajl.s0.2.1.0 ,
Ubuntu 16.04.1 LTS and 
**QEMU emulator version 2.5.0**

User@ubuntu-kvm:~$ patch p1 < /home/dodtech/kvm-qemu-2.4.0.1-libvmi.patch 
patch: **** Only garbage was found in the patch input.

User@ubuntu-kvm:~$ patch p1 < /home/dodtech/kvm-qemu-v2.8-libvmi.patch 
patch: **** Only garbage was found in the patch input.

**Comment by hagohel** [comment]
Hello 
Yes, I have a source code of qemu-2.5.0 as my QEMU emulator version 2.5.0. 
I am in user@ubuntu-kvm:~/qemu-2.5.0 directory and trying to patch kvm-qemu-v2.8-libvmi.
Please tell me if I am doing wrong and which qemu-kvm-patch would be applicable to use libvmi?

**Comment by tklengyel** [comment]
I'm repeating myself here, you can't apply the 2.8 version patch to QEMU 2.5.

2.5 != 2.8

**Comment by hagohel** [comment]
Thank you very much Tamas but my now question is which libvmi shall I use for it?
I don't have 2.5.0 kvm-qemu patch of libvmi.

**Comment by tklengyel** [comment]
You would need to use a QEMU version for which there is a patch. Otherwise you would need to port an existing patch to a different version of QEMU.

**Comment by hagohel** [comment]
Could you please enlighten on to port an existing patch on QEMU 2.5.0?

**Comment by hagohel** [comment]
Now see the issue is following after finalizing qemu-2.4.0.1
user@ubuntu-kvm/qemu-2.4.0.1$ patch < /home/dodtech/kvm-qemu-2.4.0.1-libvmi.patch
patch: **** Only garbage was found in the patch input.

Am I patching in wrong way?

**Comment by tklengyel** [comment]
Yes, you are. Please read https://github.com/libvmi/libvmi/blob/master/tools/qemu-kvm-patch/README carefully.

**Comment by hagohel** [comment]
Its done. Thank you very much Tamas.
