### ISSUE TITLE
getting the correct Thread ID of a Linux guest

### ISSUE THREAD

**Issue by dekel35** [libvmi/libvmi#542]
In linux the pid inside the task_struct *is* the thread id of a posix thread. 
To get the actual pid, it is usually enough to look at the tgid (thread-group id).
However, I could not find a way to get the task_struct for the running thread for a simple reason: all implementations use the dtd (pointed by CR3) to get to the task_struct. 
Unfortunately, the dtd is the same for all threads in a thread group, and the result is that the task_struct of the parent process is always returned, whether this is a thread or the parent process (not to be confused with real process where the parent process id and the process itself are easily distinguishable).
In the kernel itself the pointer to the correct task_struct is inside a per-cpu segmented memory. When I tried to introspect that address I got a failure in libvmi (as expected?)
My question: How can I read a per_cpu memory (pointed by the gs register)? 
alternatively: Is there a way to access the correct task_struct for a thread?

**Comment by tklengyel** [comment]
You might want to look through https://github.com/tklengyel/drakvuf/blob/master/src/libdrakvuf/linux-processes.c as a reference.

**Comment by dekel35** [comment]
Thanks, I tried that code and I had the same result: For both the main thread and it's siblings I am getting  the same pid. 
This is not surprising: All threads in a thread group have the same dtb (=CR3), so it's no wonder that they all eventually return what **getpid()** would return and not what **syscall(__NR_gettid)** would.
I tried both using *translate_mechanism = VMI_TM_PROCESS_PID* and *translate_mechanism = VMI_TM_PROCESS_DTB*

**Comment by mfusaro** [comment]
@dekel35 If I remember correctly, you can use the dtb of the PID you are looking for and then use the thread_group member of task_struct to traverse the threads. This is implemented as a list_head (much like the task list) and points to additional task_structs which will be in different memory spaces than your parent task_struct and will have access to the correct resources based on how the thread was created.
