### ISSUE TITLE
For generating Windows conf file ."./examples/dump-memory winxpsp2 winxp.dd"

### ISSUE THREAD

**Issue by Alex287** [libvmi/libvmi#545]
I have succeed in installing libvmi without any error. But when I want to generate windows libvmi.conf file, there is no dump-memory in my examples directory. 
Just find "dump-memory.c" and "dump-memory.o" in the abrove directory. I am new to linux, any help would be appreciated!
thanks!

**Comment by tklengyel** [comment]
Try `vmi-dump-memory`.
