### ISSUE TITLE
Rekall profile: no $STRUCTS section found

### ISSUE THREAD

**Issue by Alex287** [libvmi/libvmi#548]
![image](https://user-images.githubusercontent.com/26807502/34116160-b1ff55ec-e452-11e7-968f-05777ee99ae4.png)
You see! When I run 'vmi-process-list win8' with simple 'win_pid、win_tasks...'in the libvmi.conf file, everything goes fine. But when I use rekall, the error appears! Any help will be appreciated! Thanks in advance!

**Comment by smaresca** [comment]
@Alex287 please paste the entirety of the $METADATA section in the rekall profile

**Comment by Alex287** [comment]
"$METADATA": {
  "GUID_AGE": "-5", 
  "PDBFile": "ntkrpamp.pdb", 
  "ProfileClass": "Ntkrpamp", 
  "Timestamp": "2010-11-20 08:44:05Z", 
  "Type": "Profile", 
  "Version": 20000404, 
  "arch": "I386"
 },

**Comment by Alex287** [comment]
![image](https://user-images.githubusercontent.com/26807502/34117763-a28c6b22-e457-11e7-971c-1d4e32d55474.png)
@smaresca 
I cannot run 'vmi-win-guid win' correctly(It loops for a long long time for 'PEPARSE:DOS header signature not found' in debug mode). But since I have installed the same OS(win_7 32bit) with drakcuf's official install guidence. I just use its vmi-win-guid result and generate rakall json file successfully

**Comment by Alex287** [comment]
I use the following command to match ntkrpamp.pdb
 rekal –f /var/lib/libvirt/images/win8.img version_scan –name_regex ntkrpamp.pdb
and get the true address. I regenerate rekall json profile again both for win7_32bit and win8_32 bit. Error still appears as title. So I use gedit to open rekall json and execute 'find $STRUCTS' there is no result match!
I doubt that it is Microsoft 's problem because the ntkrpamp.pdb is downloading from it and recall_parse goes well. Is that true? @smaresca

**Comment by smaresca** [comment]
@Alex287 I agree, the Microsoft symbol server is supplying a full, normal PDB. I have downloaded the PDB for that GUID and verified it does contain full types.

However, the profile generated by your version of rekall is malformed. Please make sure you have an up to date rekall version and regenerate the profile.  LibVMI requires a well-formed and complete rekall profile.

The metadata section of a well-formed rekall profile generated from that PDB will show :
 "GUID_AGE": "684da42a30cc450f81c535b4d18944b12"
rather than 
 "GUID_AGE": "-5",
which is what your file contains.

**Comment by allanng78** [comment]
Hi Alex,
How do you build your image and where did you get the /var/lib/libvirt/images/win8.img file? I am facing similar problem as you.

**Comment by fwruck** [comment]
Hi,
i have the same issue, no $STRUCTS section is contained in the output of rekall parse_pdb.
The pdb I'm using is the file ntkrnlmp.pdb, PDB GUID: 9378084E8DBD4AB1A155099BCE693E341
I'm using Debian stretch.

I did the following tests:
 - Obtain the PDB GUID using vmi-win-guid
 - Obtain the PDB GUID using the symchk Microsoft tool
 - download the pdb-file from msdl.microsoft.com/download/symbols using wget
 - download the pdb-file using the symchk tool
- install the newest rekall-version from github using virtualenv (Version 1.7.3.dev7)
- Install the newest rekall version as described on drakvuf.com:
`
    sudo pip install setuptools
    python setup.py build
    sudo python setup.py install
`
In each combination of the approaches, the $STRUCTS section is missing.

The only way I got it to work was using the packaged version of rekall (python-rekall-core, pyton-rekall) coming with Debian stretch (1.6.0+dfsg-2).
(If you have local copies you have to make sure that **all** rekall-scripts are removed from /usr/local/...)

It seems the issue has arised between Versions 1.6.2 and 1.7.3.dev7

**Comment by tklengyel** [comment]
This is an issue that should be reported on the [Rekall github page](https://github.com/google/rekall)

**Comment by fwruck** [comment]
Yes, I opened a new issue on the rekall page google/rekall#355.
I think this issue can be closed.

**Comment by Wenzel** [comment]
@tklengyel can we close this issue ?
