### ISSUE TITLE
Failed to init LibVMI library

### ISSUE THREAD

**Issue by allanng78** [libvmi/libvmi#558]
hi,
I have try to extract the process list from xen guest with this command: sudo vmi-process-list ovm-1734

Here is the output:
**The running Xen version is 4.6
--found Xen
LibVMI Version 0.11.0
LibVMI Driver Mode 0
**The running Xen version is 4.6
--completed driver init.
--got id from name (ovm-1734 --> 3)
**set image_type = ovm-1734
**set vm_type HVM
--xen: setup live mode
**set allocated_ram_size = 10004b000, max_physical_address = 0x11004f000
**set pae = 1
**set pse = 1
**set lme = 0
**PAE paging
**sanity checking cr3 = 0x0000000000185000
--looking for config file at /etc/libvmi.conf
**Using config file at /etc/libvmi.conf
**set os_type to Windows.
Rekall profile: no $STRUCTS section found
Failed to init LibVMI library.

What happen? Help help

**Comment by tklengyel** [comment]
The Rekall profile you specified in the configuration file is not correct. As you have opened another issue stating you were not able to generate a Rekall profile I'm closing this issue.

**Comment by allanng78** [comment]
Hi tklengyel,
Thank for letting me know. Can you give me some suggestion how should I run it with rekall? Hope to hear from you soon. thank.
