### ISSUE TITLE
error in libvmi installation on Ubuntu 16.10 

### ISSUE THREAD

**Issue by hagohel** [libvmi/libvmi#563]
Hello I was trying to install libvmi on Ubuntu 16.10(yakkety) and getting following error

`**configure: error: No libvirt headers found. Install missing package or re-run with --disable-kvm**`
Furthermore, I have default libvirt 2.1.0 and tried to upgrade 2.4.0 and getting following compilation error.

```
**/usr/include/libxl_uuid.h:34:23: fatal error: uuid/uuid.h: No such file or directory
#include <uuid/uuid.h>
                  ^
compilation terminated.**
```
So I have tried to install uuid-dev which shows

```
**E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/u/util-linux/libuuid1_2.28.2-1ubuntu1.2_amd64.deb  404  Not Found
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/u/util-linux/uuid-dev_2.28.2-1ubuntu1.2_amd64.deb  404  Not Found 
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
At last, I am unable to update from ubuntu and getting following error.

E: The repository 'http://security.ubuntu.com/ubuntu yakkety-security Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.**
```

P.S. I have QEMU emulator version 2.8.0

Please help if anyone tried to install libvmi on Ubuntu 16.10..!

**Comment by smaresca** [comment]
@hagohel According to https://wiki.ubuntu.com/YakketyYak/ReleaseNotes , yakkety has been out of support since July 2017, and that error message from apt is somewhat expected. You should update your distribution or switch to the 'legacy' repository URLs here http://old-releases.ubuntu.com/releases/
