### ISSUE TITLE
Cannot pause a VM inside an event callback

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#569]
Hi !

I'm playing with Xen VMI events with Libvmi, and i'm façing an issue with the `vmi_pause_vm` function.

I'm listening on `single-step` events on a single VCPU, and in the callback i'm trying to pause the VM, and then exit.

However, it does not work. When my program exits, the VM is still running.
And `vmi_pause_vm` returns `VMI_SUCCESS`.

Here is my code:
~~~C
#include <stdlib.h>
#include <libvmi/libvmi.h>
#include <libvmi/events.h>

static bool interrupted = false;

event_response_t my_callback(vmi_instance_t vmi, vmi_event_t *event){
    status_t status;
    printf("%s\n", __func__);

    // pause vm again
    printf("Pausing VM\n");
    status = vmi_pause_vm(vmi);
    if (status == VMI_FAILURE)
    {
        printf("Fail to pause VM\n");
        exit(1);
    }

    // unregister
    status = vmi_clear_event(vmi, event, NULL);
    if (status == VMI_FAILURE)
    {
        printf("Fail to clear event\n");
        exit(1);
    }


    // stop monitoring
    interrupted = true;

    return 0;
}

int main()
{
    vmi_instance_t vmi_1;

    // init libvmi
    printf("Initializing LibVMI\n");
    vmi_init_error_t error;
    status_t status = vmi_init_complete(&vmi_1, "xenwin7", VMI_INIT_DOMAINNAME | VMI_INIT_EVENTS, NULL,
                                        VMI_CONFIG_GLOBAL_FILE_ENTRY, NULL, &error);
    if (status == VMI_FAILURE)
    {
        printf("vmi_init_complete: Failed to initialize LibVMI, error: %d\n", error);
        exit(1);
    }

    printf("Pausing VM\n");
    status = vmi_pause_vm(vmi_1);
    if (status == VMI_FAILURE)
    {
        printf("Fail to pause VM\n");
        exit(1);
    }

    vmi_event_t sstep_event = {0};
    sstep_event.version = VMI_EVENTS_VERSION;
    sstep_event.type = VMI_EVENT_SINGLESTEP;
    sstep_event.callback = my_callback;
    sstep_event.ss_event.enable = 1;
    SET_VCPU_SINGLESTEP(sstep_event.ss_event, 0);
    interrupted = false;

    vmi_register_event(vmi_1, &sstep_event);
    if (status == VMI_FAILURE)
    {
        printf("vmi event registration failure\n");
        vmi_resume_vm(vmi_1);
        return 0;
    }

    printf("Resuming VM\n");
    status = vmi_resume_vm(vmi_1);
    if (status == VMI_FAILURE)
    {
        printf("Fail to resume VM\n");
        exit(1);
    }
    printf("Listening on VMI events...\n");
    while (!interrupted)
    {
        status = vmi_events_listen(vmi_1, 500);
        if (status == VMI_FAILURE)
        {
            printf("listening on events failed\n");
            return 0;
        }
    }

    vmi_destroy(vmi_1);

    return 0;
}
~~~

Output:
~~~
Initializing LibVMI
libvirt: QEMU Driver error : Domain not found: no domain with matching name 'xenwin7'
LibVMI Suggestion: set win_ntoskrnl=0x280c000 in libvmi.conf for faster startup.
LibVMI Suggestion: set win_kdbg=0x1e9070 in libvmi.conf for faster startup.
LibVMI Suggestion: set win_kdvb=0xfffff800029f5070 in libvmi.conf for faster startup.
Pausing VM
Resuming VM
Listening on VMI events...
my_callback
Pausing VM
~~~

And yes, at the end, the VM is running :/

So is it an bug in libvmi/Xen events API ?
Or is it just not possible to pause a VM inside a callback ?

Thanks.

**Comment by tklengyel** [comment]
The problem you experience is related to how `vmi_pause_vm` actually behaves on Xen. By default Xen keeps a counter of how many times "pause" was issued on a domain, and only unpauses it if that counter reaches 0. LibVMI OTOH checks to see whether the domain is already paused, and if it is, it won't pause it again, just returns `VMI_SUCCESS` (see https://github.com/libvmi/libvmi/blob/master/libvmi/driver/xen/xen.c#L2313).

Now when events are being processed, there is a need to synchronize across vCPUs in case events are being swapped or cleared in a callback. It is not safe to do that work right there in the callback, because on multi-vCPU guests there may already be events queued from the other vCPUs for the event. So the entire domain needs to be paused, all events from the ring are processed, and only then are events cleared/swapped (see here https://github.com/libvmi/libvmi/blob/master/libvmi/driver/xen/xen_events_48.c#L1206). That task however pauses/unpauses the VM with the same API. Thus if you have already paused the VM in the callback and then you try to swap/clear events, the pause in the event processing logic won't actually do anything, and then the resume is executed.

You can either change the pause behavior in Xen to always pause and never check the existing state of the VM, or change the logic in the events processing to not go through the `vmi_pause_vm` API and go straight to libxc. I would suggest the latter as the best way forward because in the past we had issues with VMs hanging because their pause/unpause counts got whacked out-of-sync.

**Comment by Wenzel** [comment]
Thanks for the details.
However, i would like to keep a standard, unmodified Libvmi if possible.

To better explain my problem, let me give you some context.
I'm implementing the singlestep in my radare2 plugin.

When i initialize the debugger, i'm _attaching_ to a process by waiting on a CR3 load event, and checking that the pid matches the one i'm looking for.

At this point i'm clearing the event (inside the callback): https://github.com/Wenzel/radare2-extras/blob/vmi/vmi/debug_vmi.c#L69

And immediately pausing the VM: https://github.com/Wenzel/radare2-extras/blob/vmi/vmi/debug_vmi.c#L137

When i'm asked to single step one instruction, all i want to do is

1. setup the single step `vmi_event`
2. register the event
3. resume the VM
4. listen on events
5. process the first single step event, and unregister it
6. pause the VM again

Here is the code for that:
~~~
static int __step(RDebug *dbg) {
    ...
    vmi_event_t sstep_event = {0};
    sstep_event.version = VMI_EVENTS_VERSION;
    sstep_event.type = VMI_EVENT_SINGLESTEP;
    sstep_event.callback = cb_on_sstep;
    sstep_event.ss_event.enable = 1;
    SET_VCPU_SINGLESTEP(sstep_event.ss_event, rio_vmi->current_vcpu);
    vmi_register_event(rio_vmi->vmi, &sstep_event);
    interrupted = false;

    // resume vm
    status = vmi_resume_vm(rio_vmi->vmi);
    if (status == VMI_FAILURE)
    {
        eprintf("Fail to resume VM\n");
        return false;
    }

    while (!interrupted) {
        printf("Listen to VMI events\n");
        status = vmi_events_listen(rio_vmi->vmi, 1000);
        if (status == VMI_FAILURE)
        {
            eprintf("Fail to listen to events\n");
            return false;
        }
        printf("Listening done\n");
    }

    // pause vm again
    status = vmi_pause_vm(rio_vmi->vmi);
    if (status == VMI_FAILURE)
    {
        eprintf("Fail to pause VM\n");
        return false;
    }

    return true;
}

// and the callback
event_response_t cb_on_sstep(vmi_instance_t vmi, vmi_event_t *event) {
    status_t status;

    printf("%s\n", __func__);

    // clear event
    status = vmi_clear_event(vmi, event, NULL);
    if (status == VMI_FAILURE)
    {
        eprintf("Fail to clear event\n");
        return false;
    }

    // stop monitoring
    interrupted = true;
    return 0;
}
~~~

What i notice is that my RIP register is totally inconsistent with what i'm expecting (jump to next instruction).
Now i think there is a race condition between the moment when i'm unregistering the event, and the callback finishes , and the moment i'm pausing the VM again.

My question is: is there an easier to just single step one instruction while keeping the VM paused ?

Thanks !

**Comment by tklengyel** [comment]
What I'm telling you is that currently it is not possible to pause the VM in the callback, so yes, the VM is running when you are leaving the while loop.

**Comment by Wenzel** [comment]
Hi Tamas,

I'm linking #573 here because it's the same issue afterall.

I followed your advice, and paused my VM in the callback, terminated the while loop, and only then cleared the event.
Code is on this Gist: https://gist.github.com/Wenzel/012f4839896be83f1b1a61c7eb162e8e

But i'm still getting another CR3 than the one i processed inside the callback, and this happens everytime now:

~~~
Attaching to pid 4...
vmi_pause_vm
Enabled register event on reg: 20
vmi_resume_vm
Listening on VMI events...
Listening on VMI events...
cb_on_cr3_load
Intercepted PID: 380, CR3: 14d57000, @rip: fffff800028961a9
Listening on VMI events...
cb_on_cr3_load
Intercepted PID: 1352, CR3: f54000, @rip: fffff800028961a9
Listening on VMI events...
cb_on_cr3_load
Intercepted PID: 4, CR3: 187000, @rip: fffff800028961a9
vmi_pause_vm
PID after while loop: 1352, CR3: f54000, @rip: fffff800028961a9
Disabling register event on reg: 20
Wrong PID: 1352
~~~

A couple of things:
- I added a `printf` inside `vmi_pause_vm` and `vmi_resume_vm`
- you can see that `vmi_events_listen` doesn't resume the vm after processing the events, i was expecting the opposite.
- I tweaked the libvmi Xen driver to remove the check on `xen_pause_vm`, but this didn't change our issue:
~~~C
    /* Don't pause if it's already paused. */
    if (info.paused) {
        return VMI_SUCCESS;
    }
~~~

So if my VM is supposed to be paused after the callback and the while loop, why am i getting another CR3 when i query the VCPU register ?

Are you able to reproduce this issue on your Xen installation ?

Thanks.

**Comment by tklengyel** [comment]
Does your VM have multiple vCPUs? You can have multiple events queued from the different vCPUs.

**Comment by Wenzel** [comment]
No, i'm just testing with 1 VCPU, for the sake of simplicity.

**Comment by tklengyel** [comment]
BTW from the log you posted I'm not sure why do you get the impression of having a mov-to-cr3 event after you paused. Looks like you only have events between resume/pause as you should:
```
vmi_resume_vm
Listening on VMI events...
Listening on VMI events...
cb_on_cr3_load
Intercepted PID: 380, CR3: 14d57000, @rip: fffff800028961a9
Listening on VMI events...
cb_on_cr3_load
Intercepted PID: 1352, CR3: f54000, @rip: fffff800028961a9
Listening on VMI events...
cb_on_cr3_load
Intercepted PID: 4, CR3: 187000, @rip: fffff800028961a9
vmi_pause_vm
```

**Comment by tklengyel** [comment]
So the only thing from the log I see is that the CR3 doesn't seem to be the same in the callback and outside the callback, but I don't see a callback after you paused the VM. Try not using `vmi_get_vcpureg` in the callback but use the values already provided in the event structure. It is faster and is more likely to be accurate.

**Comment by Wenzel** [comment]
> So the only thing from the log I see is that the CR3 doesn't seem to be the same in the callback and outside the callback, but I don't see a callback after you paused the VM

Yes, it's because i'm pausing the VM inside the callback, when i found the right CR3.
I expect the CR3 to be the same when i exit the while loop, since the VM is supposed to be paused.

> Try not using vmi_get_vcpureg in the callback but use the values already provided in the event structure. It is faster and is more likely to be accurate.

I was very surprised to see that i could have different values inside the callaback for the CR3:
`event->reg_event.value`, and `event->x86_regs->cr3` !!

Look (code is at https://gist.github.com/Wenzel/f2c7c3accb39e4b219cf4a2cdba40c8a):
~~~
vmi_pause_vm
Enabled register event on reg: 20
vmi_resume_vm
Listening on VMI events...
Listening on VMI events...
cb_on_cr3_load
Previous pid : 4, cr3 (event->reg_event.previous): 0x187000
Intercepted pid : 4, cr3 (event->x86_regs.cr3): 0x187000, rip (event->x86_regs.rip): 0xfffff800028cb1a6
Intercepted pid : 376, cr3 (event->reg_event.value): 0x15100000, rip (get_vcpureg): 0xfffff800028cb1a9
Listening on VMI events...
cb_on_cr3_load
Previous pid : 376, cr3 (event->reg_event.previous): 0x15100000
Intercepted pid : 376, cr3 (event->x86_regs.cr3): 0x15100000, rip (event->x86_regs.rip): 0xfffff800028cb1a6
Intercepted pid : 4, cr3 (event->reg_event.value): 0x187000, rip (get_vcpureg): 0xfffff800028cb1a9
Found PID 4 !, pausing VM before exiting callback
vmi_pause_vm
After while loop, PID: 376, CR3: 15100000, rip: fffff800028cb1a9
Disabling register event on reg: 20
Wrong PID
~~~

-> Why are they different ? I was expecting them to be equal since it's same event struct.
Which one should i rely ?

Regarding `get_vcpureg`, you can see that after my while loop, the value of `RIP` that i obtain with `get_vcpureg` (`fffff800028cb1a9`) is the same as `event->x86_regs.rip` inside the callback.
However, the CR3 value is the same as `event->reg_event.value`.



Thanks.

**Comment by tklengyel** [comment]
Because you are prohibiting the VM from executing the MOV-TO-CR3 instruction. That's how the event is generated by the hardware. At that point the new CR3 value may not have been propagated to the actual VM state and may only get finalized when the monitor event returns.

**Comment by tklengyel** [comment]
You can see that `event->reg_event.previous` and `event->x86_regs.cr3` are the same. The new CR3 value that will get loaded after the callback finished when vCPU resumes is what's in `event->reg_event.value`.

Now since you have paused the VM, the vCPU hasn't resumed yet so it looks like the new CR3 value hasn't got propagated into the VM state either, so `vmi_get_vcpureg` returns the previous CR3 value.

**Comment by Wenzel** [comment]
Ok, now i understand better what's happening.

But what do you suggest for the use case i have ?

- Interrupting the VM on a certain CR3
- pausing it.
- and later on calling `vmi_get_vcpuregs` and other functions to query the hardware state.

what about adding a new `event_response_t` to pause the VM in a way that the VCPU gets synchronized with the event new values ?

**Comment by tklengyel** [comment]
That would require LibVMI to maintain a local cache of vCPU states and keep track of what events are enabled and how they behave regarding whether the value is loaded before or after the vCPU resumes. I rather not do that as it gets messy. You can just stash the "current" CR3 register that will get loaded once the vCPU executes in a global variable so that it you can access it outside the callback.

**Comment by tklengyel** [comment]
I would say just put a warning in the comment for `vmi_get_vcpureg` regarding this behavior.

**Comment by Wenzel** [comment]
![mov_cr3](https://user-images.githubusercontent.com/964610/36107324-5840b84c-1022-11e8-8393-f76b6779c3d3.png)
Awesome, i'm now pausing **exactly** on the MOV-TO-CR3 instruction !

thanks =)
