### ISSUE TITLE
Feature: API to get a list of currently mapped regions

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#572]
Hi,

This issue is a feature request.
I would like to have in Libvmi and API giving me the list of continuous memory mapped regions and their permissions, similar as what `/proc/pid/maps` can give.

Libvmi will have to deal with the low level details of parsing the pagetables.
I'm sure you are already doing that, but there is no API to get the list of memory mappings available.

To give you a bit of context, i am developping a debug plugin for `radare2`, and i came accross the issue of having to get the mappings to place a breakpoint.

example in `radare2`:
~~~
[0x7fa738210c30]> dm
0x0000000000400000 # 0x000000000041e000 - usr   120K s -r-x /bin/ls /bin/ls ; map.bin_ls._r_x
0x000000000061d000 # 0x000000000061f000 - usr     8K s -rw- /bin/ls /bin/ls ; map.bin_ls._rw
0x000000000061f000 # 0x0000000000620000 - usr     4K s -rw- unk0 unk0
0x00007fa738210000 # 0x00007fa738236000 * usr   152K s -r-x /lib/x86_64-linux-gnu/ld-2.23.so /lib/x86_64-linux-gnu/ld-2.23.so ; map.lib_x86_64_linux_gnu_ld_2.23.so._r_x
0x00007fa738435000 # 0x00007fa738437000 - usr     8K s -rw- /lib/x86_64-linux-gnu/ld-2.23.so /lib/x86_64-linux-gnu/ld-2.23.so ; map.lib_x86_64_linux_gnu_ld_2.23.so._rw
0x00007fa738437000 # 0x00007fa738438000 - usr     4K s -rw- unk1 unk1
0x00007fff112b0000 # 0x00007fff112d1000 - usr   132K s -rw- [stack] [stack] ; map.stack_._rw
0x00007fff113b2000 # 0x00007fff113b5000 - usr    12K s -r-- [vvar] [vvar] ; map.vvar_._r
0x00007fff113b5000 # 0x00007fff113b7000 - usr     8K s -r-x [vdso] [vdso] ; map.vdso_._r_x
0xffffffffff600000 # 0xffffffffff601000 - usr     4K s -r-x [vsyscall] [vsyscall] ; map.vsyscall_._r_x
~~~

What do you think ?
Would this feature be as easy as almost opening an internal API ?
Or does it requires more work ?

Thanks !

**Comment by tklengyel** [comment]
Have you taken a look at `vmi_get_va_pages`?

**Comment by Wenzel** [comment]
Thanks, i just discovered this new API and a new header `libvmi/libvmi_extra.h` :)

I tried to run `libvmi/examples/va-pages.c`
and it always fail to read the beginning of the content of the page with `vmi_read_64`:
~~~
Page in virtual address space of DTB 0x187000 unaccessible: 0xfffff8800096e000.	Size: 0x1000
Page in virtual address space of DTB 0x187000 unaccessible: 0xfffff8800096d000.	Size: 0x1000
Page in virtual address space of DTB 0x187000 unaccessible: 0xfffff8800096c000.	Size: 0x1000
Waiting for events...
Page in virtual address space of DTB 0x14d4e000 unaccessible: 0xfffffffffffe0000.	Size: 0x1000
Page in virtual address space of DTB 0x14d4e000 unaccessible: 0xffffffffffd09000.	Size: 0x1000
Page in virtual address space of DTB 0x14d4e000 unaccessible: 0xffffffffffd06000.	Size: 0x1000
~~~

Something is wrong with the example ?

Also, i would need to have more information from a page table entry:
- `Supervisor` bit
- `RWX` permissions.

How difficult would it be to implement in the Xen driver for example ?
Thanks.

**Comment by tklengyel** [comment]
The `page_info_t` structure contains all the information that would present in the pagetable, so you have access to the `Supervisor` and `RWX` bits. I suggest reviewing the `libvmi/x86.h` header as well that contains the definitions you can check against the page table entries.

**Comment by Wenzel** [comment]
I was able to extract the `supervisor` and `read/write` permission bits with the macros defined in `x86.h`.

But i had to get the `page_mode` first to know which `pte_value` i had to use.
Also, i had to check which one of them was setting the `NX` bit to get the execute permissions.

My code
~~~C
page_mode_t page_mode;
page_mode = vmi_get_page_mode(rio_vmi->vmi, rio_vmi->current_vcpu);

GSList *va_pages = vmi_get_va_pages(rio_vmi->vmi, dtb);

GSList *loop = va_pages;
    int nb = 0;
    while (loop)
    {
        addr_t pte_value = 0;
        page_info_t *page = loop->data;
        int permissions = R_IO_READ;
        int supervisor = 0;
        char str_nb[20];
        // get permissions
        switch (page_mode) {
            case VMI_PM_LEGACY:
                pte_value = page->x86_legacy.pte_value;
                break;
            case VMI_PM_PAE:
                pte_value = page->x86_pae.pte_value;
                if (!VMI_GET_BIT(pte_value, 63))
                    permissions |= R_IO_EXEC;
                break;
            case VMI_PM_IA32E:
                pte_value = page->x86_ia32e.pte_value;
                break;
            default:
                eprintf("Unhandled page mode");
                // TODO free
                return NULL;
        }
        supervisor = USER_SUPERVISOR(pte_value);
        if (READ_WRITE(pte_value))
            permissions |= R_IO_WRITE;
        // build RDebugMap
        addr_t map_start = page->vaddr;
        addr_t map_end = page->vaddr + page->size;
        RDebugMap *r_debug_map = r_debug_map_new (map_name, map_start, map_end, permissions, supervisor);
        // append
        r_list_append (r_maps, r_debug_map);
        // loop
        loop = loop->next;
        nb +=1;
    }

~~~


I think libvmi could provide me an abstraction in the `page_into_t` structure, by extracting these permissions and bits when the `va_pages` list is generated.

**Comment by tklengyel** [comment]
Since you had been able to extract the information you need using existing APIs I don't see a pressing need to change it.

**Comment by Wenzel** [comment]
It's not urgent of course, but in the future, having this kind of API/abstraction would be a good feature.

**Comment by Wenzel** [comment]
Closing this issue since the initial problem has been solved.
