### ISSUE TITLE
step-event-example: mistake with vmi_translate_kv2p ?

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#575]
Hi,

again on `step-event-example`:

https://github.com/libvmi/libvmi/blob/master/examples/step-event-example.c#L175
~~~C
    vmi_dtb_to_pid(vmi, cr3, &pid);
    if (pid==4) {
        vmi_translate_uv2p(vmi, rip, pid, &rip_pa);
    } else {
        vmi_translate_kv2p(vmi, rip, &rip_pa);
    }
~~~

It looks like there is a mistake here, and if pid is 4 (Windows kernel), then you should translate using `vmi_translate_kv2p`, not `vmi_translate_uv2p`

**Comment by tklengyel** [comment]
Yes, looks like it's swapped. Feel free to open a PR to fix it!
