### ISSUE TITLE
Listening on Xen events can crash guest VM ?

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#577]
Hi,

I wanted to report an issue that i faced multiple times when introspecting my VMs with libvmi.

Sometimes, when i run my vmi tool against a Windows 7 VM, intercepting registers and playing with the event API, the guest crashed (BSOD, or total crash).
It's very rare, but it happens.

Now i wanted to ask if you already observed this issue before ?
Especially with the event API on Xen ?

Since passively listening to cr3 events is not supposed to change anything of the guest execution context, i was finding that suspicious.

All i have to investigate is some Windows minidumps, but i'm not an expert in this matter.

Thanks.

**Comment by tklengyel** [comment]
Events can absolutely crash the guest. Simple things such at taking too long in the callback may timeout watchdogs in the guest and lead to bluescreens.

**Comment by Wenzel** [comment]
Okay, i was also thinking about some timeouts issues in the guest.

Thanks for the confirmation.

**Comment by mfusaro** [comment]
@Wenzel if you want to send the minidumps my way, I can take a look.

**Comment by Wenzel** [comment]
@mfusaro That would be great !
Do you have an email so i can contact you ?

**Comment by mfusaro** [comment]
That would help huh? ;) matthew.fusaro@zentific.com

**Comment by aoshiken** [comment]
@Wenzel Are you referring to the bugcheck of timeout elapsed without receiving interrupts?

This one:
![screenshot](https://user-images.githubusercontent.com/5227552/36589369-53cb6246-188b-11e8-9001-23a2c3eee0a7.png)

**Comment by Wenzel** [comment]
@aoshiken , no i was just intercepting CR3 writes.
But it appears that the bug was in the graphic stack, so not related to VMI.
