### ISSUE TITLE
Unable to read memory on Windows 10 guest

### ISSUE THREAD

**Issue by buekera** [libvmi/libvmi#602]
### Host
* Arch Linux 4.15.15
* qemu 2.12

### Guest
* Windows 10 latest patch
* 8GB Ram

### Error
I'm getting this error when trying to interact with the guest.
```
VMI_ERROR: create_new_entry failed
VMI_ERROR: --requesting PA [0x2c775e000] beyond max physical address [0x234000000]
VMI_ERROR: 	paddr: 2c775d000, length 1000, vmi->max_physical_address 234000000
VMI_ERROR: create_new_entry failed
VMI_ERROR: --requesting PA [0x27bed2000] beyond max physical address [0x234000000]
VMI_ERROR: 	paddr: 27bed1000, length 1000, vmi->max_physical_address 234000000
VMI_ERROR: create_new_entry failed
VMI_ERROR: --requesting PA [0x266f7b000] beyond max physical address [0x234000000]
VMI_ERROR: 	paddr: 266f7a000, length 1000, vmi->max_physical_address 234000000
VMI_ERROR: create_new_entry failed
VMI_ERROR: --requesting PA [0x30c7cd000] beyond max physical address [0x234000000]
VMI_ERROR: 	paddr: 30c7cc000, length 1000, vmi->max_physical_address 234000000
VMI_ERROR: create_new_entry failed
VMI_ERROR: --requesting PA [0x2df68e000] beyond max physical address [0x234000000]
VMI_ERROR: 	paddr: 2df68d000, length 1000, vmi->max_physical_address 234000000
VMI_ERROR: create_new_entry failed
VMI_ERROR: --requesting PA [0x2bdffa000] beyond max physical address [0x234000000]
VMI_ERROR: 	paddr: 2bdff9000, length 1000, vmi->max_physical_address 234000000
```

It seems like the calculation of total physical memory fails.

On Windows 7 this error is not occuring.

Does anyone have an idea?

**Comment by Wenzel** [comment]
that's weird, because we fixed this issue the KVM driver of LibVMI for guests having more than 4G of RAM. :thinking:

**Comment by buekera** [comment]
Yea, I saw that. I will check my configuration - again. Maybe I am missing something.

**Comment by buekera** [comment]
As it turned out I somehow gucked up the global installation of libvmi with the patch you mentioned @Wenzel 

This can be closed!

**Comment by Wenzel** [comment]
@buekera so you deleted your old installation, and reinstalled Libvmi again ?

If it works, you can close the issue, yes !

**Comment by buekera** [comment]
Yes, I deleted the old libvmi installation, reinstalled it and the described error disappeared.
