### ISSUE TITLE
Get Windows kernel image base address with LibVMI

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#612]
By looking at the Rekall profile JSON output:
~~~JSON
{
 "$CONSTANTS": {
  "$$VProc_ImageExportDirectory": 5439488, 
  "AT_Initialization": 2011144, 
  "AcquireOpsEvent": 2600864, 
  "AcquireOpsReservePool": 2600856, 
  "ActionNames": 5569152, 
  "AdtpAccessIdsStringBuffer": 2205120, 
  "AdtpEventIdStringSpecific": 2204864, 
  "AdtpEventIdStringStandard": 2205696, 
  "AdtpNullGuid": 5509144, 
  "AdtpNullSid": 5509128, 
  "AdtpPerCategoryCount": 5509160, 
  "AdtpRegisteredWithEtw": 5509120, 
  "AdtpSourceModuleLock": 2205824, 
  "AdtpSourceModules": 2204832, 
  "AdtpStandardAccessTypes": 1756488, 
  "AeCacheFlushEvent": 1791648, 
  "AeCacheInsertEvent": 1791616, 
  "AeCacheLookupEvent": 1791600, 
~~~
All the constants are very small number, and translated to hex:
~~~
In [1]: hex(2600856)
Out[1]: '0x27af98'
~~~
They cannot be absolute addresses.

Instead, i discovered that they are relative offsets to the Windows kernel image base address, as stated by Michael Cohen:
https://groups.google.com/forum/#!searchin/rekall-discuss/$24CONSTANTS/rekall-discuss/yhrioqPtJYA/pSpJnkpVCwAJ

So i would like to use this JSON profile while I'm introspecting a VM, and access these symbols like `PsActiveProcessHead`.

But for that, i would need to know the Windows kernel base address.

Is there a way that Libvmi already has this information when it is being initialized ?

Thanks !

**Comment by Wenzel** [comment]
by looking at `libvmi/os/windows/kdbg.c`:
https://github.com/libvmi/libvmi/blob/master/libvmi/os/windows/kdbg.c#L202

It seems that libvmi is already doing what i was looking for, but on a small, hardcoded, subset of the symbols available in the rekall profile.

**Comment by Wenzel** [comment]
The `libvmi/os/windows/windows.h` header is not exported by libvmi.

Is there a way to access the `ntoskrnl_va` field in the `windows_instance` struct ?
https://github.com/libvmi/libvmi/blob/master/libvmi/os/windows/windows.h#L30

**Comment by tklengyel** [comment]
The function you are looking for is `vmi_translate_sym2v`

**Comment by Wenzel** [comment]
I wanted to do the translation by myself (`kernel_va + offset`), since i need to parse the JSON anyway to iterate over the `$CONSTANTS` names.

but i can use this function, yes.
Thanks.

**Comment by tklengyel** [comment]
You can always just use sym2v then subtract the rva from it to get the base address.

**Comment by Wenzel** [comment]
I tried to iterate over the `$CONSTANTS` and use `vmi_translate_ksym2v`, but it was way too slow,
so i computed the kernel base address as you said, and i have my symbols.

Thanks @tklengyel
