### ISSUE TITLE
vmidbg / livvmi / ubuntu

### ISSUE THREAD

**Issue by tawan58** [libvmi/libvmi#626]
Help me pls!!

now I'm try to install VMIdbg on ubuntu server 16.04 but it's error when i run "make" and "make install"

server@server:~/Downloads/vmidbg-master$ sudo su
[sudo] password for server: 
root@server:/home/server/Downloads/vmidbg-master# ./autogen.sh 
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Remember to add 'LT_INIT' to configure.ac.
configure.ac:11: installing './compile'
configure.ac:3: installing './missing'
src/Makefile.am: installing './depcomp'
root@server:/home/server/Downloads/vmidbg-master# make
 cd . && /bin/bash ./config.status Makefile 
config.status: creating Makefile
make  all-recursive
make[1]: Entering directory '/home/server/Downloads/vmidbg-master'
Making all in src
make[2]: Entering directory '/home/server/Downloads/vmidbg-master/src'
 cd .. && /bin/bash ./config.status src/Makefile depfiles
config.status: creating src/Makefile
config.status: executing depfiles commands
gcc -DHAVE_CONFIG_H -I. -I..     -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -ggdb -g -O0  -MT vmidbg.o -MD -MP -MF .deps/vmidbg.Tpo -c -o vmidbg.o vmidbg.c
vmidbg.c: In function ‘get_executing_task’:
vmidbg.c:95:9: error: too many arguments to function ‘vmi_translate_ksym2v’
         vmi_translate_ksym2v(vmi, "per_cpu__current_task", &per_cpu_current_tas
         ^
In file included from vmidbg.c:17:0:
/usr/local/include/libvmi/libvmi.h:804:8: note: declared here
 addr_t vmi_translate_ksym2v(
        ^
vmidbg.c:99:9: error: too many arguments to function ‘vmi_translate_ksym2v’
         vmi_translate_ksym2v(vmi, "current_task", &per_cpu_current_task_offset)
         ^
In file included from vmidbg.c:17:0:
/usr/local/include/libvmi/libvmi.h:804:8: note: declared here
 addr_t vmi_translate_ksym2v(
        ^
vmidbg.c: In function ‘gdb_step_notify’:
vmidbg.c:399:9: warning: ‘return’ with no value, in function returning non-void
         return;
         ^
vmidbg.c:405:9: warning: ‘return’ with no value, in function returning non-void
         return;
         ^
vmidbg.c: In function ‘gdb_bp_notify’:
vmidbg.c:435:9: warning: ‘return’ with no value, in function returning non-void
         return;
         ^
vmidbg.c:441:9: warning: ‘return’ with no value, in function returning non-void
         return;
         ^
vmidbg.c:460:9: warning: ‘return’ with no value, in function returning non-void
         return;
         ^
vmidbg.c: In function ‘vmi_regs_to_gdb’:
vmidbg.c:505:2: warning: #warning libvmi needs 32bit registers defined [-Wcpp]
 #warning libvmi needs 32bit registers defined
  ^
vmidbg.c: In function ‘gdb_rsp_interrupt_sequence’:
vmidbg.c:608:9: error: too many arguments to function ‘vmi_get_offset’
         vmi_get_offset(ctx->vmi, "linux_pid", &pid_offset);
         ^
In file included from vmidbg.c:17:0:
/usr/local/include/libvmi/libvmi.h:1881:10: note: declared here
 uint64_t vmi_get_offset(
          ^
vmidbg.c:609:9: error: too many arguments to function ‘vmi_get_offset’
         vmi_get_offset(ctx->vmi, "linux_tasks", &tasks_offset);
         ^
In file included from vmidbg.c:17:0:
/usr/local/include/libvmi/libvmi.h:1881:10: note: declared here
 uint64_t vmi_get_offset(
          ^
vmidbg.c:611:9: error: too many arguments to function ‘vmi_translate_ksym2v’
         vmi_translate_ksym2v(ctx->vmi, "init_task", &list_head);
         ^
In file included from vmidbg.c:17:0:
/usr/local/include/libvmi/libvmi.h:804:8: note: declared here
 addr_t vmi_translate_ksym2v(
        ^
vmidbg.c: In function ‘gdb_rsp_read_mem’:
vmidbg.c:732:40: warning: passing argument 4 of ‘vmi_read_va’ makes pointer from integer without a cast [-Wint-conversion]
     vmi_read_va(ctx->vmi, mem_addr, 0, mem_size, vmibuf, &bytes_read);
                                        ^
In file included from vmidbg.c:17:0:
/usr/local/include/libvmi/libvmi.h:1038:8: note: expected ‘void *’ but argument is of type ‘size_t {aka long unsigned int}’
 size_t vmi_read_va(
        ^
vmidbg.c:732:50: warning: passing argument 5 of ‘vmi_read_va’ makes integer from pointer without a cast [-Wint-conversion]
     vmi_read_va(ctx->vmi, mem_addr, 0, mem_size, vmibuf, &bytes_read);
                                                  ^
In file included from vmidbg.c:17:0:
/usr/local/include/libvmi/libvmi.h:1038:8: note: expected ‘size_t {aka long unsigned int}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 size_t vmi_read_va(
        ^
vmidbg.c:732:5: error: too many arguments to function ‘vmi_read_va’
     vmi_read_va(ctx->vmi, mem_addr, 0, mem_size, vmibuf, &bytes_read);
     ^
In file included from vmidbg.c:17:0:
/usr/local/include/libvmi/libvmi.h:1038:8: note: declared here
 size_t vmi_read_va(
        ^
Makefile:351: recipe for target 'vmidbg.o' failed
make[2]: * [vmidbg.o] Error 1
make[2]: Leaving directory '/home/server/Downloads/vmidbg-master/src'
Makefile:362: recipe for target 'all-recursive' failed
make[1]: * [all-recursive] Error 1
make[1]: Leaving directory '/home/server/Downloads/vmidbg-master'
Makefile:303: recipe for target 'all' failed
make: * [all] Error 2
root@server:/home/server/Downloads/vmidbg-master#

**Comment by smaresca** [comment]
Will address this in the vmidbg issue you opened (https://github.com/Zentific/vmidbg/issues/4) rather than as a libvmi issue
