### ISSUE TITLE
DTB value stored in event variable does not match pid_to_dtb

### ISSUE THREAD

**Issue by auermich93** [libvmi/libvmi#639]
Dear Community,

the DTB value obtained from vmi_pid_to_dtb does not match the DTB value stored in the event pointer.
This means, the following check as performed in example/event-example.c:

if (event->reg_event.value == cr3) 

fails. Moreover, event->reg_event.previous coincides with event->reg_event.value and the value
stored in the CR3 register.  Seems like the value refers to the old DTB (the DTB of the previous task).
The reverse function vmi_dtb_to_pid only works with the cr3 value obtained from vmi_pid_to_dtb.

The guest OS I am using is Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-124-generic x86_64).
On some older Debian version, the above mentioned check works perfectly and the reg_event.value
referred to the new DTB.

I am looking for a cheap method that let me verify that a particular process is scheduled next.

Best regards
Michael

**Comment by Wenzel** [comment]
Linking this issue I opened a few month ago: https://github.com/libvmi/libvmi/issues/569#issuecomment-364683146, where we already discussed this problem.

**Comment by auermich93** [comment]
But, as described, it is not only the problem of seeing an inconsistent/old value.
Using this value in the vmi_dtb_to_pid function leads to an error. In particular, I obtain:
"Could not find task struct for pgd" from the linux_pgd_to_pid function in libvmi/os/linux/memory.c

**Comment by tklengyel** [comment]
`vmi_dtb_to_pid` and `vmi_pid_to_dtb` were not designed with events in mind. I generally recommend not using them in that context.

**Comment by auermich93** [comment]
Can you suggest some alternative?

As far as I remember, on the previous kernel I used, the FS_BASE or GS_BASE register contained
the task_struct of the 'current' task. However, now I can't see any linkage between the register contents
and the task_struct base addresses. Are you aware of any reliable source?

**Comment by smaresca** [comment]
@auermich93 FS/GS base holds the location where per-cpu variables begin.  E.g. gs_base + current task offset = address of the task_struct representing the task active on that CPU, equivalent to 'current' macro in kernel code.

**Comment by auermich93** [comment]
@smaresca Thanks for the hint. I guess you refer to the linux_get_current_task implementation used in DRAKVUF. But, this is probably referring to the 'curren't task right before the context-switch is fully performed.

**Comment by tklengyel** [comment]
@auermich93 No, that functions will return to you the task that will execute after the context switch finishes. Look at https://github.com/tklengyel/drakvuf/blob/master/src/libdrakvuf/linux-processes.c#L130:
```
 .addr = drakvuf->regs[vcpu_id]->gs_base + drakvuf->offsets[CURRENT_TASK],
```
The register `gs_base` is already loaded with the address belonging to the new task, otherwise things would fall apart in the guest. Just make sure you use the `gs_base` that is delivered with the event itself.

**Comment by auermich93** [comment]
@tklengyel, @smaresca Thanks again.
I was able to derive the task struct address and several other members.

However, I just noticed that whatever I do in the CR3 callback, my guest crashes.
I have simplified the callback to two statements; a printf followed by a return.

**Comment by tklengyel** [comment]
Newer OS version implement Spectre mitigations which make use of the PCID. That feature sets bit 63 of the CR3 and in Xen version before Xen 4.11 it wasn't properly masked leading to a invalid guest state. Try upgrading to Xen 4.11 (rc6 works just fine).

**Comment by bentau** [comment]
Do you know if there is a patch for xen 4.8?

**Comment by auermich93** [comment]
Upgrading resolved the issue. Gonna close this one.
