### ISSUE TITLE
Breakpoint event not received

### ISSUE THREAD

**Issue by auermich93** [libvmi/libvmi#640]
Dear Community,

I have developed some kind of code injection functionality for Linux x86_64 guests.
However, I have some issue related to a single BP that is not triggered.

The sequence I tried to implant is:
bp1 (saves context)
fork
bp2
some arbitrary instructions (intend to use execve here, right now 0x90 (NO-OPs))
bp3 (restores the context and jumps to location of bp1)

The fork syscall is working fine, I receive the second bp (bp2) twice as expected. One time
the register RAX contains the PID of the newly created child process and one time the register
contains 0 (indicating that the child is operating).
However, the third bp (bp3) is only received once, currently the child's one.
In the guest VM the parent receives a segmentation fault, while the child continues operating.
Dmesg shows me that the third BP of the parent is hit, but causes some error: 
(913 is pid of parent, 914 child)

[   46.846649] traps: test.o[913] general protection ip:7f9d67dac42c sp:7ffd4d30a270 error:0 in libc-2.19.so[7f9d67d38000+1a1000]

The corresponding output of my VMI application is as follows:

The byte size of the code to inject is: 5
The original first instruction is: 0x85
We have read the following instruction sequence: 0x6063cc
The original    instruction at pos: 7f9d67dac424 is: 0xFFFFFF85
The overwritten instruction at pos: 7f9d67dac424 is: 0xf
The original    instruction at pos: 7f9d67dac425 is: 0xFFFFFFC0
The overwritten instruction at pos: 7f9d67dac425 is: 0x5
The original    instruction at pos: 7f9d67dac426 is: 0x79
The overwritten instruction at pos: 7f9d67dac426 is: 0xcc
The original    instruction at pos: 7f9d67dac427 is: 0xFFFFFFD8
The overwritten instruction at pos: 7f9d67dac427 is: 0x90
The original    instruction at pos: 7f9d67dac428 is: 0x41
The overwritten instruction at pos: 7f9d67dac428 is: 0x90
Waiting for events...
The first BP was triggered!
The current instruction is: [RIP] 0x7f9d67dac423
The modified RAX register is: 0x39
The modified instruction pointer is: [RIP] 0x7f9d67dac424
Restore first BP!
Waiting for events...
The second BP [parent] was triggered!
The current instruction is: [RIP] 0x7f9d67dac426
The return value of the fork() syscall is: 914
parent is active
We found our pid in the kernel task structure!
The RIP register after modification contains: 0x7f9d67dac427
End of second BP [parent]
Waiting for events...
The second BP [child] was called!
The instruction pointer is: [RIP] 0x7f9d67dac426
The return value of the fork syscall is: [SHOULD BE 0] 0x0
The instruction at pos [CHILD]: 7f9d67dac427 is: 0x90
The instruction at pos [CHILD]: 7f9d67dac428 is: 0x90
The instruction at pos [CHILD]: 7f9d67dac429 is: 0xcc
The instruction at pos [CHILD]: 7f9d67dac42a is: 0xc
The instruction at pos [CHILD]: 7f9d67dac42b is: 0x24
End of second BP [child]
Waiting for events...
The third BP [child] was triggered!
The instruction pointer is: [RIP] 0x7f9d67dac429
The RAX register contains: 0x0
The original    instruction at pos: 7f9d67dac424 is: 0xFFFFFF85
The restored    instruction at pos: 7f9d67dac424 is: 0x85
The original    instruction at pos: 7f9d67dac425 is: 0xFFFFFFC0
The restored    instruction at pos: 7f9d67dac425 is: 0xc0
The original    instruction at pos: 7f9d67dac426 is: 0x79
The restored    instruction at pos: 7f9d67dac426 is: 0x79
The original    instruction at pos: 7f9d67dac427 is: 0xFFFFFFD8
The restored    instruction at pos: 7f9d67dac427 is: 0xd8
The original    instruction at pos: 7f9d67dac428 is: 0x41
The restored    instruction at pos: 7f9d67dac428 is: 0x41
The modified instruction pointer is: [RIP] 0x7f9d67dac423

I have verified that fork copied the instructions to the child as @tklengyel suggested.
Moreover, what I have noticed is:
Depending on the 'complexity' of the callback handler, the order of the BPs received varies.
Also the reinject behaviour of the event variable influences the entire situation.
Since, I have to manage inserting/removing BPs/events manually, I haven't got the idea
behind this reinject behaviour (maybe this is the problem). Is this related to the specific BP
that caused the event, or is it globally treated (the int3 event)?
If I set this flag to 1, sometimes my target process halts and shows the following msg: Trace/breakpoint trap.
I am currently using a switch-statement that calls the appropriate callback function. I am setting this
reinject behaviour in each callback + before the switch-statement to avoid this LibVMI error that expects
to set the reinject behaviour.

Best regards

**Comment by auermich93** [comment]
Is it possible that there is an upper limit for BPs/BP-events that can be processed
during some certain time interval?

**Comment by smaresca** [comment]
How many VCPUs does this guest have assigned to it?

**Comment by tklengyel** [comment]
>  the order of the BPs received varies
Xen doesn't guarantee any type of "order" for events in which they will be serialized with multi-vCPU systems. So just because event "A" is on the ring before event "B", it doesn't mean "A" happened before "B" if they were generated on different vCPUs.

> How many VCPUs does this guest have assigned to it?
That doesn't really matter. Even if the ring-buffer becomes full the vCPU will just hang until space becomes available. Events will never be dropped because of it.

**Comment by tklengyel** [comment]
> Is it possible that there is an upper limit for BPs/BP-events that can be processed
during some certain time interval?

The only limit you have is your OS detecting some threads hung and killing it. This could happen if your processing takes too long in your callback.

**Comment by auermich93** [comment]
@tklengyel, I will try to reduce the callback complexity as much as possible and see what happens.

What is really strange, if I turn on a function that checks the obtained PID
from the fork syscall against the task struct list within the callback of the parent process (bp2),
I receive the order: bp1, bp2 (parent), bp2 (child), bp3 (child)
If I remove this check, I receive the order: bp1, bp2 (parent), bp3 (parent)
As you can observe, the union would deliver all five BP-events.

**Comment by auermich93** [comment]
@tklengyel, I am sorry, but reducing the callback complexity didn't help.
We are talking here about writing 5 Bytes at max in the callback.

**Comment by tklengyel** [comment]
`¯\_(ツ)_/¯`, rest assured that there is no path where events silently get discarded. If you are missing breakpoints it is because those breakpoints didn't execute. How are you handling the breakpoint events? If you do remove-singlestep-replace then you probably just have a race-condition.

**Comment by auermich93** [comment]
So what I'm basically doing:

MAIN_BEGIN:
Register cr3 event

cr3_callback:

1. Determine suitable location for code
2. Save sequence we intend to overwrite
3. Write sequence '\xcc\x0f\x05\xcc\x90\x90\xcc' at this location (\x0f\x05 is the syscall instruction on x86_64 with the intention to call 'fork', so it is basically bp1-fork-bp2-NOP-NOP-bp3)
4. Install int3_callback handler

int3_callback:
A. Specify reinject behaviour
B. Halt VM
C. Determine which BP was triggered

case bp1: 
1. Prepare arguments for fork syscall
2. Adjust instruction pointer to refer to next instruction (fork)
3. Restore original instruction of bp1
4. Remove cr3 event

case bp2-parent OR bp2-child:
// this will be changed in the future depending on what will be executed within the child
1. Adjust instruction pointer to refer to next instruction (NOP)

case bp3-parent OR bp3-child:
1. Restore original instruction of bp3
2. Restore overwritten sequence (bp1/bp3 restored arleady)
3. Adjust instruction pointer to refer to location of bp1

D. Resume VM
MAIN_END: Remove int3 event

For bp1 it holds that I am doing some kind of 'remove&replace-singlestep' by adjusting the instruction pointer (not using the pre-defined singlestep event).
Later on, I can probably save bp3 completely, but right now for these NOPs, the sequence should be valid though.

**Comment by tklengyel** [comment]
So you remove bp3 the first time it triggers.. I haven't checked Linux's fork implementation but I would not be surprised if it employed CoW memory so that the parent and the child process effectively still share underlying physical memory. So when you remove bp3 the first time it triggers it won't trigger a second time.. because it's no longer in memory.

**Comment by auermich93** [comment]
@tklengyel, thanks for the hint. That could be definitely the problem. I don't think we can alter
the behaviour of fork, maybe the clone syscall is more appropriate.

**Comment by auermich93** [comment]
Using vfork instead of fork resolved the issue. Not the best solution, but working.

**Comment by tklengyel** [comment]
`vfork() is a special case of clone(2).  It is used to create new processes without copying the page tables of the parent process.`

Sounds exactly like what you need so I think its the best solution considering.
