### ISSUE TITLE
Windows XP: vmi_dtb_to_pid broken

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#641]
Hi,

I tried to use Windows XP SP3 with libvmi, Xen `4.10.1` (Fedora 28), installed in a Vagrant box on top of KVM.

The whole point was to have a reproducible environment for r2vmi development.

However, I quickly noticed some errors when using the `vmi_dtb_to_pid` API.
The errors are reproducible with `step-event-example`:

~~~
[vagrant@localhost examples]$ sudo ./step-event-example winxp
LibVMI Suggestion: set win_ntoskrnl=0x4d7000 in libvmi.conf for faster startup.
LibVMI Suggestion: set win_kdbg=0x762e0 in libvmi.conf for faster startup.
LibVMI Suggestion: set win_kdvb=0x8054d2e0 in libvmi.conf for faster startup.
LibVMI init succeeded!
Current value of RIP is 0xf65d6162
VMI_ERROR: Could not find EPROCESS struct for pgd = 0x304000.
VMI_ERROR: Could not find EPROCESS struct for pid = -1.
Preparing memory event to catch next RIP 0xf65d6161, PA 0x0, page 0x0 for PID 4294967295
PID 396 with CR3=6a00060 executing on vcpu 0.
PID 4 with CR3=6a00020 executing on vcpu 0.
VMI_ERROR: Could not find EPROCESS struct for pgd = 0x304000.
PID -1 with CR3=304000 executing on vcpu 0.
 -- Enabling mem-event
PID 4 with CR3=6a00020 executing on vcpu 0.
 -- Disabling mem-event
VMI_ERROR: Could not find EPROCESS struct for pgd = 0x304000.
PID -1 with CR3=304000 executing on vcpu 0.
 -- Enabling mem-event
PID 396 with CR3=6a00060 executing on vcpu 0.
 -- Disabling mem-event
VMI_ERROR: Could not find EPROCESS struct for pgd = 0x304000.
PID -1 with CR3=304000 executing on vcpu 0.
 -- Enabling mem-event
PID 4 with CR3=6a00020 executing on vcpu 0.
 -- Disabling mem-event
VMI_ERROR: Could not find EPROCESS struct for pgd = 0x304000.
PID -1 with CR3=304000 executing on vcpu 0.
 -- Enabling mem-event
PID 4 with CR3=6a00020 executing on vcpu 0.
 -- Disabling mem-event
VMI_ERROR: Could not find EPROCESS struct for pgd = 0x304000.
PID -1 with CR3=304000 executing on vcpu 0.
 -- Enabling mem-event
PID 396 with CR3=6a00060 executing on vcpu 0.
 -- Disabling mem-event
VMI_ERROR: Could not find EPROCESS struct for pgd = 0x304000.
PID -1 with CR3=304000 executing on vcpu 0.
 -- Enabling mem-event
PID 4 with CR3=6a00020 executing on vcpu 0.
 -- Disabling mem-event
VMI_ERROR: Could not find EPROCESS struct for pgd = 0x304000.
PID -1 with CR3=304000 executing on vcpu 0.
 -- Enabling mem-event
PID 4 with CR3=6a00020 executing on vcpu 0.
 -- Disabling mem-event
VMI_ERROR: Could not find EPROCESS struct for pgd = 0x304000.
PID -1 with CR3=304000 executing on vcpu 0.
 -- Enabling mem-event
PID 396 with CR3=6a00060 executing on vcpu 0.
 -- Disabling mem-event
VMI_ERROR: Could not find EPROCESS struct for pgd = 0x304000.
...
~~~

I even installed `WinDBG`  in the VM to make sure I had the right offets:
![screenshot from 2018-07-08 18-26-37](https://user-images.githubusercontent.com/964610/42421434-50bbb17e-82de-11e8-8a65-1334572a9955.png)

Which translates to `/etc/libvmi.conf`
~~~
winxp {
    ostype = "Windows";
    win_pdbase  = 0x18;
    win_pid     = 0x84;
    win_tasks   = 0x88;
    win_pname   = 0x174;
}
~~~

The error message in libvmi is located [here](https://github.com/libvmi/libvmi/blob/8e6aa25ee582499b524264558cce2074f01ba36d/libvmi/os/windows/memory.c#L153), in `memory.c:windows_pgd_to_pid`.

So is the `vmi_dtb_to_pid` supposed to work all the time ?
Or maybe we found an unhandled corner case in LibVMI ? 

Thanks for your help

**Comment by Wenzel** [comment]
I continued to investigate by printing the process list from `WinDBG` with `!process 0 0`:
![screenshot from 2018-07-08 19-58-58](https://user-images.githubusercontent.com/964610/42422157-ce1864d6-82e9-11e8-9e91-984ef622c8e9.png)
![screenshot from 2018-07-08 19-59-19](https://user-images.githubusercontent.com/964610/42422159-d0ea31e4-82e9-11e8-8a64-7fb0772bd1a1.png)

As you can see, every process's `DirectoryTableBase` is located at `0x6a00xxx`.

Now how is it possible for `CR3` to have a value of `0x304000` ? :thinking:

**Comment by tklengyel** [comment]
No, `vmi_dtb_to_pid` is not supposed to work all the time. In fact, its use is very much discouraged when using events or when performing malware analysis.

**Comment by Wenzel** [comment]
I confirm that `vmi_get_vcpureg` returns this invalid (?) `CR3` value.
~~~C
vmi_get_vcpureg(vmi, &rip, RIP, 0);
vmi_get_vcpureg(vmi, &cr3, CR3, 0);

printf("Current value of CR3 is 0x%lx\n", cr3);
~~~
~~~
LibVMI init succeeded!
Current value of CR3 is 0x304000
~~~

**Comment by Wenzel** [comment]
@tklengyel okay
but we have a different kind of problem here, where `vmi_get_vcpureg` is returning a `CR3` that doesn't belong to any of the active processes.

**Comment by tklengyel** [comment]
No, it just means that no process in the non-binding Windows internal process linked-list has a matched DTB. That doesn't make the value invalid.

**Comment by Wenzel** [comment]
@tklengyel that's entirely possible because it can't see it listed in `WinDBG.`

I went back to Windows XP because Windows 7 is having a BSOD at boot time in nested virtualization.
But on Windows 7 this is not happening, so i guess this `Idle` process is now back into the process list somehow.

Thanks for your help !

**Comment by smaresca** [comment]
@Wenzel I agree with @tklengyel on all points here. 

If, however, you wish to satisfy your curiosity you could certainly inspect PsInitialSystemProcess->Pcb.DirectoryTableBase and PsIdleProcess->Pcb.DirectoryTableBase.

Both are initialized in a manner similar to the Linux equivalents init_task and the related init_mm. Many operating systems use statically constructed page tables for boot and for some context switching operations. They can often appear in CR3 events and are not a cause for concern.

**Comment by Wenzel** [comment]
Hi @smaresca,
thank you very much for your advice.
It was indeed the `IDLE` process's CR3, and I checked this info using `PsIdleProcess`.

Therefore I was able to add support for Windows XP in `r2vmi`, and as it's the only system which is able to boot in nested virtualization under Xen, i can have a fast development cycle working directly with Xen source code.

Thank you guys !!
