### ISSUE TITLE
INT3 event: Need to specify reinjection behaviour!

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#660]
HI,

I'm a bit confused by the message i receive from LibVMI when I try to play with interrupts.

First i configured my interrupt with
~~~C
SETUP_INTERRUPT_EVENT(bp_event, 0, cb_on_int3);
~~~

which should set the reinject behavior to 0.

When i run my test, the callback `cb_on_int3` is called, followed by a message from LibVMI:
`VMI_ERROR: process_interrupt_event Need to specify reinjection behaviour!`

As a user and developer, this message is a bit confusing, because I think I already configured the reinjection behavior.

Looking at the function where the error message came from:`
https://github.com/libvmi/libvmi/blob/master/libvmi/driver/xen/xen_events_48.c#L216

I notice that there is a switch a couple of lines ealier to the error message, that will set the reinjection behavior to `-1`:
https://github.com/libvmi/libvmi/blob/master/libvmi/driver/xen/xen_events_48.c#L183

which leads to the test printing the error message.

Could you give me some explanation about this error and the related code ?

Thanks.

**Comment by tklengyel** [comment]
`SETUP_INTERRUPT_EVENT` has to be updated not to take the reinjection behavior as input. That field needs to be filled in during the callback.

**Comment by tklengyel** [comment]
> Could you give me some explanation about this error and the related code ?

Configuring a global reinjection behavior is bad and can lead to issues even harder to debug. Developers need to determine which breakpoints need reinjection on a case-by-case basis. The best place to do that is in the callback.
