### ISSUE TITLE
vmi_step_event doesn't clear single step event

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#663]
Hi,

I'm playing with interrupts, and inside a callback on an `int3`, i have been using the `vmi_step_event` API to singlestep one instruction (once the original opcode has been replaced).
~~~C
static event_response_t cb_on_int3(vmi_instance_t vmi, vmi_event_t *event){
    ...
    // unset radare2 breakpoint (rewrite original instruction)
    r_bp_restore_one(event_data->bp, event_data->bpitem, false);
    // singlestep once
    status = vmi_step_event(vmi, event, event->vcpu_id, 1, NULL);
    if (VMI_FAILURE == status)
    {
        eprintf("fail to singlestep\n");
        return VMI_EVENT_RESPONSE_NONE;
    }
    // restore radare2 breakpoint 
    r_bp_restore_one(event_data->bp, event_data->bpitem, true);
~~~

In my interactive debugger, i wanted to singlestep right after that, using a custom one: (not `vmi_step_event`)
~~~C
    rio_vmi->sstep_event = calloc(1, sizeof(vmi_event_t));
    rio_vmi->sstep_event->version = VMI_EVENTS_VERSION;
    rio_vmi->sstep_event->type = VMI_EVENT_SINGLESTEP;
    rio_vmi->sstep_event->callback = cb_on_sstep;
    rio_vmi->sstep_event->ss_event.enable = 1;
    SET_VCPU_SINGLESTEP(rio_vmi->sstep_event->ss_event, rio_vmi->current_vcpu);
    status = vmi_register_event(rio_vmi->vmi, rio_vmi->sstep_event);
    if (status == VMI_FAILURE)
    {
        eprintf("%s: Failed to register event\n", __func__);
        return false;
    }
~~~

And i have the following problem:
~~~
An event is already registered on this vcpu: 0
~~~

So i think `vmi_step_event` doesn't clear the singlestep event registered on the vcpu after the call.

I modified `xen-emulate-response.c` to reproduce the bug:
https://gist.github.com/Wenzel/e2094c28cce8789b813cff4b64b9acb4

Result:
~~~
sudo ./examples/xen-emulate-response winxp 0x8057a1a0
LibVMI init succeeded!
Waiting for events...
Waiting for events...
Waiting for events...
Waiting for events...
Waiting for events...
Waiting for events...
Waiting for events...
Waiting for events...
Waiting for events...
PAGE ACCESS: --x for GFN 57a (offset 0001a0) gla 000000008057a1a0 (vcpu 0)
Enabling single step
Disabling memevent on page 0x57a in view 0: success
An event is already registered on this vcpu: 0
Finished with test.
Destroying memaccess on gfn events
Destroying memaccess generic events
Destroying register events
Destroying MSR events
Destroying singlestep events
Destroying interrupt events
Destroying clear events
~~~

Can you confirm ?
Thanks !

**Comment by tklengyel** [comment]
The `vmi_step_event` API is fairly fragile and it's use is not recommended anymore. It should be deprecated.

**Comment by Wenzel** [comment]
Ok, got it.

Any idea of how to singlestep inside an event callback ?
~~~C
static event_response_t cb_on_int3(vmi_instance_t vmi, vmi_event_t *event){
    ...
    // singlestep once
    make_single_step(vmi, event->vcpu_id, 1);
    ....
}
~~~

~~~C
bool make_single_step(vmi_instance_t vmi, int vcpu_id, int nb_steps)
{
    vmi_event_t ss_event;
    status_t status;

    // prepare single step
    memset(&ss_event, 0, sizeof(vmi_event_t));
    ss_event.version = VMI_EVENTS_VERSION;
    ss_event.type = VMI_EVENT_SINGLESTEP;
    ss_event.callback = cb_on_make_sstep;
    ss_event.ss_event.enable = 1;
    SET_VCPU_SINGLESTEP(ss_event.ss_event, vcpu_id);
    // register event
    status = vmi_register_event(vmi, &ss_event);
    if (VMI_FAILURE == status)
    {
        eprintf("%s: registering single step event failed\n", __func__);
        return false;
    }
    // listen
    for (int counter = 1; counter <= nb_steps; counter++)
    {
        eprintf("%s: step %d, Listening on VMI events...(%d)\n", __func__, counter, vmi_are_events_pending(vmi));
        status = vmi_events_listen(vmi, 1000);
        if (VMI_FAILURE == status)
        {
            eprintf("%s: Listening failed\n", __func__);
            return false;
        }
    }
    // clear event
    status = vmi_clear_event(vmi, &ss_event, NULL);
    if (VMI_FAILURE == status)
    {
        eprintf("%s: fail to clear event\n", __func__);
        return false;
    }
    return true;
}
~~~

Because the `vmi_events_listen` returns immediately and my callback is not being called. :thinking: 
I was wondering is it was because i'm already inside an event callback, and the VCPU are paused ?
Or if i made a mistake somewhere ?

Thank you.

**Comment by Wenzel** [comment]
I continue investigating this, using a memory event, and trying to singlestep once inside the callback:
[Gist](https://gist.github.com/Wenzel/25530c175111a834a959fab2ca8bca26)

i unregistered the memory event, to relax the permissions and setup my singlestep once, and tried to singlestep.

output:
~~~
sudo ./examples/singlestep-in-callback winxp NtOpenFile
**The running Xen version is 4.10
**The running Xen version is 4.10
**set vm_type HVM
--xen: setup live mode
--xen_get_memory_pfn success on pfn=0x304
--xen_get_memory_pfn success on pfn=0x308
--xen_get_memory_pfn success on pfn=0x318
--xen_get_memory_pfn success on pfn=0x40
--xen_get_memory_pfn success on pfn=0x307
--xen_get_memory_pfn success on pfn=0x54d
--xen_get_memory_pfn success on pfn=0x563
--xen_get_memory_pfn success on pfn=0x63c4
LibVMI init succeeded!
--xen_get_memory_pfn success on pfn=0x6a00
--xen_get_memory_pfn success on pfn=0x6983
--Done Setting memaccess on GPFN: 1402
Waiting for events...
--Waiting for xen events...(500 ms)
Waiting for events...
--Waiting for xen events...(500 ms)
Waiting for events...
--Waiting for xen events...(500 ms)
Waiting for events...
--Waiting for xen events...(500 ms)
Waiting for events...
--Waiting for xen events...(500 ms)
Waiting for events...
--Waiting for xen events...(500 ms)
Waiting for events...
--Waiting for xen events...(500 ms)
Waiting for events...
--Waiting for xen events...(500 ms)
Waiting for events...
--Waiting for xen events...(500 ms)
Waiting for events...
--Waiting for xen events...(500 ms)
--Caught mem access event!
PAGE ACCESS: --x for GFN 57a (offset 0001a0) gla 000000008057a1a0 (vcpu 0)
clear mem event
register single step
--Starting single step on domain 60
--Setting MTF flag on vcpu 0
Enabling single step
make_single_step: step 1, Listening on VMI events...(0)
--Waiting for xen events...(1000 ms)
make_single_step: step 2, Listening on VMI events...(0)
--Waiting for xen events...(1000 ms)
make_single_step: step 3, Listening on VMI events...(0)
--Waiting for xen events...(1000 ms)
make_single_step: step 4, Listening on VMI events...(0)
--Waiting for xen events...(1000 ms)
make_single_step: step 5, Listening on VMI events...(0)
--Waiting for xen events...(1000 ms)
clear singlestep event
register mem event
An event is already registered on this page: 1402
make_single_step: registering event failed
--Finished handling event.
Cannot clear unknown event: 0
Finished with test.
--Shutting down single step on domain 60
--Removing MTF flag from vcpu 0
--Shutting down single step on domain 60
--Removing MTF flag from vcpu 0
Destroying memaccess on gfn events
Destroying memaccess generic events
Destroying register events
Destroying MSR events
Destroying singlestep events
Destroying interrupt events
Destroying clear events
~~~

As you can see, my singlestep callback  `cb_on_make_sstep` is not being called.

So i guess it's just not possible ?
I have to get out of the initial mem_event callback, and toggle the singlestep using an `event_response_t` ?

Thanks.

**Comment by tklengyel** [comment]
Well, you interrupt the loop in the mem cb https://gist.github.com/Wenzel/25530c175111a834a959fab2ca8bca26#file-singlestep-in-callback-c-L126, so how do you expect for events after that to be delivered?

**Comment by tklengyel** [comment]
Also, you are allocating the `vmi_event_t` structure on the stack in your event callback, which is going to go away as soon as the function pops. That's going to lead to a segfault and/or some other spectacular crash when you get an actual event.

**Comment by tklengyel** [comment]
Also, ough, you are calling `vmi_events_listen` again in your callback, that's not going to work. That function can only be called from one place at a time since its not reentrant.

**Comment by Wenzel** [comment]
> Well, you interrupt the loop in the mem cb https://gist.github.com/Wenzel/25530c175111a834a959fab2ca8bca26#file-singlestep-in-callback-c-L126, so how do you expect for events after that to be delivered?

I was trying to recreate the `vmi_step_event` on my own, but i guess it's just not possible to continue the VM execution since the callback is blocking it anyway.

> Also, you are allocating the vmi_event_t structure on the stack in your event callback, which is going to go away as soon as the function pops.

Yes, the structure was supposed to be used during the context of the function, so no need tor a heap.

> Also, ough, you are calling vmi_events_listen again in your callback, that's not going to work. That function can only be called from one place at a time since its not reentrant.

Okay, got it.

I worked my way on this, `r2vmi` now has support for software breakpoints.

Thanks for your help @tklengyel.

**Comment by tklengyel** [comment]
Dealing with dynamically created events can be tricky. For the most part you just have to allocate them on the heap and specify what function to call to free the associated memory when calling `vmi_clear_event`. Even then, for multi-vCPU systems you can have any number of events queued so just because you clear an event doesn't mean you will stop receiving them right away. And then of course your system always have to keep track of what events are registered as you can't register twice for the same event.
