### ISSUE TITLE
Failed to read port from event channel

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#694]
Hi everyone

still working on **pyvmidbg**, and I got a new error that I never had before with Xen.
Usually, after I stopped listening to VMI events, I'm [clearing the queue](https://github.com/libvmi/libvmi/blob/master/libvmi/events.h#L753) by issuing a call to `vmi_events_listen()` with `timeout = 0`:
~~~Python
    def action_singlestep(self):
        cb_data = {
            'interrupted': False
        }

        def cb_on_sstep(vmi, event):
            self.log.debug('singlestepping')
            vmi.pause_vm()
            cb_data['interrupted'] = True
        # unregister sstep_recoil
        self.ctx.vmi.clear_event(self.ss_event_recoil)

        num_vcpus = self.ctx.vmi.get_num_vcpus()
        ss_event = SingleStepEvent(range(num_vcpus), cb_on_sstep)
        self.ctx.vmi.register_event(ss_event)

        self.ctx.vmi.resume_vm()
        while not cb_data['interrupted']:
            self.ctx.vmi.listen(1000)

  -->   self.ctx.vmi.listen(0)
        self.ctx.vmi.clear_event(ss_event)

        # reregister sstep_recoil
        self.ctx.vmi.register_event(self.ss_event_recoil)
~~~

This time, this call doesn't return for no clear reason.
When I `CTRL-C`, i get a Python backtrace and the following error:
`VMI_ERROR: Failed to read port from event channel`
which corresponds to:
https://github.com/libvmi/libvmi/blob/master/libvmi/driver/xen/xen_events.c#L1820

Any idea what's happening ? :thinking: 

xen_version            : 4.11.1 (distro package)
Fedora 29

Thanks !

**Comment by smaresca** [comment]
What's errno at that point?

**Comment by tklengyel** [comment]
That error message should be turned into a debug warning. It's benign. When calling listen with a 0 time-out it now will try to unmask any pending event-channel ports. This time you didn't have any pending events so there was simply nothing to unmask.

**Comment by Wenzel** [comment]
So why the call was blocking in your opinion ?
It should be instant and return immediately after checking that were was nothing to unmask ?
I can try to increase libvmi debug logs verbosity, see if it reveals something.

**Comment by tklengyel** [comment]
I don't see anything that would block on that path. If you get that error message it will immediately return with a VMI_FAILURE and that trickles back to the caller straight through.

**Comment by tklengyel** [comment]
@Wenzel were you running with safety checks enabled or disabled? Also, try with PR #695

**Comment by Wenzel** [comment]
I added a few debug statements, and enabled all debug messages in libvmi
~~~Python
        self.ctx.vmi.resume_vm()
        while not cb_data['interrupted']:
            self.ctx.vmi.listen(1000)

        self.log.debug('listen(0)')
        self.ctx.vmi.listen(0)
        self.log.debug('clear_event')
        self.ctx.vmi.clear_event(ss_event)
~~~

output:
~~~
INFO:client-37406:new packet: b'vCont;s:0;c:0'
INFO:root:command v: V_FEATURES
Disabling single step on vcpu: 0
--Removing MTF flag from vcpu 0
--Shutting down single step on domain 1
--Removing MTF flag from vcpu 0
--Starting single step on domain 1
--Setting MTF flag on vcpu 0
Enabling single step
--Waiting for xen events...(1000 ms)
DEBUG:client-37406:singlestepping
DEBUG:client-37406:listen(0)



~~~

So the execution is indeed blocked by listen(0)

and if I `CTRL-C`, i get the error message
~~~
^CVMI_ERROR: Failed to read port from event channel
INFO:root:resuming VM execution
--Shutting down single step on domain 1
--Removing MTF flag from vcpu 0
Destroying memaccess on gfn events
Destroying memaccess generic events
Destroying register events
Destroying MSR events
Destroying singlestep events
Destroying interrupt events
Destroying clear events
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/vagrant/pyvmidbg/vmidbg/main.py", line 44, in <module>
    main()
  File "/vagrant/pyvmidbg/vmidbg/main.py", line 41, in main
    server.listen()
  File "/vagrant/pyvmidbg/vmidbg/gdbserver.py", line 39, in listen
    client.handle_rsp()
  File "/vagrant/pyvmidbg/vmidbg/gdbstub.py", line 166, in handle_rsp
    self.call_handler(packet_data)
  File "/vagrant/pyvmidbg/vmidbg/gdbstub.py", line 181, in call_handler
    handled = handler(cmd_data)
  File "/vagrant/pyvmidbg/vmidbg/libvmistub.py", line 439, in v_features
    self.action_singlestep()
  File "/vagrant/pyvmidbg/vmidbg/libvmistub.py", line 470, in action_singlestep
    self.ctx.vmi.listen(0)
  File "/usr/local/lib64/python3.7/site-packages/libvmi/libvmi.py", line 893, in listen
    status = lib.vmi_events_listen(self.vmi, timeout)
KeyboardInterrupt
~~~

**Comment by tklengyel** [comment]
Well, that's certainly odd that its blocking on your system. I suspect it may actually be your kernel that's the culprit here. What are you running on?

**Comment by Wenzel** [comment]
latest on Fedora 29: `4.19.10-300.fc29.x86_64`
why do you think the kernel is involved ?

**Comment by tklengyel** [comment]
Because it's a system call to the Xen kernel driver that is blocking when it really shouldn't. But it's not kernel version specific, it happens whenever that system call is issued without a prior `poll`. I would say it's a bug in the Xen kernel driver.

**Comment by Wenzel** [comment]
Confirmed, it works now, thank you !
