### ISSUE TITLE
Syscall and VMI Failure

### ISSUE THREAD

**Issue by yguseto** [libvmi/libvmi#698]
While event-example running, it cant give syscall output.
Error is : "Could not install sysenter syscall handler." 
What will i do?

Xen version : 4.9.2
Ubuntu 18.04 LTS

**Comment by tklengyel** [comment]
FYI the examples are there to illustrate the use of the LibVMI api. The examples may require tweaking and adjustments to work for your target.

**Comment by yguseto** [comment]
I tried 2 different OS (W8, W10) 
I got same error and debug output

**Comment by ultrapikachu** [comment]
Hi.
I have the same problem. In xen 4.9 and 4.11 libvmi throw same error.
VM os : w7 32bit 

I use virt-manager to create machine on xen , could this be related to the problem?

**Comment by yguseto** [comment]
@tklengyel can you help me? 
What can i do to work successfully?

**Comment by tklengyel** [comment]
The `event-example` has been buggy and unreliable for a while. It is only useful as an example to using the API, not as a tool by itself.

**Comment by yguseto** [comment]
I know it but when we try catch syscall events , we need use same functions from libvmi.
So if we call vmi_register_event, we will get the same error directly.
"An event is already registered on this page : 0" the error coming from events.c 
What we will do in this situation?

**Comment by tklengyel** [comment]
Well, it sounds like there is already an event registered on the page. You can only register one event for a given page. You will need to first clear the previous even that was registered there to be able to add a new one.

**Comment by yguseto** [comment]
Yes it's true but the page every time same and we are using vmi_clear_event to clear event however, the situation is the same.
In addition event-example also does clear event.

**Comment by tklengyel** [comment]
Perhaps forgo adding the first event in the first place if you don't need it.

**Comment by tklengyel** [comment]
Also, you can't clear and then register a new event at the same time in the callback of the event you are trying to clear. You would need to use `vmi_swap_events` in that scenario.

**Comment by yguseto** [comment]
Do you have a chance to show on the event-example?
or do you have a chance to look at the event-example?

Shortly before i looked python wrapper example ( reg-access)
both workflows are the same and in python can enter syscall. 
I couldn't solve the real problem

**Comment by tklengyel** [comment]
I'll try to take a look at `event-example` when I have some time.

**Comment by yguseto** [comment]
Thank you.

**Comment by ultrapikachu** [comment]
@tklengyel I tried with new code. It's work but sometime it throw
"Could not find EPROCESS struct for pgd"

**Comment by tklengyel** [comment]
Keep in mind that it is designed to trace sysca of a Linux VM and that it is not very good at it. As I said before, consider it only an illustration of the API use, not of actual functionality.

**Comment by tklengyel** [comment]
You need to review and understand how `poll` works. http://man7.org/linux/man-pages/man2/poll.2.html

**Comment by yguseto** [comment]
Can you a little more details?
I cant understand connection with vm
