### ISSUE TITLE
sysenter_ip is zero

### ISSUE THREAD

**Issue by dscdo** [libvmi/libvmi#706]
I was trying simple things with libvmi and i writed a memevent tracer but my sysenter_eip zero every time?
What's the main reason of situation?

**Comment by Wenzel** [comment]
If you don't show us your code or anything more to look at, we can't exactly help you here :)

**Comment by dscdo** [comment]
I'm using this
> vmi_get_vcpureg(vmi, &sysreg, SYSENTER_EIP, 0);

I can read LSTAR and CSTAR but i cant get value of sysenter.

**Comment by tklengyel** [comment]
This has already been answered: https://groups.google.com/forum/m/#!topic/vmitools/Vp6DYRUYIiY

**Comment by dscdo** [comment]
I do not fully understand. Actually i want catch all syscall activity on target vm
With using MSR_LSTAR can i do it?
@tklengyel
