### ISSUE TITLE
**failed to determine KASLR offset on ARM32 Machine

### ISSUE THREAD

**Issue by mckuok** [libvmi/libvmi#715]
I received the following error when I tried to call `vmi-process-list <VM_NAME>`

```
**The running Xen version is 4.11
--found Xen
LibVMI Version 0.13.0
LibVMI Driver Mode 0
**The running Xen version is 4.11
--completed driver init.
--got id from name (debian-installer --> 21)
**set image_type = debian-installer
--xen: setup live mode
**set allocated_ram_size = ffe4000, max_physical_address = 0x50000000
Found ARM32 pagemode
--looking for config file at /home/mckuok/domU/debian/libvmi.conf
--looking for config file at /home/mckuok/etc/libvmi.conf
--looking for config file at /root/etc/libvmi.conf
--looking for config file at /etc/libvmi.conf
**set os_type to Linux.
--ARM AArch32 PTLookup: vaddr = 0xffffffff82412480, dtb = 0x000000004000406a
--MEMORY cache set 0x40006000
--xen_get_memory_pfn success on pfn=0x40006
--ARM AArch32 PTLookup: fld_location = 0x40006090
--ARM AArch32 PTLookup: fld_value = 0x0
--ARM PTLookup: PA = 0x0
--ARM AArch32 PTLookup: vaddr = 0xffffffff82412480, dtb = 0x000000004000506a
--MEMORY cache hit 0x40006000
--ARM AArch32 PTLookup: fld_location = 0x40006090
--ARM AArch32 PTLookup: fld_value = 0x0
--ARM PTLookup: PA = 0x0
**failed to determine KASLR offset
Failed to init LibVMI library.
```
I suspect that it has to do with the rekall profile not being created correctly, as I was having trouble creating one for `Linux version 4.9.0-8-armmp (debian-kernel@lists.debian.org)`. I was using one created on an `amd64 4.15.0-43-generic` machine instead ..... (I know, terrible). Can someone confirm that the KASLR offset has to do with the profile?

**Comment by mckuok** [comment]
https://github.com/google/rekall/issues/478

**Comment by tklengyel** [comment]
It most likely is, the rekall profile has to match exactly the kernel version you are running with. Try perhaps the linux-offset-finder tool in the libvmi repo?

**Comment by mckuok** [comment]
I was able to generate the offsets using the linux-offset-finder tool,
```
debian {
    ostype = "Linux";
    sysmap = "[insert path here]";
    linux_name = 0x46c;
    linux_tasks = 0x2d8;
    linux_mm = 0x300;
    linux_pid = 0x380;
    linux_pgd = 0x20;
 }
```
From reading the README of the `rekall/tools/linux`, the system map file is generated by the command `sudo make profile`, and that is throwing an error on my system of `Linux version 4.9.0-8-armmp`. Any recommendation?
