### ISSUE TITLE
Compiling on arm64 with cmake

### ISSUE THREAD

**Issue by scorpionzezz** [libvmi/libvmi#726]
Hi,

I tried to compile libvmi with cmake on arm64, and I got following error:

> -- Could NOT find LibvmiRequest (missing:  LibvmiRequest_INCLUDE_DIR) 
CMake Error at cmake/modules/DetectArchitecture.cmake:15 (message):
  Undetect architecture aarch64 to be configured in config.h.in
Call Stack (most recent call first):
  CMakeLists.txt:26 (include)
-- Configuring incomplete, errors occurred!
See also "/mnt/test/libvmi/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/test/libvmi/build/CMakeFiles/CMakeError.log".

Cheers!

**Comment by Wenzel** [comment]
Hi @scorpionzezz ,
i wrote the `DetectArchitecture` cmake module based on internet research, i had no ARM processor to test it :)
As you can see, the error quite trivial to fix:
https://github.com/libvmi/libvmi/blob/master/cmake/modules/DetectArchitecture.cmake#L15

Can you make a PR ?
Thanks

**Comment by scorpionzezz** [comment]
Hi @Wenzel 

I tried to change arm64 to "aarch64" and the "cmake .." works fine. But, then when I run "make"

>/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S: Assembler messages:
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:32: Error: unknown mnemonic `push' -- `push %rbx#rbx'
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:33: Error: unknown mnemonic `movq' -- `movq %rdx,%r8'
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:34: Error: unknown mnemonic `movq' -- `movq $1073746'
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:35: Error: unknown mnemonic `cpuid' -- `cpuid'
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:36: Error: unknown mnemonic `movq' -- `movq %rbx,(%r'
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:37: Error: unknown mnemonic `movq' -- `movq %rcx,(%r'
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:38: Error: unknown mnemonic `movq' -- `movq %rdx,(%r'
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:39: Error: unknown mnemonic `pop' -- `pop %rbx'
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:45: Error: operand 1 must be an integer register -- '
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:46: Error: unknown mnemonic `vmcall' -- `vmcall'
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:52: Error: operand 1 must be an integer register -- '
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:53: Error: unknown mnemonic `vmcall' -- `vmcall'
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:54: Error: unknown mnemonic `movq' -- `movq %rdi,(%r'
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:60: Error: operand 1 must be an integer register -- '
/mnt/test/libvmi/libvmi/driver/bareflank/hypercall.S:61: Error: unknown mnemonic `vmcall' -- `vmcall'


Sorry I'm not really familiar with CMAKE, how to disable the bareflank support?

Cheers!

**Comment by Wenzel** [comment]
@scorpionzezz run `cmake -DENABLE_BAREFLANK=OFF ..`
Options are declared here:
https://github.com/libvmi/libvmi/blob/master/CMakeLists.txt#L44

Or you can use the ncurses gui with `ccmake .` (in the build directory)

**Comment by scorpionzezz** [comment]
@Wenzel  Alright, confirmed that I use 

> cmake -DENABLE_BAREFLANK=OFF -DENABLE_KVM=OFF ..

and all compiled well. Should I make the PR? I mean you can just add the aarch64 to the detectarchitecture file :+1: 

Cheers!

**Comment by Wenzel** [comment]
@scorpionzezz thanks for confirming

> Should I make the PR?

I would prefer, since you have an ARM processor to verify the result.

**Comment by scorpionzezz** [comment]
@Wenzel 

done :)

**Comment by scorpionzezz** [comment]
merged
