### ISSUE TITLE
Enable check build dependency only when testing is enabled

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#745]
related to #744 

Testing option is enabled by default:
https://github.com/libvmi/libvmi/blob/master/CMakeLists.txt#L56

check is added here as a dependency:
https://github.com/libvmi/libvmi/blob/master/tests/CMakeLists.txt#L1

The fix should be to disable testing by default.
What do you think @tklengyel ?

**Comment by tklengyel** [comment]
sgtm
