### ISSUE TITLE
Configure multiple Rekall profiles in a LibVMI entry

### ISSUE THREAD

**Issue by Wenzel** [libvmi/libvmi#756]
Hi,

This is a feature request.
I would like to be able to configure multiple rekall profiles for a given libvmi entry and domain.

The problem i'm facing is simple, I need to find the virtual address for the symbol `RtlUserThreadStart`, in the `ntdll.dll` library, always mapped on Windows.

The use case was to intercept thread creation on Windows, since the last part of their initialization is done in `ntdll`, which is loading the libraries in the address space, and jumping to the entrypoint.

Therefore i would like to extract its profile via Rekall, and configure it in LibVMI.

-> Do you have already thought about this problem ?
-> How do you see LibVMI handling this use case ?

**Comment by tklengyel** [comment]
LibVMI only needs a rekall profile for the kernel. There are no functions within LibVMI that need any of the RVAs from `ntdll.dll`. The only thing you need from LibVMI is to give you the base address where `ntdll.dll` is loaded, then you can find the function addresses by reading the RVA out of the profile yourself. You don't need LibVMI for that.

**Comment by tklengyel** [comment]
Here is an example from DRAKVUF https://github.com/tklengyel/drakvuf/blob/master/src/plugins/clipboardmon/clipboardmon.cpp#L269

**Comment by Wenzel** [comment]
I get your point.
The thing is that i was thinking of Libvmi as an abstraction layer to the system i'm inspecting.

Therefore, as a developer using Libvmi, i would like to rely on it to inspect something else than the kernel.

And if you are not convinced, think about DRAKVUF's command line at the moment:
~~~C
                "\t -w, --rekall-wow <rekall profile>\n"
                "\t                           The Rekall profile for WoW64 NTDLL\n"
#ifdef ENABLE_PLUGIN_CLIPBOARDMON
                "\t -W, --rekall-win32k <rekall profile>\n"
                "\t                           The Rekall profile for win32k.sys\n"
#endif
                "\t --rekall-sspicli <rekall profile>\n"
                "\t                           The Rekall profile for sspicli.dll\n"
                "\t --rekall-kernel32 <rekall profile>\n"
                "\t                           The Rekall profile for kernel32.dll\n"
                "\t --rekall-kernelbase <rekall profile>\n"
                "\t                           The Rekall profile for KernelBase.dll\n"
                "\t --rekall-wow-kernel32 <rekall profile>\n"
                "\t                           The Rekall profile for SysWOW64/kernel32.dll\n"
                "\t --rekall-ntdll <rekall profile>\n"
                "\t                           The Rekall profile for ntdll.dll\n"
                "\t --rekall-iphlpapi <rekall profile>\n"
                "\t                           The Rekall profile for iphlpapi.dll\n"
#ifdef ENABLE_PLUGIN_WMIMON
                "\t --rekall-mpr <rekall profile>\n"
                "\t                           The Rekall profile for mpr.dll\n"
                "\t --rekall-ole32 <rekall profile>\n"
                "\t                           The Rekall profile for ole32.dll\n"
                "\t --rekall-wow-ole32 <rekall profile>\n"
                "\t                           The Rekall profile for SysWOW64/ole32.dll\n"
#endif
~~~

The more plugins you will have on Drakvuf, the more profiles you have to specify on the command line.

Now if i'm a malware analyst, and i'm using drakvuf successively on Windows 7, Windows 8, and WIndows 10, i will have a **difficult user experience**, switching from a set rekall profiles to another one, and having to specify all of them on the command line.

That's why i think it makes more sense to write them only once in the configuration file, and just rely on libvmi to do the association between a domain and it's profiles.

**Comment by tklengyel** [comment]
I don't see the value adding that to LibVMI when the library itself doesn't need any of these profiles. You could easily replace having those files defined in a shell script that passes the required arguments to the tool that needs it. Or create another wrapper around libvmi that keeps track of those profiles for you. Really, anything but adding complexity to an already complex library when it's not needed. So it's a -1 from me.

**Comment by Wenzel** [comment]
Alright, thanks for your reply.
