### ISSUE TITLE
Cannot compile in Arch Linux

### ISSUE THREAD

**Issue by ssentanoe** [libvmi/libvmi#771]
Hi, 

I wanted to compile libvmi in Arch Linux to test my new bareflank driver, so I compiled it with
`cmake .. -DENABLE_XEN=OFF` 
and I got these output:
```
-- Could NOT find LibvmiRequest (missing: LibvmiRequest_INCLUDE_DIR) 
-- Could NOT find Xen (missing: Xen_INCLUDE_DIR) 
-- Could NOT find Xenstore (missing: Xenstore_INCLUDE_DIR) 
-- Could NOT find Libvirt (missing: Libvirt_LIBRARY Libvirt_INCLUDE_DIR) 
CMake Error at libvmi/CMakeLists.txt:112 (set):
  set given invalid arguments for CACHE mode.


CMake Warning at libvmi/CMakeLists.txt:113 (message):
  Cannot find JSON or Libvirt: disabling KVM driver


-- Found Doxygen: /usr/bin/doxygen (found version "1.8.15") found components:  doxygen dot 
--  ↳ Compiler     → /usr/bin/cc
--  ↳ C Flags      →  -Wall -Wextra
--  ↳ Prefix       → /usr/local
--  ↳ Build        → 

```

any idea what can I do? or should I install libvirt?
cheers!

**Comment by Wenzel** [comment]
@ssentanoe  did you solved your problem ?

I think there is a real issue with the build system.
I don't know why it wasn't triggered before.

**Comment by ssentanoe** [comment]
Hi @Wenzel 
so yesterday I talked with @tklengyel , but I just tried with your latest patch, and it works with `cmake .. -DENABLE_XEN=OFF -DENABLE_KVM=OFF` and I made a new pull request, the bareflank flag is missing.
