### ISSUE TITLE
Implementing vmi_toggle_single_step_vcpu

### ISSUE THREAD

**Issue by mtarral** [libvmi/libvmi#815]
Hi,

I'm following up on an old issue I had regarding the API, where I wanted to control singlestepping without `TOGGLE_SINGLESTEP` callback response.

In `libvmi/events.h` an API already exists: `vmi_stop_single_step_vcpu`, but
the `start` API is missing.

As we already discussed this [before](https://172.255.51.119/xen/devel/550756), you recommended me to implement it, and to merge both of them in a single API:

Which I did:
~~~C
status_t
vmi_toggle_single_step_vcpu(
    vmi_instance_t vmi,
    vmi_event_t* event,
    uint32_t vcpu,
    bool enabled)
{
#ifdef ENABLE_SAFETY_CHECKS
    if (!vmi || !event)
        return VMI_FAILURE;

    if (!(vmi->init_flags & VMI_INIT_EVENTS))
        return VMI_FAILURE;
#endif

    if (enabled) {
        SET_VCPU_SINGLESTEP(event->ss_event, vcpu);

        gint *key = g_malloc0(sizeof(gint));
        if (!key)
            return VMI_FAILURE;

        *key = vcpu;

        if (!g_hash_table_insert(vmi->ss_events, key, event)) {
            g_free(key);
            return VMI_FAILURE;
        }

        return driver_start_single_step(vmi, &event->ss_event);
    } else {
        UNSET_VCPU_SINGLESTEP(event->ss_event, vcpu);

        gint key = vcpu;

        if (!g_hash_table_remove(vmi->ss_events, &key))
            return VMI_FAILURE;

        return driver_stop_single_step(vmi, vcpu);
    }
}
~~~

However I've noticed that it doesn't work as expected.
For example with this code:

~~~C
    memset(&single_event, 0, sizeof(vmi_event_t));
    single_event.version = VMI_EVENTS_VERSION;
    single_event.type = VMI_EVENT_SINGLESTEP;
    single_event.callback = single_step_callback;
    single_event.ss_event.enable = 1;
    SET_VCPU_SINGLESTEP(single_event.ss_event, 0);
    vmi_register_event(vmi, &single_event);
    while (!interrupted ) {
        printf("Waiting for events...\n");
        vmi_events_listen(vmi,500);
    }
    printf("stopping singlestep\n");
    if (VMI_FAILURE == vmi_toggle_single_step_vcpu(vmi, &single_event, 0, false)) {
        fprintf(stderr, "fail to disable sstep\n");
    }
    printf("stopped. VM should be running\n");
    sleep(10);
    printf("starting sstep\n");
    if (VMI_FAILURE == vmi_toggle_single_step_vcpu(vmi, &single_event, 0, true)) {
        fprintf(stderr, "fail to enable sstep\n");
    }
    sleep(1);
    printf("Finished with test.\n");
~~~

When it reaches `stopped. VM should be running`, the MTF flag has been disabled, but the VM is not executing because a singlestep event is waiting for processing on the ring.

Therefore it doesn't work as intended.

@tklengyel: how should we implement this function so that the previous example works as expected ?
Should we clean the ring when we disable MTF ?

Should solve #665

**Comment by tklengyel** [comment]
Yes, the ring always has to be empty before making modifications to already registered events. Clearing events for example is queued and only processed when the ring is guaranteed to be empty and the VM is paused (see https://github.com/libvmi/libvmi/blob/master/libvmi/driver/xen/xen_events.c#L2389). This is to ensure no new event is placed on the ring while we make the modifications.

**Comment by tklengyel** [comment]
What you would have to do in your example code above is pause the vm before `vmi_toggle_single_step_vcpu`, call `vmi_events_listen` again with a timeout 0 to clear the ring, then unpause the vm after `vmi_toggle_single_step_vcpu`

**Comment by tklengyel** [comment]
Also, this code you wrote will likely not work because you are passing in a singlestep event structure with NO vcpus specified (`SET_VCPU_SINGLESTEP(single_event.ss_event, 0);`). Thus any MTF actually reaching LibVMI will have no way to tell what handler to call.

**Comment by mtarral** [comment]
ok, thanks for the reply, I just tested pausing the VM, cleaning the ring, and stopping singlestepping
it works.

Now, I think we should add this (pausing + `vmi_events_listen(vmi, 0)` in the API documentation, otherwise people will likely get confused, and (like me) will open an issue.

**Comment by tklengyel** [comment]
Feel free to add that.
