### ISSUE TITLE
Using g_try_malloc0 instead of g_malloc0 for error handling

### ISSUE THREAD

**Issue by mtarral** [libvmi/libvmi#818]
Hi,

I just learned recently that the `g_malloc0` API cannot fail, since on failure it will generate an `abort()` internally, leaving no option for decent error handling:
https://developer.gnome.org/glib/unstable/glib-Memory-Allocation.html#g-try-malloc0
> Contrast with g_malloc0(), which aborts the program on failure.

As we are [extensively using this API in Libvmi](https://github.com/libvmi/libvmi/search?q=g_malloc0&unscoped_q=g_malloc0), I would recommend that we switch to `g_try_malloc0` if possible.

Furthermore, there are cases in the code where people genuinely check the return value from `g_malloc0`, since they would expect it behaves as `malloc()`...
https://github.com/libvmi/libvmi/blob/f8cfe2545f550e60057017e6d5f2a659a8ccf6c1/libvmi/os/linux/symbols.c#L112

So switching to `g_try_malloc0` and checking the return values seems to be a better option, otherwise we might leave a VM in an unclean state if a call ends up in `abort()`

Thanks

**Comment by tklengyel** [comment]
A PR implementing the switch would be welcome.

**Comment by mtarral** [comment]
Closed by https://github.com/libvmi/libvmi/pull/823
