### ISSUE TITLE
QEMU-KVM Version 2.8 Restriction 

### ISSUE THREAD

**Issue by Vladinuto** [libvmi/libvmi#820]
Hello, 

I'm trying to run LIbVMI on a KVM hypervisor using qemu-kvm, but it seems that LibVMI forces you to use the 2.8 version of qemu. 

With recent updates to qemu, is it necessary to have this condition? And if so, what changes need to be done in order to support newer versions of qemu for kvm ?

Thanks in advance. 

-CR

**Comment by mtarral** [comment]
Hi @Vladinuto,

the 2.8 restriction comes from the fact that the Libvmi community has been maintaining a patch for QEMU to allow a fast memory access on KVM.

this patch hasn't been updated and following the latest versions, as the focus has been on working on a more complete VMI API, provided by [KVM-VMI](https://github.com/KVM-VMI/kvm-vmi).

It's a work in progress, but reading and writing physical memory already works, and we are integrating hardware events ATM.

If you are not afraid of installing a new kernel, QEMU, you should try this.
[KVM-VMI setup Wiki page](https://github.com/KVM-VMI/kvm-vmi/wiki/KVM-VMI-setup)

**Comment by Vladinuto** [comment]
Thanks! Will take a look at KVM-VMI and see if it works with our current set up.

Regards,

-CR
