### ISSUE TITLE
It is possible to monitor memory ranges through events?

### ISSUE THREAD

**Issue by igor4020** [libvmi/libvmi#828]
So, i was trying to monitor **write events** to a certain memory range in the kernel space of the guest machine. Is it possible? I tried using generic memory events and then filtering in the callback but the generic memory event doesn`t seem to work, also when specifing the gfn the region covered by the event is too small.

**Comment by igor4020** [comment]
Okay, i also tried to do that but the range is quite big and i did not have enough memoery to allocate each event. Can you enlighten me about how the generic memory event is supposed to work? and if there`s another way besides creating an event for each gfn in the range?

**Comment by tklengyel** [comment]
You create one `vmi_event_t` that you designate to be a generic handler. Then you use `vmi_set_mem_event` for each of GFNs that you want to monitor. The generic handler's callback is going to be called for each.

**Comment by igor4020** [comment]
Thank you, just one last thing, the vmm _pagetable_id parameter i didn`t quite get what actually is it.

**Comment by igor4020** [comment]
Thank you very much.
