### ISSUE TITLE
What is the most adequate response in a MSR_ANY event response?

### ISSUE THREAD

**Issue by igor4020** [libvmi/libvmi#835]
I'm trying to monitor writes to the MSR_IA32_SYSENTER_CS register using the following code:
``` 
SETUP_REG_EVENT(&msr_event, MSR_ANY, VMI_REGACCESS_W, 0, cb);
msr_event.reg_event.msr = 0x174;
vmi_register_event(vmi, &msr_event);
```
And the following callback:
```
event_response_t cb(vmi_instance_t vmi, vmi_event_t *event)
{
    printf("Caught write to a register\n");
    return 0;
}
```
But this results in a seg fault and crashes the Guest VM when i run in the guest the command:
```
wrmsr 0x174 value

```
My guess it's the event_response return, i tried some macros but to no luck (the print isn't executed though)

**Comment by tklengyel** [comment]
Sending back `0` is the adequate response. If you don't see the print from your callback then it didn't execute and the crash is because of something else.

**Comment by igor4020** [comment]
Okay, thank you a lot, guess i'll wait for the pr to merge though, because the msr-event-example actually crashes my guest and host machine.

**Comment by tklengyel** [comment]
Crashing the host is certainly not a good sign and shouldn't happen even if the tool is buggy. What version of Xen are you running on?

**Comment by igor4020** [comment]
4.13

**Comment by tklengyel** [comment]
It would be valuable if you could get the Xen debug log for when the crash occurs. You would need a serial cable to be attached. I tried it on my build server running Xen 4.13-rc1 and I didn't get a crash but I do see a crash on my laptop.. which doesn't have a serial.

**Comment by tklengyel** [comment]
The host crash should be resolved now.
