### ISSUE TITLE
vmi-win-guid not working for Windows 7 (32 bit)

### ISSUE THREAD

**Issue by icedevml** [libvmi/libvmi#838]
I have a problem with getting a kernel GUID using `vmi-win-guid` on Windows 7 x86. The exact line that is too rigorous is:

https://github.com/libvmi/libvmi/blob/df82b484d4b7a9562dfcf66fe8ea58500e65cbf1/examples/win-guid.c#L88

... after commenting it out it prints out the GUID properly.

Variable values:
```
base_p = 0x2843000
export_header_offset = 0x344000
```

seems like the export header is mapped much further than it was expected.

Windows 7 x86 ISO file of my target:
```
4129a34d796cd49e852f68805976f8cf85325f7a4d1dd656354bbdad3ae3ee27
SW_DVD5_SA_Win_Ent_7_32BIT_English_Full_MLF_X15-70745.ISO
```

I have no clue about the suggested fix. Maybe just remove this check?

**Comment by icedevml** [comment]
@tklengyel

**Comment by tklengyel** [comment]
That safety check can be removed if its no longer accurate. Generally though you want to have some sanity checks on everything you read from the PE header, especially if its malicious. Here it should be fine since this tool is expected to run on a clean VM.

**Comment by icedevml** [comment]
Perhaps the check could be if the RVA doesn't exceed the whole PE. I will make some PR.
