### ISSUE TITLE
To tell if the process is running using the task_struct

### ISSUE THREAD

**Issue by igor4020** [libvmi/libvmi#865]
### **This is the output from the binary that uses libvmi**
![image](https://user-images.githubusercontent.com/51101165/71913546-6e8e7600-3156-11ea-9712-82702993602c.png)
### **Then, the kernel module seems more realible showing some processes that are actually running:**
![image](https://user-images.githubusercontent.com/51101165/71913703-cc22c280-3156-11ea-8d16-9e89abb368af.png)

### **The ***rcu_sched*** task is running ok, but libvmi returns 0 on the on_rq field.**

- I tried doing the analysis with the vm paused and with the vm running, both have the same result: only the swapper task is running.
- I'm doing the field access using the on_rq offset from the kernel module.
- I tried running the libvmi binary multiple times and the same result is what i get.

**Comment by tklengyel** [comment]
Well, if you just randomly pause the VM at some point it's most likely going to be.. idling. So the fact that you only seem to be getting swapper in the runqueue is not that surprising. If you print the same information from a kernel module you are actively interacting with the VM (running insmod I bet) so you will get a different result. I would wager if you keep running your randomly-pausing app you will eventually see some process other then swapper being scheduled. It's just by chance you haven't so far.

**Comment by igor4020** [comment]
Okay, i'll keep trying, i tested without pausing the vm at all, but only the swapper shows again. I also tried running a bash in a infinite loop so it is always executing, but still the swapper is the only one being ran. I'll keep trying.

**Comment by smaresca** [comment]
The task scheduler(s) are very good at their jobs :). There are a variety
of fields which can indicate task state, but observing the desired state
can definitely be a challenge at times.

task->state is another useful member, at times.  See TASK_RUNNING,
TASK_INTERRUPTIBLE, TASK_IDLE, TASK_NEW etc

Creating a custom, 'sacrificial' process that runs a tight loop, sleeps, or
triggers an interrupt is usually my personal approach.

**Comment by igor4020** [comment]
Ok, thank you guys. Suppose it could be a little bug on libvmi but i guess i'm missing something, i'll try the custom process.
