### ISSUE TITLE
LibVMI for Windows 10 doesn't always initialize properly with KPTI enabled

### ISSUE THREAD

**Issue by icedevml** [libvmi/libvmi#897]
From what I've understood, LibVMI's `windows_init` is searching for kernel's virtual address in order to find its Page Global Directory (KPGD) physical location in the next step.

We've encountered some stability problems particularly with Windows 10, that LibVMI randomly gets into trouble finding right kernel VA/KPGD and starts doing a full scan (sometimes even a few different full scans).

I belive this is due to the fact that with KPTI the kernel may not be mapped at all, when we are in usermode and this may confuse the LibVMI search procedure. From what I've experimented, there is a strong correlation between being in user mode and full scans.

A hint may be to detect that we caught the VM in user mode (this snippet is useful for that: https://github.com/libvmi/libvmi/pull/797/files ) and retry until we catch it in a kernel mode. This is however pretty tricky - if there is some program doing simple computations consuming 100% CPU time, then the kernel is active for a small fraction of time and it is really hard to randomly catch it.

/cc @chivay and thanks for help debugging/understanding this

**Comment by icedevml** [comment]
I will try to prepare some PR for tihs.

**Comment by icedevml** [comment]
I will try to prepare some PR for this. I bet some CR3 hook could be leveraged for that purpose?

**Comment by icedevml** [comment]
may be related #736 #757

**Comment by icedevml** [comment]
@tklengyel A little more context about this.

Currently, this:
https://github.com/libvmi/libvmi/blob/55248db8f3492f98dd7cdf68a815b1cc65cfaead/libvmi/os/windows/core.c#L1013

which is a part of:
https://github.com/libvmi/libvmi/blob/be5af9b4d7b6bd8f920b70bac1376c6a0272ac85/libvmi/core.c#L652-L657

is implemented in such way, that it basically:
1. pauses the VM at arbitrary moment
2. looks at the current value of `CR3` (and few other registers) for VCPU 0 https://github.com/libvmi/libvmi/blob/55248db8f3492f98dd7cdf68a815b1cc65cfaead/libvmi/os/windows/core.c#L1067
3. tries to compute all necessary parameters that are required for proper initialization like `ntoskrnl_va` (kernel virtual address), actual `kpgd` etc.

the trick is that now we have Kernel Page Table Isolation, so if LibVMI is out of luck, it will pause the VM in a moment when VCPU 0 is executing the code in user mode. In such case, the kernel will be shadowed and `windows_init` will not succeed no matter how hard it would try. This is another nasty bug that needs to be resolved.

For that reason I was playing with CR3 VM event. I've found the solution that before calling `windows_init`, one may just register a CR3 event and fast forward the VM until it's observed that the `System` process (PID=4) started executing on VCPU 0 (checked via `KPCR` inspection). With such precondition `windows_init()` will always succeed.

Such fix is already implemented in PR #898, but it actually resolves the problem only for `vmi-win-offsets` tool, not for the whole LibVMI. I think about closing this PR and implementing the fix described above as a part of `windows_init()` procedure.

How do you find that?

**Comment by tklengyel** [comment]
> This is another nasty bug that needs to be resolved.

I don't consider that a bug. The whole reason we have separate init functions that enable you to initialize events and paging is so that you can determine yourself when its safe to try to initialize the os specific parts. If you don't want to do that, then LibVMI is just going to do a best-effort which will be a hit-or-miss as you observe. That doesn't make it a bug, that just means you tried to initialize parts of the library when it was not possible to do so. It's up to the user to figure out how to resolve this. I'm against implementing baked-in logic that plays with events and such since events are not uniformly supported on all hypervisors. Plus maintaining said logic is a pain, as OS internals change all the time. Implementing that logic is much better suited to be done on top of the library instead of inside.

**Comment by tklengyel** [comment]
Also, to clarify, I'm only against adding that logic to the library core. It's perfectly fine to add something that implements this logic in `examples` or something under `tools`.

**Comment by icedevml** [comment]
What with DRAKVUF, for instance? Basically it would have to implement the same logic as `vmi-win-offsets` does in PR #898 in order to be resistant to this issue. So maybe `libvmi_extra.h` is the proper place to have such a helper?

**Comment by icedevml** [comment]
Or another option for DRAKVUF is to have some switch that would accept pre-computed LibVMI runtime offsets and then it would be executed like that:

```
drakvuf -d vm_name -r kernel.json --runtime-offsets=$(vmi-win-offsets name vm_name)
```

so `vmi-win-offsets` would be hardened against KPTI and DRAKVUF would just receive all the offsets (KPGD, NTOSKRNL_VA etc.) from the start.

**Comment by icedevml** [comment]
Or even different option. I think the best one.

The part responsible for checking PID based on KPCR:
https://github.com/libvmi/libvmi/blob/7c510b3c903aa71399dafeda98b3cafebfd6d726/examples/win-offsets.c#L85-L146
and this piece of code:
https://github.com/libvmi/libvmi/blob/7c510b3c903aa71399dafeda98b3cafebfd6d726/examples/win-offsets.c#L261-L282

could be some LibVMI helper function. Then the whole CR3 trick would take just a few lines of code on the user side and essentially there will be not much code duplication.

**Comment by tklengyel** [comment]
> What with DRAKVUF, for instance?

That logic would also have to be implemented in there.

> So maybe libvmi_extra.h is the proper place to have such a helper?

I'm against that.

> Or another option for DRAKVUF is to have some switch that would accept pre-computed LibVMI runtime offsets

It does. You can tell DRAKVUF to read the offsets from the `libvmi.conf` file. If you want to pass the offsets via the command line, then that could be implemented quite easily.

**Comment by icedevml** [comment]
Ok thanks for feedback, I will adjust the PR.

**Comment by trapframe** [comment]
Guys,

Not sure if this is the same issue but it looks similar enough, so checking before opening a new one.

Very randomly we got drakvuf stuck during libvmi init.
It happens with our windows 10 VM (build 1903)

Since i cannot apply your fix in the near feature, we disabled KPTI in the VM template using the registry keys to disable spectre and meltdown windows protection.

No effect...

When we have the problem libvmi debug output looks like the one below.

At some point there is the ouput :
```
--searching for process by name: System
```
And then libvmi starts crawling all the physical pages...

Does it looks related to your issue or are we chasing another beast ?

We will test with win7 shortly, and for win10 next time we will have libvmi logs + backtrace taken with gdb

```
_0	1590590931.606185 drakvuf_event_fd_add fd=16
_0	1590590931.606199 size of list=1
_0	1590590931.606213 regenerating event_fds and fd_info_lookup...
_0	1590590931.606224 new event_fd i=0 for fd=16
_0	1590590931.606234 new fd_info_lookup i=0 for fd=16
_0	1590590931.606244 drakvuf_init: adding event_fd done
qspy_04_736	1590590931.623341 init_vmi on domID 736 -> qspy_04
LibVMI Version 0.13.0
LibVMI Driver Mode 0
**The running Xen version is 4.13
--completed driver init.
--got name from id (736 --> qspy_04)
**set image_type = qspy_04
**set vm_type HVM
--xen: setup live mode
--Xen common events interface initialized
--Xen vm_event ABI version: 5
**set allocated_ram_size = 8004b000, max_physical_address = 0xff000000
qspy_04_736	1590590931.625629 init_vmi: initializing vmi done
**set pae = 1
**set pse = 1
**set lme = 1
**IA-32e paging
**sanity checking cr3 = 0x000000000e8ed000
qspy_04_736	1590590931.625840 init_vmi: initializing vmi paging done
**set os_type to Windows.
Rekall profile lookup _KPROCESS DirectoryTableBase: 0x28
** (vmi->page_mode == VMI_PM_IA32E) Entering KPCR register selection loop...
** (vmi->page_mode == VMI_PM_IA32E) => Using kpcr_register_to_use=GS_BASE.
**Trying to init from JSON profile
** Trying kpcr_register_to_use to get KPCR.
** Trying kpcr_find1
Rekall profile: symbol 'KiInitialPCR' not found in $CONSTANTS
Rekall profile: symbol 'KiInitialPCR' not found in $FUNCTIONS
Rekall profile lookup KiInitialPCR (null): 0x1
** Trying kpcr_find2
Rekall profile: symbol 'KiSystemCall64Shadow' not found in $CONSTANTS
Rekall profile lookup KiSystemCall64Shadow (null): 0x34f140
Rekall profile: symbol 'KiSystemCall32Shadow' not found in $CONSTANTS
Rekall profile lookup KiSystemCall32Shadow (null): 0x34ee00
--PTLookup: lookup vaddr = 0xfffff8017521c000
--PTLookup: dtb = 0x000000000e8ed001
--MEMORY cache set 0xe8ed000
--xen_get_memory_pfn success on pfn=0xe8ed
--PTLookup: pml4e_address = 0x000000000e8edf80
--MEMORY cache set 0x5d6000
--xen_get_memory_pfn success on pfn=0x5d6
--PTLookup: pdpte_address = 0x00000000005d6028, pdpte_value = 0x0a000000005d5863
--MEMORY cache set 0x5d5000
--xen_get_memory_pfn success on pfn=0x5d5
--PTLookup: pde_address = 0x00000000005d5d48, pde_value= 0x0000000000000000
--PTLookup: paddr = 0x0000000000000000
** Trying kpcr_find3
Rekall profile: symbol 'KiDivideErrorFault' not found in $CONSTANTS
Rekall profile lookup KiDivideErrorFault (null): 0x1c7100
--PTLookup: lookup vaddr = 0xfffff80178e5b000
--PTLookup: dtb = 0x000000000e8ed001
--MEMORY cache hit 0xe8ed000
--PTLookup: pml4e_address = 0x000000000e8edf80
--MEMORY cache hit 0x5d6000
--PTLookup: pdpte_address = 0x00000000005d6028, pdpte_value = 0x0a000000005d5863
--MEMORY cache hit 0x5d5000
--PTLookup: pde_address = 0x00000000005d5e38, pde_value= 0x0a000000005d4863
--MEMORY cache set 0x5d4000
--xen_get_memory_pfn success on pfn=0x5d4
--PTLookup: pte_address = 0x00000000005d42d8, pte_value = 0x8a0000000705b121
--PTLookup: paddr = 0x000000000705b000
--V2P cache set 0xfffff80178e5b000 -- 0x000000000705b000
--MEMORY cache set 0x705b000
--xen_get_memory_pfn success on pfn=0x705b
--PTLookup: lookup vaddr = 0xfffff80178e5b006
--PTLookup: dtb = 0x000000000e8ed001
--MEMORY cache hit 0xe8ed000
--PTLookup: pml4e_address = 0x000000000e8edf80
--MEMORY cache hit 0x5d6000
--PTLookup: pdpte_address = 0x00000000005d6028, pdpte_value = 0x0a000000005d5863
--MEMORY cache hit 0x5d5000
--PTLookup: pde_address = 0x00000000005d5e38, pde_value= 0x0a000000005d4863
--MEMORY cache hit 0x5d4000
--PTLookup: pte_address = 0x00000000005d42d8, pte_value = 0x8a0000000705b121
--PTLookup: paddr = 0x000000000705b006
--V2P cache set 0xfffff80178e5b006 -- 0x000000000705b006
--MEMORY cache hit 0x705b000
--PTLookup: lookup vaddr = 0xfffff80178e5b008
--PTLookup: dtb = 0x000000000e8ed001
--MEMORY cache hit 0xe8ed000
--PTLookup: pml4e_address = 0x000000000e8edf80
--MEMORY cache hit 0x5d6000
--PTLookup: pdpte_address = 0x00000000005d6028, pdpte_value = 0x0a000000005d5863
--MEMORY cache hit 0x5d5000
--PTLookup: pde_address = 0x00000000005d5e38, pde_value= 0x0a000000005d4863
--MEMORY cache hit 0x5d4000
--PTLookup: pte_address = 0x00000000005d42d8, pte_value = 0x8a0000000705b121
--PTLookup: paddr = 0x000000000705b008
--V2P cache set 0xfffff80178e5b008 -- 0x000000000705b008
--MEMORY cache hit 0x705b000
--PTLookup: lookup vaddr = 0xfffff801753a2000
--PTLookup: dtb = 0x000000000e8ed001
--MEMORY cache hit 0xe8ed000
--PTLookup: pml4e_address = 0x000000000e8edf80
--MEMORY cache hit 0x5d6000
--PTLookup: pdpte_address = 0x00000000005d6028, pdpte_value = 0x0a000000005d5863
--MEMORY cache hit 0x5d5000
--PTLookup: pde_address = 0x00000000005d5d48, pde_value= 0x0000000000000000
--PTLookup: paddr = 0x0000000000000000
Rekall profile lookup _EPROCESS ImageFileName: 0x450
**set os.windows_instance.pname_offset (0x450)
--searching for process by name: System
--MEMORY cache set 0x0
--xen_get_memory_pfn success on pfn=0x0
--MEMORY cache set 0x1000
--xen_get_memory_pfn success on pfn=0x1
--MEMORY cache set 0x2000
--xen_get_memory_pfn success on pfn=0x2
--MEMORY cache set 0x3000
--xen_get_memory_pfn success on pfn=0x3
--MEMORY cache set 0x4000
--xen_get_memory_pfn success on pfn=0x4
--MEMORY cache set 0x5000
--xen_get_memory_pfn success on pfn=0x5
--MEMORY cache set 0x6000
--xen_get_memory_pfn success on pfn=0x6
--MEMORY cache set 0x7000
--xen_get_memory_pfn success on pfn=0x7
--MEMORY cache set 0x8000
--xen_get_memory_pfn success on pfn=0x8
--MEMORY cache set 0x9000
--xen_get_memory_pfn success on pfn=0x9
--MEMORY cache set 0xa000
--xen_get_memory_pfn success on pfn=0xa
--MEMORY cache set 0xb000
```

**Comment by tklengyel** [comment]
Are you passing the KPGD value to DRAKVUF manually (`-k`) or do you rely on LibVMI finding it on it's own?

**Comment by trapframe** [comment]
leaving LIBVMI finding it

**Comment by tklengyel** [comment]
Try running vmi-win-offsets to gather the kpgd value for your VM and pass that in when you run DRAKVUF for a more deterministic initialization. When you leave it up to LibVMI it only does a limited method based on the state of vCPU 0 to try to find the kernel. It's hit-or-miss.

**Comment by icedevml** [comment]
If you want to have a bulletproof setup with Windows 10 then something like this should do the job:

```
drakvuf -k $(vmi-win-offsets --name vm -k) -d vm ... remaining arguments ...
```

The `vmi-win-offsets` command has additional sanity checks to guarantee that it would always succeed finding the proper KPGD value. Then after you pass this value to DRAKVUF, it shouldn't have any startup problems either.

**Comment by tklengyel** [comment]
Arguably it would make sense to just incorporate the logic in vmi-win-offsets to the DRAKVUF initialization so you don't have to init LibVMI twice (once in vmi-win-offsets and once in DRAKVUF). If someone is inclined to write that code, I wouldn't object ;)

**Comment by icedevml** [comment]
It's somewhere on my TODO list already, maybe today/tomorrow I would do that.

**Comment by trapframe** [comment]
That would be a nice feature ;)

Although for bullet proof reliability I will consider the -k option as
using memory snapshot for the VM it can be setup once (until the next
snapshot modification) and give a little extra bit of optimization.

Thanks for the feedback :)
