### ISSUE TITLE
CR3 event cleanup causing VM crash

### ISSUE THREAD

**Issue by icedevml** [libvmi/libvmi#899]
I've got some troubles with CR3 event listening. I remember that we've already been debugging this before in DRAKVUF, but without luck.

This is the minimal example:
https://github.com/libvmi/libvmi/compare/master...icedevml:cr3-debug
this branch is a stripped-off version of my other branch, the most relevant part is:
https://github.com/icedevml/libvmi/blob/5e9f474d0674aa9d7d2e3b74ef98f86a34b9f886/examples/win-offsets.c

It also has hardcoded `VMI_DEBUG` and `ENV_DEBUG` in `configure.ac`.

It takes at most few runs of this program:
```
LD_LIBRARY_PATH=/usr/local/lib examples/vmi-win-offsets name my-test-vm
```
before BSOD is triggered in the guest (usually `PAGE_FAULT_IN_NONPAGED_AREA` but also different ones). BSOD occurs after VMI destruction and cleanup.

This problem blocks #898

**Comment by icedevml** [comment]
@tklengyel Could you take a look at this one? This example is pretty much stripped and this is again some problem with CR3 events.

**Comment by icedevml** [comment]
I've tested experimentally that such mashing before calling `vmi_destroy` (with unpaused VM) is decreasing chance for BSODs:

```cpp
    for (int i = 0; i < 500; i++) {
        vmi_events_listen(vmi, 0);
        vmi_clear_event(vmi, &cr3_event, NULL);
    }
```

guess that guest crashes are related to some race condition that some Xen event is triggered after LibVMI exits and thus it's routed directly to the guest VM(?).

With this "mashing" procedure, sometimes I get:
```
VMI_ERROR: Unhandled register event caught: 0x1
```
this safety check returns `VMI_FAILURE` which causes trap being routed to the guest VM (if I got it right) and crash.

So it seems like clearing CR3 event doesn't take immediate effect in Xen and if we disconnect too early then the trap would leak to the guest and cause crash?

**Comment by tklengyel** [comment]
I've looked at every possible angle I could think of with the CR3 event handling but I don't have a better insight into what's happening. I have stress-tested this many times and what seems to happen is something within the guest - and only Windows - starts leaking memory. If you have task-manager open that shows the memory utilization you will notice it starts to go up steadily before the bsod. On the Xen/LibVMI side the CR3 event is one of the most simple ones. The instruction itself traps to Xen based on the VMCS setting, event is sent to LibVMI, and when its processed Xen emulates it. It is possible its an emulation issue but then we would see it every time not just after the event is disabled. Also, how exactly it leads to the memory leak within the guest is a mystery. I was thinking maybe its a stale TLB issue but even with forced TLB flush in Xen on every CR3 event it still happened. The only clue we have is that this has to do with something on how the event is being disabled.

**Comment by icedevml** [comment]
I will check the task manager, but I think that we are talking about two different issues. This one happens in the same second when LibVMI is de-initialized.

When I disable event and then wait few seconds before LibVMI de-init, sometimes I get this:
```
VMI_ERROR: Unhandled register event caught: 0x1
```

from this code:
```cpp
static
status_t process_register(vmi_instance_t vmi, vm_event_compat_t *vmec)
{
    reg_t convert[] = {
        [VM_EVENT_X86_CR0] = CR0,
        [VM_EVENT_X86_CR3] = CR3,
        [VM_EVENT_X86_CR4] = CR4,
        [VM_EVENT_X86_XCR0] = XCR0
    };

    gint lookup = convert[vmec->write_ctrlreg.index];
    vmi_event_t * event = g_hash_table_lookup(vmi->reg_events, &lookup);

#ifdef ENABLE_SAFETY_CHECKS
    if ( !event ) {
        errprint("Unhandled register event caught: 0x%x\n", vmec->write_ctrlreg.index);
        return VMI_FAILURE;
    }
#endif
```

and in this situation the guest crash is directly caused by LibVMI. When I change `return VMI_FAILURE` to `return VMI_SUCCESS` then the VM doesn't crash anymore o_O

It seems like LibVMI's `process_register` function can be fired even after it's cleared and this causes some confusion.

**Comment by tklengyel** [comment]
When you get the unhandled register event error message that means you called `vmi_clear_event` while the VM was still running. You can only disable events when the VM is paused. If you call `vmi_clear_event` in an event callback the event processing logic makes sure that free event only happens when its safe. If you call `vmi_clear_event` outside the event callback, its up to you to ensure 1) vm is paused 2) all events from the ring are clear before you call `vmi_clear_event`. So I think this may just be an error on your side. This would also not necessarily cause a guest crash, but a hang. Of course if you are running with multi-vCPUs it may be that you are hanging one vCPU (the one that had no handler) and then Windows still running on the other one notices something is wrong and bsods.

**Comment by icedevml** [comment]
Ok but I pause the VM just at the entry to the CR3 callback:
https://github.com/libvmi/libvmi/blob/eefddded5337cf36895d3ebaff32f058bbd82679/examples/win-offsets.c#L83

then I clear the event:
https://github.com/libvmi/libvmi/blob/eefddded5337cf36895d3ebaff32f058bbd82679/examples/win-offsets.c#L166

and then I resume the VM and perform cleanup:
https://github.com/libvmi/libvmi/blob/eefddded5337cf36895d3ebaff32f058bbd82679/examples/win-offsets.c#L390

if this sleep is removed:
https://github.com/libvmi/libvmi/blob/eefddded5337cf36895d3ebaff32f058bbd82679/examples/win-offsets.c#L392

the VM is crashing from time to time after the program exits. With this `sleep(1)` everything works well and stable.

I suppose this is some weird race condition? Of course it only happens with >1 VCPU.

**Comment by tklengyel** [comment]
After you pause you need to check if there are still events pending, process them with vmi_events_listen(vmi, 0); and only after clear the event. If you do that but you still get an event when you resume then thats a bug as it would mean the event wasn't cleared from the VMCS of some vCPUs.

**Comment by icedevml** [comment]
I was trying exactly what you've said but it was not always helping.

I suspect that the event is already queued for some vCPU and it's not cleared properly, thus fired some time after LibVMI destruction, causing BSOD/hang.

**Comment by tklengyel** [comment]
Possible, that would be a bug in Xen. Verify that when the event is cleared it sticks and there are no events trapped to Xen afterwards. You can add some gdprintk's to see if it happens.

**Comment by tklengyel** [comment]
So I can reproduce the guest crash on my end, seems to only trigger when the CR3 event had both vCPUs trap at the same time. What happens then is the callback is issued for both, and if in both callbacks the VM gets paused and vmi_clear_event gets called then the crash occurs. You should only call `vmi_clear_event` once, so when I did:

```
event_response_t cr3_cb(vmi_instance_t vmi, vmi_event_t *event)
{
    printf("vCPU %u CR3!\n", event->vcpu_id);
    if ( !find_pid4_success )
    {
        find_pid4_success = 1;
        vmi_pause_vm(vmi);
        vmi_clear_event(vmi, event, NULL);
    }
    return 0;
}
```

I don't see the crash anymore. Without that `if ( !find_pid4_success )` gate I did. So seems like calling the clear event twice is what seems to be causing some issue. I think we are one step closer to figuring this out ;)

**Comment by tklengyel** [comment]
So what's odd is that LibVMI has logic that checks whether the same event is being queued for clearing twice, to ensure each event only gets cleared once. Somehow its not working and it gets queued twice:

```
vCPU 0 CR3!
Queueing event 5646c920b140 for clearing. Should be 0x5646c920b140
vCPU 1 CR3!
Queueing event 5646c920b140 for clearing. Should be 0x5646c920b140
```

Somehow when using the event pointer as the key in the ghashtable it doesn't work.

**Comment by icedevml** [comment]
Interesting. Going to check this within few hours, right now I'm afk.

**Comment by icedevml** [comment]
Also, this might help to debug related issue https://github.com/tklengyel/drakvuf/issues/662

**Comment by tklengyel** [comment]
Indeed. I hope this is the same issue.

**Comment by tklengyel** [comment]
So it starts to look like to me that the problem is if you have the VM paused while all vCPUs are trapped while executing mov-to-cr3. If you keep the VM in a paused state for too long you get a crash. If you resume fast enough you don't get a crash. My bet is that there is a watchdog in Windows 10 that times out in that situation.

**Comment by tklengyel** [comment]
For some reason it seems like one of the vCPUs may get stuck in a paused state. If I just add a couple `vmi_resume_vm(vmi)` at the end I never get a crash.

**Comment by tklengyel** [comment]
Hm, nope, it just seems to reduce the frequency of the crash but it can still happen. I'm running out of ideas :)

**Comment by icedevml** [comment]
Btw. I've switched to Windows 7 x64 because I can still reproduce the crash there and it behaves much less randomly than Windows 10 (subjective opinion).

**Comment by icedevml** [comment]
I made sure that:
* event clearing is done from callback
* I do it only once
* the VM is paused before `vmi_clear_event`

No luck tho. I'm still digging into this.

**Comment by tklengyel** [comment]
Btw this might also be relevant, on the Xen dmesg output I see: `VIRIDIAN CRASH 50`. So perhaps it might be worth trying to boot these VMs with `viridian = 0`

**Comment by tklengyel** [comment]
Can you try applying this patch to Xen and see if it does anything? Seems to me it might be reducing the frequency of the crashes. Although I still saw one O.o

```
diff --git a/xen/arch/x86/monitor.c b/xen/arch/x86/monitor.c
index bbcb7536c7..e59f3ad529 100644
--- a/xen/arch/x86/monitor.c
+++ b/xen/arch/x86/monitor.c
@@ -195,7 +195,10 @@ int arch_monitor_domctl_event(struct domain *d,
             struct vcpu *v;
             /* Latches new CR3 or CR4 mask through CR0 code. */
             for_each_vcpu ( d, v )
+            {
                 hvm_update_guest_cr(v, 0);
+                hvm_asid_flush_vcpu(v);
+            }
         }
 
         domain_unpause(d);

**Comment by tklengyel** [comment]
Well, never mind. I still see the crash. I've verified that after the CR3 event is disabled nothing traps to Xen. Only the events we see in LibVMI are trapped to Xen. I also checked that at the end the event is disabled properly and in every case the last state Xen sees for the event is that it's disabled with no events actually trapping to Xen. So I'm afraid we are still no closer to the root cause.

**Comment by icedevml** [comment]
Since this `sleep(1)` between CR3 event clearing and `vmi_destroy` definitely helps, I belive that we should just add additional step in the sequence:

1. In callback: Pause the VM and clear CR3 event.
2. In main code: Resume the VM
3. ~~Check pending event queue and perform single iteration of `vmi_events_listen(vmi, 0)`~~ **Wait until we see all VCPUs actually unpaused**
4. Perform VMI destruction

What I did is that I've implemented `vmi_wait_vm()` function which simply loops over all vCPUs and blocks until it sees all of them either `running` or `blocked` (not simultaneously, just that all vCPUs must be seen scheduled at least for a while).

Here is the mentioned implementation of `vmi_wait_vm`:
https://github.com/libvmi/libvmi/blob/5613d826a2aa3dc9c69a0cafcf915adecb0bae97/libvmi/driver/xen/xen.c#L2747-L2779

and then in the user program, a call to `vmi_wait_vm` should replace this:
```
    if ( vmi_are_events_pending(vmi) > 0 )
        vmi_events_listen(vmi, 0);
```

I've collected some interesting logs:
```
VMI_ERROR: success after 11 iterations for total 4 vCPUs
VMI_ERROR: success after 4 iterations for total 4 vCPUs
VMI_ERROR: success after 12 iterations for total 4 vCPUs
VMI_ERROR: success after 3783 iterations for total 4 vCPUs
VMI_ERROR: success after 11 iterations for total 4 vCPUs
VMI_ERROR: success after 24 iterations for total 4 vCPUs
VMI_ERROR: success after 27 iterations for total 4 vCPUs
VMI_ERROR: success after 33 iterations for total 4 vCPUs
VMI_ERROR: success after 29 iterations for total 4 vCPUs
VMI_ERROR: success after 20 iterations for total 4 vCPUs
VMI_ERROR: success after 18 iterations for total 4 vCPUs
VMI_ERROR: success after 9 iterations for total 4 vCPUs
VMI_ERROR: success after 13 iterations for total 4 vCPUs
VMI_ERROR: success after 13 iterations for total 4 vCPUs
VMI_ERROR: success after 15 iterations for total 4 vCPUs
```

so there was a run in which it looped inside `xen_wait_vm` for 3783 iterations before all vCPUs were actually seen unpaused. With this fix I don't experience crash anymore.

So in simple words: VM needs to run for a little while after clearing CR3 event and we need to make sure that this happens for all vCPUs. Within this time frame it's somehow dangerous to disable the event system.

**Comment by tklengyel** [comment]
Ah! That's a good piece of the puzzle. If you clear the event in the callback, then it should make no difference whether you call `vmi_destroy` before or after the vCPUs are seen as scheduled. The `vmi_destroy` call at that point has no event to disable, it only clears up the monitor ring on the Xen side. There is certainly logic that only gets called when a vCPU resumes executions, it is possible something in there is gated on the monitor ring still being present and when it's not, its skipping the step that's required to emulate the cr3 event.

**Comment by tklengyel** [comment]
OK, I think this is the problem:
https://github.com/tklengyel/xen/blob/master/xen/arch/x86/hvm/hvm.c#L540
```
void hvm_do_resume(struct vcpu *v)
{
    check_wakeup_from_wait();

    pt_restore_timer(v);

    if ( !handle_hvm_io_completion(v) )
        return;

    if ( unlikely(v->arch.vm_event) )
        hvm_vm_event_do_resume(v);
```

If the vCPU doesn't get scheduled before `vmi_destroy` clears up the vm_event ring, this resume logic here skips `hvm_vm_event_do_resume` which would do the emulation!

**Comment by icedevml** [comment]
Looking through the code, I suppose that:

LibVMI destruction for Xen driver calls
```cpp
    if ( xen->libxcw.xc_monitor_disable(xch, dom) )
        errprint("%s error: couldn't disable monitor vm_event ring.\n", __FUNCTION__);
```
which goes there:
```cpp
static int vm_event_disable(struct domain *d, struct vm_event_domain **p_ved)
```
calls
```cpp
vm_event_cleanup_domain(d);
```

which shreds `v->arch.vm_event`
```cpp
void vm_event_cleanup_domain(struct domain *d)
                    
{
    struct vcpu *v;
    for_each_vcpu ( d, v )
    {
        xfree(v->arch.vm_event);
        v->arch.vm_event = NULL;
    }
    d->arch.mem_access_emulate_each_rep = 0;
}
```

which was set here:
```cpp
int hvm_set_cr3(unsigned long value, bool may_defer)
{
    struct vcpu *v = current;
    struct page_info *page;
    unsigned long old = v->arch.hvm.guest_cr[3];
    bool noflush = false;

    if ( may_defer && unlikely(v->domain->arch.monitor.write_ctrlreg_enabled &
                               monitor_ctrlreg_bitmask(VM_EVENT_X86_CR3)) )
    {
        ASSERT(v->arch.vm_event);

        if ( hvm_monitor_crX(CR3, value, old) )
        {
            /* The actual write will occur in hvm_do_resume(), if permitted. */
            v->arch.vm_event->write_data.do_write.cr3 = 1;
            v->arch.vm_event->write_data.cr3 = value;

            return X86EMUL_OKAY;
        }
    }
```
note
```
/* The actual write will occur in hvm_do_resume(), if permitted. */
```
and thus as you said - `hvm_do_resume` doesn't update CR3 in the CPU context which causes the VM unconsciously running with altered CR3 value leading to random crash.

**Comment by tklengyel** [comment]
Yeap, explains everything. Having multiple vCPUs just increased the chances of this happening but could happen with a single vCPU as well. Explains the random nature of the bluescreen itself, why it was not always reproducible, etc. I have a patch to Xen that will be a bit more reasonable then having to poll each vCPU. Will post it soon. But holy damn, this was such a headache to figure out! Wow.

**Comment by icedevml** [comment]
Great that you've managed to figure out what's wrong in HVM after I've somehow guessed the correct workaround :D This is going to vastly improve stability.

**Comment by tklengyel** [comment]
Apply this patch: https://github.com/tklengyel/xen/commit/b70080b610ea3657ca09f6478457b01ec2fd5a8d

Now `xc_monitor_disable` will error out with `-ERESTART` in case there are pending synchronization events. Can just loop until it succeeds, perhaps sleep(1) while it does. As a more elegant solution I've added a vm_event type that will check the domain's status during each `hvm_do_resume` to see if there are any other vCPUs still pending synchronization and if not, sends an event to LibVMI that says its safe to disable: https://github.com/tklengyel/xen/commit/93a41257d5ebde0323a00aa346baf75a35544d2b

**Comment by icedevml** [comment]
Cool. I will test that tomorrow (i.e. after getting a sleep), my sanity is completely lost right now :P

**Comment by icedevml** [comment]
Side note, with this new Xen I receive a build error inside QEMU

This patch by Greg Kroah-Hartman helps to resolve the problem:
```diff
--- a/include/uapi/linux/swab.h
+++ b/include/uapi/linux/swab.h
@@ -135,9 +135,9 @@ static inline __attribute_const__ __u32
 
 static __always_inline unsigned long __swab(const unsigned long y)
 {
-#if BITS_PER_LONG == 64
+#if __BITS_PER_LONG == 64
 	return __swab64(y);
-#else /* BITS_PER_LONG == 32 */
+#else /* __BITS_PER_LONG == 32 */
 	return __swab32(y);
 #endif
 }
```

Source: https://lkml.org/lkml/2020/5/1/640

**Comment by tklengyel** [comment]
Sigh, there are many issues like that with master at the moment. I ran into https://lists.xenproject.org/archives/html/xen-devel/2020-05/msg00280.html

**Comment by icedevml** [comment]
Installing Win7 x64 right now, there is some strange stuff going on with the graphics mode.

![image](https://user-images.githubusercontent.com/6976513/82048734-75556880-96b5-11ea-9bc3-e925cbfc5395.png)

There is some weird colour depth and the UI is much less responsive than normally o_O WTF

**Comment by icedevml** [comment]
:thinking: Maybe I will rebase these patches to Xen 4.13 stable and then perform some testing...

**Comment by tklengyel** [comment]
Yea, that's an option. I had to do that with some other Xen patches of mine because 4.14 was too unstable.

**Comment by icedevml** [comment]
@tklengyel For the second patch I guess there should also be a corresponsing change in `arch_monitor_get_capabilities` so it is possible to distinguish if currently running Xen supports this special sync event or not?

**Comment by icedevml** [comment]
For the transition moment I'd add

**Comment by tklengyel** [comment]
I think it will be enough to just get the vm_event version.

**Comment by tklengyel** [comment]
This is the commit that introduced this regression to Xen: http://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=96760e2fba100d694300a81baddb5740e0f8c0ee. Early versions of this MOV-TO-CR3 didn't have this issue because it got emulated before the event was sent out, not after.

**Comment by tklengyel** [comment]
Makes me think that perhaps we should do that all the time unless the user requests that they use the feature that's introduced in the above patch.

**Comment by tklengyel** [comment]
I think intsead of that vm_event route that waits for the event to be disabled I'll just add a domctl you need to use to explicitely _enable_ this feature. Otherwise the emulation happens right away and we don't have this issue. So only people who use this feature will have to deal with it during shutdown.

**Comment by icedevml** [comment]
Seems to be a fair option too. Then it will work without any changes to LibVMI in particular.

**Comment by tklengyel** [comment]
Actually, no reason we can't have all of them. I'll just send all three patches in.

**Comment by tklengyel** [comment]
Patches are up at https://github.com/tklengyel/xen/tree/vm_event_disable_safely

Posted at https://lists.xenproject.org/archives/html/xen-devel/2020-05/msg00862.html

Cheers ;)

**Comment by icedevml** [comment]
Thanks for posting the patches to Xen. Right now I've tested with the following setup:

Xen 4.13.0 with your patches (rebased):
https://github.com/icedevml/xen/tree/RELEASE-4.13.0-patch-vmevent

Guest: Windows 7 x64, 2 VCPUs

Works like a charm!

**Comment by tklengyel** [comment]
Great! If you can send the test result as a reply to that thread on xen-devel that would be helpful.

**Comment by icedevml** [comment]
Sure. Will do in a moment.

**Comment by icedevml** [comment]
@tklengyel Will it work properly if I just send an email with `Re: [PATCH 1/3] xen/monitor: Control register values` to xen-devel@? I'm not too familiar with mailing lists (wow, soo '90).

**Comment by tklengyel** [comment]
A reply to the cover letter is probably better. Also, don't top-post ;)

**Comment by tklengyel** [comment]
And yes, the whole Xen development flow is seriously antiquated and IMHO embarrasing in 2020..

**Comment by icedevml** [comment]
Posted. I will also make some more extensive tests if some spare time gets succesfully allocated.
