### ISSUE TITLE
Problem with introspection on multiple machines and KVM

### ISSUE THREAD

**Issue by 0xarash** [libvmi/libvmi#919]
I'm trying to introspect over multiple machines (the goal is this machines be introspected in parallel). 

Here is my test environment:

- LibVMI (master branch) and recent new KVM driver (kvmi branch). 
- My Host is CentOS 7
- My guest machines are Windows 7 32-bit and Windows 10 64-bit 
- My tests are mostly based on LibVMI and python biding examples, actually vmi-process-list, vmi-win-guid, process-list.py (without any modification)
- QEMu arguments also are same for every machines

The problem is that sometimes I get introspection result from wrong machine, and I execute each example on each machines multiple times and switch between them to trigger this problem.

- Some tests goes to to end of their execution for example with vmi-win-guid (result still from wrong machine)
- Some tests stop working in case of process-list 
    - For example I tried to introspect Windows 10 64 bit, but it detect page-mode as (VMI_PM_LEGACY or VMI_PM_PAE) which then use FS_BASE as register which is wrong for 64-bit windows, from here it stuck in handshaking every time with different uuid, and then some step further it throw some error where it could not find System process and fail.
- and FYI if I power-on every machine one at a time everything work as expected. 

And as I test the codes I use are the examples provided by LibVMI and python binding (as is)

Appreciate any help

**Comment by Wenzel** [comment]
a quick idea: do you use the same KVMi socket for each VM ? (`/tmp/introspector` in the examples)
Each VM should have its own socket.

**Comment by 0xarash** [comment]
> a quick idea: do you use the same KVMi socket for each VM ? (`/tmp/introspector` in the examples)
> Each VM should have its own socket.

I do, actually I asked this question in Slack (whether socket should be same or not) and I guess one of the kvmi developer said It's OK to "remain the same", based on that I followed this path.

**Comment by 0xarash** [comment]
I tested again, changing socket solved my problem, 
thanks @Wenzel
