### ISSUE TITLE
examples/CMakeFiles/vmi-win-offsets.dir/build.make:95: recipe for target 'examples/vmi-win-offsets' failed

### ISSUE THREAD

**Issue by liuya0904** [libvmi/libvmi#923]
Hi,

I am trying to install libvmi from source on a Ubuntu 20.04 amd64 machine. The following errors were encountered:

[  5%] Built target config_parser
[ 35%] Built target vmi
[ 51%] Built target vmi_shared
[ 52%] Built target vmi_static
[ 55%] Built target vmi-win-guid
[ 57%] Built target vmi-module-list
[ 60%] Built target vmi-dump-memory
[ 62%] Built target va-pages
[ 64%] Built target map-symbol
[ 67%] Built target vmi-process-list
[ 69%] Built target map-addr
[ 71%] Built target cr3-event-example
[ 74%] Built target msr-event-example
[ 76%] Built target event-example
[ 78%] Built target singlestep-event-example
[ 81%] Built target descriptor-event-example
[ 83%] Built target interrupt-event-example
[ 85%] Built target fool-patchguard
[ 88%] Built target wait-for-domain-example
[ 90%] Built target breakpoint-emulate-example
[ 91%] Linking C executable vmi-win-offsets
CMakeFiles/vmi-win-offsets.dir/win-offsets.c.o: In function `main':
/home/robin/libvmi/examples/win-offsets.c:310: undefined reference to `vmi_get_kernel_json'
/home/robin/libvmi/examples/win-offsets.c:312: undefined reference to `vmi_get_struct_member_offset_from_json'
/home/robin/libvmi/examples/win-offsets.c:314: undefined reference to `vmi_get_struct_member_offset_from_json'
/home/robin/libvmi/examples/win-offsets.c:320: undefined reference to `vmi_get_struct_member_offset_from_json'
/home/robin/libvmi/examples/win-offsets.c:325: undefined reference to `vmi_get_struct_member_offset_from_json'
/home/robin/libvmi/examples/win-offsets.c:330: undefined reference to `vmi_get_struct_member_offset_from_json'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/vmi-win-offsets.dir/build.make:95: recipe for target 'examples/vmi-win-offsets' failed
make[2]: *** [examples/vmi-win-offsets] Error 1
CMakeFiles/Makefile2:1128: recipe for target 'examples/CMakeFiles/vmi-win-offsets.dir/all' failed
make[1]: *** [examples/CMakeFiles/vmi-win-offsets.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by allewwaly** [comment]
I've met the same problem, how did you solved it?
