### ISSUE TITLE
Problems with event related examples

### ISSUE THREAD

**Issue by auermich93** [libvmi/libvmi#949]
Hi Tamas,

the christmas break brought me some time to play around with Xen and libvmi. I have setup Xen 4.11 on the Debian 10 (4.19),
created a simple domU VM (PV guest) and tried out the examples shipped with libvmi. While `vmi-process-list` or `vmi-module-list` work, examples dealing with events, e.g. `cr3-event-example`,` interrupt-event-example` or `mem-event-example` fail. In particular, running the `cr3-event-example `causes the VM to get in an unreachable/unresponsive state. Debugging enabled produces the following output:

```
**The running Xen version is 4.11
--found Xen
Running Bareflank CPUID signature: 1 2 256 1
LibVMI Version 0.13.0
LibVMI Driver Mode 0
**The running Xen version is 4.11
--completed driver init.
--got id from name (vm1 --> 6)
**set image_type = vm1
**guest address width is 8 bytes
**set vm_type PV64
--xen: setup live mode
**set allocated_ram_size = 80000000, max_physical_address = 0x80101000
WARNING: driver_set_reg_w_access function not implemented.
Destroying memaccess on gfn events
Destroying memaccess generic events
Destroying register events
Destroying MSR events
Destroying singlestep events
Destroying interrupt events
Destroying clear events
```

The output of `xl list`:
```

Name                                        ID   Mem VCPUs      State   Time(s)
Domain-0                                     0  3070     4     r-----    3663.7
vm1                                          6  2048     1     --p---       8.3

```
And finally `xl info:`

```
host                   : debian
release                : 4.19.0-13-amd64
version                : #1 SMP Debian 4.19.160-2 (2020-11-28)
machine                : x86_64
nr_cpus                : 4
max_cpu_id             : 3
nr_nodes               : 1
cores_per_socket       : 2
threads_per_core       : 2
cpu_mhz                : 2527.009
hw_caps                : bfebfbff:0298e3ff:28100800:00000001:00000000:00000000:00000000:00000100
virt_caps              : hvm hvm_directio
total_memory           : 6004
free_memory            : 2845
sharing_freed_memory   : 0
sharing_used_memory    : 0
outstanding_claims     : 0
free_cpus              : 0
xen_major              : 4
xen_minor              : 11
xen_extra              : .4
xen_version            : 4.11.4
xen_caps               : xen-3.0-x86_64 xen-3.0-x86_32p hvm-3.0-x86_32 hvm-3.0-x86_32p hvm-3.0-x86_64 
xen_scheduler          : credit
xen_pagesize           : 4096
platform_params        : virt_start=0xffff800000000000
xen_changeset          : 
xen_commandline        : placeholder dom0_mem=3G,max:3G
cc_compiler            : gcc (Debian 8.3.0-6) 8.3.0
cc_compile_by          : pkg-xen-devel
cc_compile_domain      : lists.alioth.debian.org
cc_compile_date        : Fri Dec 11 21:33:51 UTC 2020
build_id               : 6d8e0fa3ddb825695eb6c6832631b4fa2331fe41
xend_config_format     : 4
```
Is the warning actually the problem? If yes, any idea how to fix it?
Thanks for your help.

**Comment by icedevml** [comment]
> WARNING: driver_set_reg_w_access function not implemented.

This seems to be meaningful especially that you say that process list works but CR3 event (dependent exactly on this function) does not.

**Comment by icedevml** [comment]
Are you using the correct driver? This looks like using a bare file driver or something, so pure static stuff works while event-driven stuff does not.

**Comment by auermich93** [comment]
@icedevml, are you talking about a driver of LibVMI, i.e. a configuration option of LibVMI, or do I need to pass some additional option to `xen-create-image`, or does Xen itself require a modification?

**Comment by icedevml** [comment]
You don't need modified Xen but anyway your Xen version seems to be pretty old. Right now we are commonly using RELEASE-4.14.1. Could you first try to update Xen to 4.14.1 and check whether the problem persists?

**Comment by auermich93** [comment]
Well, Debian 10 offers only Xen 4.11 in its stable repository. I tried to fetch the newest version of Xen from the unstable repository, but upgrading doesn't succeed due to (transitive) conflicts of libgcc-8-dev. Any other suggestions?

**Comment by smaresca** [comment]
@auermich93 please create a Xen domain which is HVM rather than paravirtual, and that will allow events to function for you.

**Comment by auermich93** [comment]
@smaresca I try, but creation of a HVM guest via `xl create` stucks with the message 'Parsing config from /etc/xen/vm1.cfg'. I have checked that all relevant hardware accelerations (VT-x, VT-d) are turned on. Any logs that could be helpful?
