### ISSUE TITLE
Where can i get the `ctx` variable?

### ISSUE THREAD

**Issue by qianfei11** [libvmi/libvmi#970]
I want to use `vmi_translate_v2ksym` to get a syscall symbol name, but i have no idea about this `ctx` variable. Where can i get the `ctx` variable? And i can't find any examples of using `vmi_translate_v2ksym` in the repo, can i get any help?

```cpp
/**
 * Performs the translation from VA to a symbol for Linux with KASLR offset
 * Windows is not supported at this moment
 * Only the first matching symbol of System.map is returned.
 *
 * @param[in] vmi LibVMI instance
 * @param[in] ctx Access context
 * @param[in] va VA to translate
 * @return Symbol, or NULL on error
 */
const char* vmi_translate_v2ksym(
    vmi_instance_t vmi,
    const access_context_t *ctx,
    addr_t va) NOEXCEPT;
```

**Comment by icedevml** [comment]
First of all, as far as I see, this function is supported only for Linux systems at the moment, it is not implemented for Windows.

As virtual addresses are only meaningful in the context of particular process, you need to provide that context using such kind of structure:

Example:
```cpp
        access_context_t ctx = {
            .translate_mechanism = VMI_TM_PROCESS_PID,
            .pid = 1337
        };
```

So you need to pass the virtual address of your interest using `va` argument, and pass the context of this address using `ctx` argument. If the translation is successful, the function will return a string with a symbol name.

**Comment by qianfei11** [comment]
@icedevml Thanks, this works for me.
