### ISSUE TITLE
Question on struct layout randomization in the Linux kernel

### ISSUE THREAD

**Issue by loresuso** [libvmi/libvmi#987]
I would like to obtain the list of processes running inside a virtual machine. I've seen the example in process-list.c but I have a question: how do you deal with struct layout randomization? On the basis of this [article](https://lwn.net/Articles/722293/), important data structures have a randomized layout at compile time, meaning that fields does not reside in memory in the order they are declared. How do you know the correct offsets with this complication?

**Comment by chivay** [comment]
Hi,
libvmi uses profiles generated from debug symbols created by the compiler. So, there's no difference from libvmi perspective.
